### ISSUE TITLE
Assertion failure on iPhone 5s at pixelsPerInchForCurrentDevice

### ISSUE THREAD

**Issue by rrbrambley** [SVGKit/SVGKit#106]
iPhone6 is not an acceptable prefix for the value of hw.machine, causing this assertion failure: NSAssert(FALSE, @"Not supported yet: you are using an iPhone that didn't exist when this code was written, we have no idea what the pixel count per inch is!");

**Comment by adamgit** [comment]
Appears fixed, not sure why this is still open, closing...
