### ISSUE TITLE
Image parse but not draw when using "use" 

### ISSUE THREAD

**Issue by flemingm** [SVGKit/SVGKit#108]
Fixed bug in SVGKParserDefsAndUse.m  
Y was stored in X instead of Y.
and added log message to confirm parsing was correct.

But don't know how to fix drawing issue parsing Quebec Flag at:
http://en.wikipedia.org/wiki/File:Flag_of_Quebec.svg

---

The fix and the Log message in:
- (Node_) handleStartElement:(NSString *)name document:(SVGKSource_) SVGKSource namePrefix:(NSString_)prefix namespaceURI:(NSString_) XMLNSURI attributes:(NSMutableDictionary _)attributes parseResult:(SVGKParseResult *)parseResult parentNode:(Node_) parentNode
  {
  ...

if( [name isEqualToString:@"use"])
        {
            /*\* NB: must supply a NON-qualified name if we have no specific prefix here ! */
            SVGUseElement *useElement = [[[SVGUseElement alloc] initWithQualifiedName:qualifiedName inNameSpaceURI:XMLNSURI attributes:attributes] autorelease];

```
        [useElement postProcessAttributesAddingErrorsTo:parseResult]; // handles "transform" and "style"

        if( [attributes valueForKey:@"x"] != nil )
            useElement.x = [SVGLength svgLengthFromNSString:[((Attr*)[attributes valueForKey:@"x"]) value]];
        if( [attributes valueForKey:@"y"] != nil )
            useElement.y = [SVGLength svgLengthFromNSString:[((Attr*)[attributes valueForKey:@"y"]) value]];
        if( [attributes valueForKey:@"width"] != nil )
            useElement.width = [SVGLength svgLengthFromNSString:[((Attr*)[attributes valueForKey:@"width"]) value]];
        if( [attributes valueForKey:@"height"] != nil )
            useElement.height = [SVGLength svgLengthFromNSString:[((Attr*)[attributes valueForKey:@"height"]) value]];

        NSString* hrefAttribute = [useElement getAttributeNS:@"http://www.w3.org/1999/xlink" localName:@"href"];

        NSAssert( [hrefAttribute length] > 0, @"Found an SVG <use> tag that has no 'xlink:href' attribute. File is invalid / don't know how to parse this" );
        if( [hrefAttribute length] > 0 )
        {
            NSString* linkHref = [((Attr*)[attributes valueForKey:@"xlink:href"]) value];

            NSAssert( [linkHref hasPrefix:@"#"], @"Not supported: <use> tags that declare an href to something that DOESN'T begin with #. Href supplied = %@", linkHref );

            linkHref = [linkHref substringFromIndex:1];

            /** have to find the node in the DOM tree with id = xlink:href's value */
            SVGElement* linkedElement = (SVGElement*) [parseResult.parsedDocument getElementById:linkHref];

            NSAssert( linkedElement != nil, @"Found an SVG <use> tag that points to a non-existent element. Missing element: id = ", linkHref );


            useElement.instanceRoot = [self convertSVGElementToElementInstanceTree:linkedElement outermostUseElement:useElement];
            // debug parsing of USE
            NSLog(@"linkedElement: %@ (%d x %d)\ninstanceRoot %@", linkedElement ,  (int) [useElement.x value], (int) [useElement.y value], useElement.instanceRoot);
        }

        return useElement;
    }
```

**Comment by adamgit** [comment]
Ouch, good catch.

So far I haven't got SVG "use" working at all - the x/y mixup might be enough, the thing to test it on is the Reinel Compass Rose in the test-suite that's embedded in SVGKit (run the "Demo-iOS" project). There's a simplified SVG there that should be easy to render.

I'd like to have another go at this, but it could be half a year or more before I get time to try again :(

**Comment by sum111** [comment]
Excuse me, this problem is solved?

**Comment by flemingm** [comment]
Here is a simple file for testing and the expected results.:

in the folder on dropbox at:
https://www.dropbox.com/sh/tlyl1h5eqr1mrgj/AAABOnw6UieqPYEIogvoEttca?dl=0

I will try to download current dev branch and confirm it's fixed.

**Comment by flemingm** [comment]
fixed in issue 384.  we can close this issue.
