### ISSUE TITLE
Loading a lot of SVG Images

### ISSUE THREAD

**Issue by IgorBulyga** [SVGKit/SVGKit#109]
Hi! I'm loading about 30 SVG images with imageNamed: in a loop and it take on iPhone 4s about 15-20 seconds. Should it be so? Or it can be issue with SVG files? If so then how can I improve performance of loading? Thank you!

**Comment by adamgit** [comment]
Firstly, try the 1.x branch - I committed some changes to the parser a few weeks ago that have a huge impact on _some_ SVG files.

Secondly ... is it one of them in particular is slow, or is it all of them?

Try running with Instruments (use "Profile" / cmd-I from the Xcode Product menu), and watch the memory usage and CPU usage. Which is worse?

**Comment by adamgit** [comment]
No response, so I'm closing this.
