### ISSUE TITLE
SVGKit working with Illustrator SVGs?

### ISSUE THREAD

**Issue by omphe** [SVGKit/SVGKit#11]
I've been trying a number of SVG libraries today, in an attempt to get some images rendering in our iOS project.  SVGKit seems to handle the Illustrator generated files we have, the most gracefully, but it still seems to be choking on a number of the xml elements in the file (e.g. pgf).   

While other libraries are having the same issues, I was just wondering if there are any known issues with Illustrator formats and the SVGKit libraries?

Awesome work and thanks for the contribution to the community.  Hopefully I can use it on this occasion, but I'll definitely turn to it in the future.

**Comment by codingstyle** [comment]
I've been through issues with Illustrator files too. 
Main issues found on parser :
- very compact notation for path elements (spaces can be omitted between coordinates)
- smoothhand/curveto ("S" and "s") is not implemented
- "display = none" not supported on graphic element ("<g>")

I'm currently adding some enhancements on the project and hope to publish it when I have some spare time :)

**Comment by adamgit** [comment]
Update: I've fixed a bunch of low-level problems that were breaking Illustrator SVG files in my branch - https://github.com/adamgit/SVGKit/tree/transforms - which we'll try to merge into main very soon.

(I fixed most of the stuff to do with transforms - although some transforms are implemented, but aren't being parsed, e.g. pure ROTATIONS are ignored, but rotations as part of MATRIX operations are handled correctly)

**Comment by adamgit** [comment]
That's all now in the 2013base branch
