### ISSUE TITLE
SVGKit won't load SVG from URL

### ISSUE THREAD

**Issue by johanndiedrick** [SVGKit/SVGKit#114]
I'm running into this problem. I set up a simple empty iOS project and placed the following code in ViewController.m's viewDidLoad:

```
NSLog(@"Loading main view");

NSLog(@"Trying to load a SVG from the internet");

// Splitting URL to multiple lines to make blogpost
//    easier to read...
NSString* longURL = [NSString stringWithFormat:@"%@%@%@",
                     @"http://upload.wikimedia.org/",
                     @"wikipedia/commons/f/fd/",
                     @"Ghostscript_Tiger.svg" ];

NSURL* url = [NSURL URLWithString:longURL];

SVGKImage* newImage = [SVGKImage imageWithContentsOfURL:url];
```

Unfortunately it results in the following error:

[SVGKImage] ERROR: failed to init SVGKImage with source = (null), returning nil from init methods

Any ideas?

**Comment by adamgit** [comment]
I believe this is now fixed, a couple of commits ago. A couple of us did a complete rewrite of the remote loading code. If not, open new issues for specific problems (the code has been replaced)
