### ISSUE TITLE
fill-opacity gets ignored if fill attribute not present

### ISSUE THREAD

**Issue by sakamura** [SVGKit/SVGKit#115]
Here is a simple SVG:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="1024" height="1024" viewBox="0, 0, 1024, 1024">
  <g id="Layer 1">
    <g>
      <path d="M545.23,333.478 C487.843,333.478 441.322,289.424 441.322,235.08 C441.322,180.737 487.843,136.683 545.23,136.683 C602.617,136.683 649.138,180.737 649.138,235.08 C649.138,289.424 602.617,333.478 545.23,333.478 z" fill-opacity="0" stroke="#000000" stroke-width="1"/>
    </g>
  </g>
  <defs/>
</svg>
```

The path's fill-opacity="0" gets ignored by the parser, and thus shows a black circle.

However, if you add up fill="#c00000" to the attributes, it will render properly.

Patch was created by moving things around in SVGHelperUtilities newCALayerForPathBasedSVGElement:

``` objc
    NSString* actualFill = [svgElement cascadedValueForStylableProperty:@"fill"];
    NSString* actualFillOpacity = [svgElement cascadedValueForStylableProperty:@"fill-opacity"];
```

[snip]

``` objc
    else if( actualFill.length > 0 || actualFillOpacity.length > 0)
    {
        SVGColor fillColorAsSVGColor = ( actualFill.length > 0 ) ?
            SVGColorFromString([actualFill UTF8String]) // have to use the intermediate of an SVGColor so that we can over-ride the ALPHA component in next line
            : SVGColorMake(0, 0, 0, 0);

        if( actualFillOpacity.length > 0 )
            fillColorAsSVGColor.a = (uint8_t) ([actualFillOpacity floatValue] * 0xFF);

        _shapeLayer.fillColor = CGColorWithSVGColor(fillColorAsSVGColor);
    }
```

Caveat of patch is it uses a default SVGColorMake. There could be a verification to make sure either fill is there or opacity is 0 to make sure it's only being used to clear fills

**Comment by adamgit** [comment]
From reading the spec, your interpretation sounds correct to me.

"fill" explicitly defaults to "black" in the spec.

I've added your patch to 1.x, and included the SVG file above as "sakamura-default-fill-opacity-test.svg" to prove its working.

**Comment by sakamura** [comment]
Works well! Thank you for the patch! :)

PS: the culprit editor is iDraw on iOS. They are also weird, as they'll create two objects with the same path: one for the fill and one for the stroke... But hey, it works :) And now, that part of their files work adequately on SVGKit.
