### ISSUE TITLE
SVN problem

### ISSUE THREAD

**Issue by gerchicov** [SVGKit/SVGKit#118]
Your instruction for including into another project is incorrect.

If many people work under this project and one of them added SVGKit by the way you wrote then other people would get linker errors

**Comment by adamgit** [comment]
Thanks - I tested this extensively, but most of us use the library as a static-library, so we don't understand very well how to embed the project file.

If you could explain what's wrong, and how we should be doing it instead, we could change it?

**Comment by adamgit** [comment]
NB: there is a MAJOR bug in Xcode5 where it corrupts your build-settings, causing the problem you describe - is that what you're referring to?

It's definitely an Apple bug, and I keep hoping they'll fix it. If not, we may have to hack a workaround :(.
