### ISSUE TITLE
Please Tag V1.1 for use w/ Cocoapods (if ready)

### ISSUE THREAD

**Issue by augustj** [SVGKit/SVGKit#119]
I'd like to create a v1.1 cocoapod spec that includes the fixes for iOS7.  Cocoapods require tags, rather than just a branch/ref.
If 1.1 is ready, could you please tag it?
Thanks.

**Comment by adamgit** [comment]
Done!

https://github.com/SVGKit/SVGKit/releases/tag/v1.1.0

(re-open if that doesn't work - I checked it, and it seems to have gone to the main repo OK)

**Comment by foulkesjohn** [comment]
Is there a podspec for 1.1.0? I've tried to make my own but I'm hitting issues

**Comment by augustj** [comment]
@foulkesjohn 
I ended up copying the existing to make my own version that excluded the CocoaLumberjack files and defined ddLogLevel as extern.
Here is my repo of podspecs: https://github.com/augustj/Cocoapods_Specs
There have been recent changed in CocoaLumberjack regarding definition of ddLogLevel.  Here's the thread for that:  https://github.com/CocoaLumberjack/CocoaLumberjack/pull/162

I have not updated my spec to reflect the recent 1.1.0 tagging yet - mine still pulls from master (but that should be easy for you to change).
