### ISSUE TITLE
SVGKit will require minimum of Xcode v4.5 - comment if this will cause you problems

### ISSUE THREAD

**Issue by adamgit** [SVGKit/SVGKit#127]
We'd like to convert the codebase to using the new Objective-C features that Apple introduced with Xcode 4.5.

If we do this, SVGKit will no longer compile or build on Xcode 3.x, Xcode 4.0-4.4. This affects approximately 500-1,000 lines of code, and will only increase going forwards. I'm not proposing to backport ANY future changes to pre Xcode-4.5.

We _think_ that everyone's using 4.5 or newer (current version is 5.0.2). But we've no way of checking. If you're stuck on 4.4 or earlier, please comment on this issue, let us know who you are, and why you're unable to use current/recent Xcode versions.

Thanks!

**Comment by n8v** [comment]
This is fine with me-- just wanted to let you know someone's paying attention.

**Comment by sakamura** [comment]
Using latest&greatest (5.0.2) here. No problem. Actually the opposite, can't wait for SVGKit to use ARC, as I had to change my framework to remove ARC for SVGKit, and add up ARC for the newly used logging framework files, all in all quite a mess.

However (and this will annoy me too ;) ), may I suggest that you actually do most of the fixes on the latest version, fix what needs to be fixed if required, push a version, say "this is the last version that will be supported using XCode 3 to 4.4", and then do the changes to 4.5, fix what needs to be fixed, and create the official 4.5-5.x version in a matter of days. That way, if anyone is annoyed by this, they won't have to search for the precise last version that works, and if they want to support it, they can do so at their leisure by forking that precise version.

**Comment by adamgit** [comment]
OK. We're not at 100% coverage of the SVG spec yet - I'd like to get everything covered (or at least: everything-except-animation (Because almost no-one uses animated SVG's - even Inkscape doesn't support them yet)) before we do a major version-bump.

MaddTheSane has a huge list of fixes and changes, that might help a lot - but there's too many for me to verify. I need some volunteers to go through and pull out some individual fixes and make them into smaller commits for us to test.

I'll leave this issue open as an FYI to anyone new coming to the project

**Comment by adamgit** [comment]
@sakamura I'm sorry to hear you've had problems with ARC. Unfortunately, most people seem to be avoiding ARC still. But I thought it was easy to have non-ARC code in an ARC project (that was Apple's promise!).

Is there anything we can do short-term to make it easier?

NB: the CocoaLumberjack guys have tweaked the Logger with some changes we need to start using, so I'm expecting to do changes there soon anyway.

**Comment by adamgit** [comment]
This has happened, done, dusted, too late to change now :).
