### ISSUE TITLE
Can only export to a particular NSData format

### ISSUE THREAD

**Issue by sakamura** [SVGKit/SVGKit#128]
The NSData exporter "- exportNSDataAntiAliased" only allows for one particular colorSpace (RGB no alpha). I export my images to SpriteKit and don't really need to use UIImage or other systems. However, my SVGs are sometimes with premultiplied alpha channel.

Few suggestions for that "low-level" exporter:
- Add up the possibility to set up the Alpha Channel parameter at least, which might be the one most often modified by end users, and it won't require changes calculating the byte size. Ability to create other formats might be a little bit harder problem to tackle.
- Move the NSAssert( infinite size ) to renderToContext
- Make renderToContext public to create your own exporter, including creating weird colorSpaces. I don't believe there's any rationale in keeping renderToContext private.

**Comment by adamgit** [comment]
It's private for two reasons:
1. We don't have test cases for the code, and the code is far from perfect
   :). I put it together quickly, and as soon as it worked for my limited use
   cases (export to OpenGL textures), I stopped testing.
2. I want to refactor these methods out of SVGKImage. I want SVGKImage to
   be as close as possible _identical_ to UIImage's method signature, so it's
   easier for people new to SVGKit to understand.

My plan was to create a standardized set of classes / method names for each
stage of SVGKit:
- loading a file / parsing it into SVGElements
- exporting an SVG / serializing it to NSString
- converting an SVG to a graphical render / converting it to bitmap

Part 1 is fairly clean with the SVGKParser ... that uses SVGKSource.h and
subclasses.
Part 3 I planned to do something like "SVGKConverter", and move all the
SVGKImage methods that generate CALayers - and the renderInContext - method
to there
Part 2 I planned to do something like "SVGKExporter", and make it support
the same SVGKSource objects as SVGKParser

...AND: make sure [SVKGImage imageNamed:] automatically re-uses all of that
correctly. So that you could be lazy and "imageNamed:" to load an image,
but then modify it, and save it back to disk _without remembering the
filename_, just by doing something like:

[SVGKExporter exportToOriginalLocation:(SVGKImage*)
overwritingExistingFile:(BOOL)]

...and because SVGKImage keeps track of its SVGKSource, the expoter
wouldn't need any additional information, it would Just Work.

**Comment by adamgit** [comment]
PS: Apple hasn't documented their formats for passing images around as
NSData. I filed a bug and was told "it's obvious" - we (Apple) use mangled
compressed data streams. Raw arrays of image data are not-supported.

Huh? Raw byte arrays - are exactly what Apple's own CoreGraphics exports!

So ... yeah. There was a lot of trial and error to get the image code working, and I wasn't very confident of it. But it seems to work at the moment

**Comment by adamgit** [comment]
PPS: ... I would really really like to see the Exporter stuff modelled on the extensible SVGKParser's we already have - as much as possible, make the library consistent!

...but I didn't get as far as coming up with a neat way to support modular / configurable Converters that are consistent with the other two. If you can do that - or even come up with something that's a good first attempt - I think it would be a great step forwards.

But consistency is a big thing. SVGKit 3 years ago had so many different ways of doing things it took ages to work out how to do anything new. I want to avoid that.

**Comment by sakamura** [comment]
Hahaha! I understand that, and I agree to put the drawing code in the UIImage lookalike is a hack, it'd be preferable to have this code reside elsewhere. Code could be prepared with the animation requirement, as stated in another issue, and to make sure everything is consistent and future-proof.

Well, on my issue, I'm still open to suggestions. :) If I take my own texture code for SpriteKit, that does work, but requires renderToContext to be public, I have the following calling code (My interface file is FGKTexture so nevermind finding that on the Net :) ):

[EDIT : I had copy-pasted the bad thing here ... Updated for the proper code]

``` ObjC
NSData *data = [FGKTexture readSvgFromFile:name];
SVGKImage *svg = [SVGKImage imageWithSource:[SVGKSource sourceFromData:data]];
skTexture = [SKTexture textureWithData:[FGKTexture renderSvg: svg] size:[svg size]];
```

(if it can be used by other peeps, I public domain whatever's there)
And this is the code I use to create textures. SKTexture does a copy of the NSData to its own stuff, so I only need to allocate VM temporarily, hence the messy approach.

``` ObjC
// Temporary texture management is done directly in vm_allocations to reduce device strain
+ (char *)allocateVirtualMemory: (size_t)size
{
    char*          data;
    kern_return_t   err;

    size = (size+4095)/4096*4096;

    // Allocate directly from VM
    err = vm_allocate((vm_map_t) mach_task_self(),
                      (vm_address_t*) &data,
                      size,
                      VM_FLAGS_ANYWHERE);

    // Check errors
    NSAssert(err == KERN_SUCCESS, @"No vm_allocate success!");
    if(err != KERN_SUCCESS)
    {
        data = NULL;
    }

    return data;
}

+ (void)deallocateVirtualMemory: (char *)data size:(size_t)size
{
    size = (size+4095)/4096*4096;

    vm_deallocate((vm_map_t) mach_task_self(),
                  (vm_address_t)data,
                  size);
}

+ (NSData *)renderSvg: (SVGKImage *)svg
{
    // This code is based on SVGKit's exportNSDataAntiAliased. Modified to support premult alpha and remove NSData copy.
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = CGBitmapContextCreate( [FGKTexture allocateVirtualMemory:( svg.size.width * svg.size.height * 4 )], svg.size.width, svg.size.height, 8, 4 * svg.size.width, colorSpace, (CGBitmapInfo)kCGImageAlphaPremultipliedLast );
    CGColorSpaceRelease( colorSpace );

    [svg renderToContext:context antiAliased:YES curveFlatnessFactor:1. interpolationQuality:kCGInterpolationDefault flipYaxis: NO];

    void* resultAsVoidStar = CGBitmapContextGetData(context);

    size_t dataSize = 4 * svg.size.width * svg.size.height;
    NSData* result = [[NSData alloc] initWithBytesNoCopy:resultAsVoidStar length:dataSize deallocator:^(void *bytes, NSUInteger length)
    {
        [FGKTexture deallocateVirtualMemory:bytes size:length];
    }];

    CGContextRelease(context);

    return result;
}

+ (NSData *)readSvgFromFile: (NSString *)name
{
    // Code from SVGImage
    NSBundle *bundle = [NSBundle mainBundle];

    if (!bundle)
        return nil;

    NSString *newName = [name stringByDeletingPathExtension];
    NSString *extension = [name pathExtension];
    if ([@"" isEqualToString:extension]) {
        extension = @"svg";
    }

    NSString *path = [bundle pathForResource:newName ofType:extension];

    if (!path)
    {
        NSLog(@"[%@] MISSING FILE, COULD NOT CREATE DOCUMENT: filename = %@, extension = %@", [self class], newName, extension);
        return nil;
    }

    NSData* result = [NSData dataWithContentsOfFile:path];
    return result;
}
```

**Comment by sakamura** [comment]
I have changed yet again the SVG rendering code in my project, which led me to think, more I see it, more I believe one of the the inner functionality of SVGKit is to actually render to a CGContext. A user could theoretically decide to put the SVGs inside his own CGContext rendering, and use the drawing as a primitive.

So ATM, I would suggest you simply make renderToContext public (but advanced). Especially since it's public source, so people can actually get "inspired" by the inner default code as much as they want, if they want to render to a PDF or a printer, or whatnot.

**Comment by adamgit** [comment]
OK, I've:
1. Made the renderInContext public (with some warnings in the header file docs!)
2. Removed this from SVGKImage, and placed it into a category on SVGKImage. If you import the categories (e.g. SVGKImage+CGContext) you get this AND the old method (with the extra options)
3. Moved the exporters into their own classes - e.g. SVGKExporterNSData, and SVGKExporterUIImage
4. Added "simpler" versions of the Export methods, that use the Apple defaults for the other settings
5. Greatly improved the flexibility of the process (see below)

The old approach: "call a special exporter method, which makes its own context internally"

The new approach: "request a CGContextRef, or supply one of your own, then proceed as before"

The big difference here is that many use-cases have their own CGContextRef to start with, and want the SVG written _directly_ into it - they don't want an extra copy of the bitmap in memory (it can be a hundred megabytes or more for a large one!).

https://github.com/SVGKit/SVGKit/commit/fc999d1c285cd48b9a1c53172837ea67bf23db2e
