### ISSUE TITLE
Getting started instructions are wrong for iOS

### ISSUE THREAD

**Issue by adamgit** [SVGKit/SVGKit#13]
Instructions say: "drag/drop the iOS and Core folders to your project"

There are additional _REQUIRED_ instructions:
1. you MUST edit "Header Search Paths" and add /usr/share/include/libxml2
2. you MUST edit the Build Phases, and add to the Libraries phase: libxml2

Additionally, the current git repos won't build even when you've done that because of a const-error. I'm not sure why the SVGPad example compiles OK with this - I guess you ALSO MUST change the compiler settings to suppress this (which by default is an ERROR in current Xcode):

"SVGKit/Core/SVGUtils.m:164: error: initializer element is not constant"

..NB: variations on that cause over TWO HUNDRED build errors on a new empty iPad project which has merely had SVGKit added to it!

**Comment by adamgit** [comment]
So, yes - additional getting started instruction:
1. you MUST edit your Build Settings, and set "GCC_VERSION"  to be: "com.apple.compilers.llvm.clang.1_0"

**Comment by adamgit** [comment]
FINALLY ....
1. you MUST add "QuartzCore.framework" to your iOS project.

Please can someone update the README on the front page to include these 4 changes - it would have saved me half an hour of doing: Compile ... get build errors ... debug ...re-try.

**Comment by ralphleon** [comment]
Thanks for this comment.  The fact that this hasn't been addressed in 4 months is a good sign I shouldn't be using this library ;)

**Comment by adamgit** [comment]
Mattrajca disappeared - everyone's now using reklis's fork, which is much better maintained, and has many more features and major re-writes.

The instructions on the reklis fork are fixed, and simplified (it builds as a library now, not just as a project).

https://github.com/reklis/SVGKit/

**Comment by adamgit** [comment]
(CC'ing to reklis)

We use "SVGPad" as the main unit test / demo project (it imports the
library, which is now in project "SVGKit").

I admit I haven't tried "Note" in a long time. I'm getting:

[SVGDocument] SVGKit Parse error: Error Domain=1 Code=97 "Unsupported
version '1.1'
" UserInfo=0x4e03560 {lineNumber=1, NSLocalizedDescription=Unsupported
version '1.1'
}
2012-03-11 23:33:40.767 SVGPad[4946:207] [SVGDocument] MISSING OR
CORRUPT FILE, OR FILE USES FEATURES THAT SVGKit DOES NOT YET SUPPORT,
COULD NOT CREATE DOCUMENT: path = /Users/adam/Library/Application
Support/iPhone Simulator/4.3.2/Applications/9C58C48C-5279-423C-A7DD-34284199C77B/SVGPad.app/Note.svg,
error = Error Domain=1 Code=97 "Unsupported version '1.1'
" UserInfo=0x4e03560 {lineNumber=1, NSLocalizedDescription=Unsupported
version '1.1'
}

...which is a bit more detailed.

Until recently, we were silently ignoring most parse errors, and I
added an error handler. It would appear that

   Unsupported version '1.1'

isn't really an error (although the library reports it as an 'error'),
instead it's a warning.

I'll have a quick try at fixing that now

**Comment by ralphleon** [comment]
Cool! I actually got the same error with a different svg file, and wanted to make sure I wasn't messing anything else up. Also, I installed this exactly like the original (no framework) so that might come into play too!

~Ralph G.

**Comment by adamgit** [comment]
I've committed a change to https://github.com/adamgit/SVGKit (master
branch) that checks each parser-error, and if it's an error of type
"warning", it logs it but does NOT report "parse failed".

**Comment by adamgit** [comment]
ralphleon - please can you try the copy from my fork, and check it's working for you?

I've checked it with Note.SVG on the SVGPad project, and it now seems to be working fine. HOWEVER since it seems to be complaining that it doesn't support XML 1.1, I'm surprised it works at all, ever (and it does work - I'm using it unmodified on multiple projects)

**Comment by adamgit** [comment]
Also, re usage: for iPhone/iPad, I recommend you run the SVGKit project, and build the SVGKitLibrary, which outputs a single .a library file + all the headers, which you can then drag/drop/embed in your project. No further setup needed, I think (although check the README).

For Mac ... I haven't had time to check / fix / deploy it in a real Mac app yet, so ... dunno how well it works right now

**Comment by adamgit** [comment]
Fixed ages ago, with the move to SVGKit/SVGKit
