### ISSUE TITLE
Resize SVG containing polylines

### ISSUE THREAD

**Issue by tkreuder** [SVGKit/SVGKit#132]
Is there a way to resize svg's containing polylines

```
<polyline points="22.8125,199.15625 22.84375,..." style="fill:none;stroke:black;"/>

```

the following just worked with the provided sample svg's, but not with a svg containing polylines:

```
[[[SVGKImage alloc ]initWithContentsOfURL:url]setSize:CGSizeMake(imgWidth, imgHeight)];
```

**Comment by adamgit** [comment]
Polylines should resize same as everything else. I have no idea what you
mean when you say it didn't work. If you can create an SVG file that
demonstrates the problem within the Demo app, it's much more likely someone
will fix it - but unfortunately the resizing in the app is dynamic, and I
don't think it uses the setSize code :(.

**Comment by adamgit** [comment]
Please read: http://t-machine.org/index.php/2013/12/22/reporting-issues-in-open-source-software/
