### ISSUE TITLE
Editing Imported SVGImages

### ISSUE THREAD

**Issue by jfclifton** [SVGKit/SVGKit#133]
Hi, thanks for sharing this library. I read your blog and I have successfully imported and displayed an image and also exported the XML to save a SVG file.

My question is: Am I able to edit these images somehow? When importing, does it convert the XML into Core Graphics data? 

For example I want to import an SVG, maybe change some colors or add some extra lines, then export out as XML again to be saved as SVG.

Thanks for any info. Forgive my lack of knowledge of how the library was built 100%

**Comment by adamgit** [comment]
If you edit the CALayer attributes, that will NOT AFFECT the file you save.

You need to edit the "DOM" (c.f. the SVG spec / any modern HTML javascript
tutorial). The DOM is stored in memory as ObjectiveC classes objects, and
it's fairly obvious how this maps to CALayers - but if your SVG is using
CSS internally (which is supported) then the edit changes might be
non-obvious.

**Comment by jfclifton** [comment]
So basically I need to somehow write to the DOM of the imported SVGKImage object with any kind of new changes to it?

**Comment by adamgit** [comment]
Exactly.

NB: in general, I don't see how you could _ever_ avoid this! Apple has no
concept of CSS styling (no concept of "cascaded" properties, no concept of
re-usable / shared "styles") - so, to create an Apple-renderable-image, we
have to collapse the CSS / SVG data down to flat, duplicated, unshared data.

...and when you edit that, there is no way of "simply" reflecting that back
into the original SVG.

Instead, as a "correct" solution, users should be editing the XML/DOM tree,
and the CSS styles on it - and you re-render the Apple graphics after
changing the DOM. That way, what the user sees / edits / creates is exactly
what is rendered _and_ what is saved.

(FYI to re-render the DOM after changing it, simply call
"SVGKImage.CALayerTree" and a new one will be auto-generated. You might
need to manually "invalidate" the cached tree - off the top of my head I
can't remember if it is able to detect changes to the DOMTree object)

**Comment by jfclifton** [comment]
Thanks for your help and quick responses, I am going to see what I can do :)
