### ISSUE TITLE
NSInputStream misuse - Load SVG from URL 

### ISSUE THREAD

**Issue by MirkoBrunner** [SVGKit/SVGKit#135]
I have changed the method SVGKSourceURL::sourceFromURL to this:
- (SVGKSource_)sourceFromURL:(NSURL_)u {
  NSData *data = [NSData dataWithContentsOfURL:u];
  NSInputStream *stream = [NSInputStream inputStreamWithData:data];
  [stream open];
  
  SVGKSourceURL\* s = [[[SVGKSourceURL alloc] initWithInputSteam:stream] autorelease];
  s.URL = u;
  
  return s;
  }

..and it work´s ;)

best regards...

**Comment by adamgit** [comment]
AFAICS, that would load the entire URL into RAM, and then process it. Whereas the method we use now should - according to Apple's docs - stream it and parse as it goes.

Do you have a side-by-side test case to show one working and the other not working? The code we have now _used to work_, and I don't think anyone changed it. I'd like to be sure this code is different before replacing.

Also: we can't merge a change unless you issue a Pull Request - github requires you to make the decision, sorry.

**Comment by adamgit** [comment]
It turns out that [stream open] has some subtle side-effects on current iOS to do with threading.

I've rewritten that code and it seems to work fine now (it calls open as late as possible now, instead of as early as possible)
