### ISSUE TITLE
The demo app crashes on the simulator and device.

### ISSUE THREAD

**Issue by nverinaud** [SVGKit/SVGKit#137]
Hi !

I'm evaluating your library and unfortunately the demo project crashes when I click on the image in the details view controller.
I'm testing the "stable" branch `1.1.0`.

I tested on the device and on the simulator.

Using Xcode 5.0.2, iOS SDK 7.0.

**Comment by adamgit** [comment]
1.1.0 predates iOS7, so ... yeah, I expect it doesn't work (Apple introduced plenty of stuff that requires small modifications of existing code).

Generally - Use 1.x for everything - the version numbers are a convenience for people who are using old versions of the library in shipped-apps, and need to stick with that version until they can afford to test their code with the latest and greatest version.

If you get the same problem with 1.x, re-open this.
