### ISSUE TITLE
Too much memory and then Crash

### ISSUE THREAD

**Issue by KateShi** [SVGKit/SVGKit#138]
When I use instrument of Xcode , I found SVGKit's memory increase quickly like a crazy and wait for several minutes, it crashed.

Could you optimise it?

Device:iPhone 4s
iOS Version:6.1

**Comment by adamgit** [comment]
Please read: http://t-machine.org/index.php/2013/12/22/reporting-issues-in-open-source-software/

If you have ideas for optimizations, I'd be interested to hear them. I've added a few myself.
