### ISSUE TITLE
Can't be used with c++ code in objective C project???

### ISSUE THREAD

**Issue by gerchicov** [SVGKit/SVGKit#139]
try to rename *.m file to *.mm and import svgkit. It writes that something wrong with "Class" type

**Comment by adamgit** [comment]
http://t-machine.org/index.php/2013/12/22/reporting-issues-in-open-source-software/

**Comment by gerchicov** [comment]
does it work in your code? I don't know how to say a little bit more about this issue.

**Comment by adamgit** [comment]
Xcode has support for this cool feature called copy/paste. You select an
error, you copy it, you paste it.

It would have taken less effort to do that than give the useless info you
gave :(
