### ISSUE TITLE
Podspec for 1.x

### ISSUE THREAD

**Issue by pyro2927** [SVGKit/SVGKit#141]
Only v1.0 is available on Cocoapods, and changing the current Podspec to use `:branch => "1.x"` doesn't compile.

**Comment by adamgit** [comment]
This is a "feature" / "design mistake" in CocoaPods, depends how you look at it :) - they can ONLY link against static commits (they can't link against branches :( ).

I completely understand that decision, but it's a very narrow view of software development, and fails in a lot of cases.

Net effect: the only thing you can link against is a "tagged" commit. You can find them on the home page, at the very top - GitHub (slightly unhelpfully) renames them "Releases" (they are not really releases, they are git-tags; a git tag could mean a lot of things other than "a release").

Unfortunately, we have to keep choosing a particular commit to tag for CP, and the project isn't stable enough for that to be easy. Do we tag this one, or that one, or ... wait another 24 hours for another one? Or wait a week? Or .. ?

(I'm open to ideas on this - I don't expect there's a perfect solution, but I'm happy to try things if they seem better than what we've been doing so far)

**Comment by pyro2927** [comment]
You could self-host a `podspec` inside of the repo (like [this](https://github.com/pyro2927/SVGKit/blob/1.x/SVGKit.podspec)), and then users could add `1.x` in their `Podfile` with:

```
pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git'
```

Side note: don't merge in any of my commits, they were all pretty destructive.

**Comment by adamgit** [comment]
Could you set this up and send a pull request? I dont use CP so cant test
it :(

**Comment by pyro2927** [comment]
Done!  It's #142, and I threw up an example repo that shows how it works.
