### ISSUE TITLE
[SVGKImage imageWithData:] implementation

### ISSUE THREAD

**Issue by mohpor** [SVGKit/SVGKit#145]
Hi,
I was just wondering why the very convenient (and sometime inevitable to use) method: "imageWithData:" in SVGKImage is not implemented yet?!
It seems that you could create an string from data and then use SVGKSourceString and return the result of "imageWithSource"!
I've done it already and it work perfectly!

**Comment by adamgit** [comment]
Submit a pull request?

**Comment by mohpor** [comment]
Im not sure adam, it might need further investigation, mainly because i have used UTF8 to decode the data to string and as far as SVG goes it must be ok, but you might need to let the final user decide on the encoding and that'll break the one to one mapping of the UIImage to SVGKImage.

**Comment by adamgit** [comment]
This is probably why no-one's done it yet. Correct solution is - I think -
to read the first N bytes of the NSData, look for the XML "UTF-whatever"
command, use that to re-parse the thing as an apporpriate string.

NB: if you pass the data to the XML parser, it will be doing this
automatically (the XML spec requires it!). Maybe you just need to find a
way to convert the NSData into a Stream, so that libXML is able to read it.

**Comment by mohpor** [comment]
That sounds like the right way to do it (finding the correct encoding from SVG document)! but it might hurt the performance even further!
Trying to convert NSData to Stream might be a better solution,

**Comment by adamgit** [comment]
From memory, XML is designed so that "detecting the encoding" can be done
very rapidly by copying the first N bytes, and only converting/reading
those ones.

So use the NSData method to read N bytes, and specify whatever the spec
says N has to be.

...or streamify it :)

**Comment by mohpor** [comment]
I came across SVGKit looking for a solution to display Vector tiles in route-me iOS SDK for map tiles, but it proved to be too slow (not just SVG rendering, because SVGKit is amazingly fast, I've tried ImageMagick too and SVGKit was almost 10 times faster! but SVG tiles were 3 times the size of PNG tiles), now I just know there is this amazing SDK for working with SVGs and I will use it in other projects. I'll be more than happy to look into methods that aren't implemented yet. I wish there was a source that I could use as a checklist to try and implement them every time I had idle hands.
By the way, I have finished doing what I was looking for: having vector tiles as map source in route-me, MapBox iOS SDK, using SVGKit, it isn't great but it is working, something the folks at MapBox can'r do yet!

**Comment by adamgit** [comment]
Perhaps add something here: https://github.com/SVGKit/SVGKit/issues/140

**Comment by adamgit** [comment]
Did you get this working in the end?

**Comment by adamgit** [comment]
No response, closing.
