### ISSUE TITLE
SVG Created only once

### ISSUE THREAD

**Issue by xavicolomer** [SVGKit/SVGKit#146]
Hi There,

I have this code:

SVGKImage\* newImage = [SVGKImage imageNamed:path];
            CGRect      startFrame = CGRectMake(0.0, 0.0, newImage.size.width, newImage.size.height);
            self.frame = startFrame;
            [self addSublayer:newImage.CALayerTree];

The application has to create several icons and this will keep moving around the frame, but I can only see one in the screen. I am not able to see if there's only one or multiple at the same place.

Any suggestion?

**Comment by adamgit** [comment]
Well, yes, that code would only show one.

Most people who get CALayer add
/ Frame problems find they didnt know CALayer as well as they needed - its
a tricky class, many of the bits are IMHO named badly or even wrongly. I
suggest building up from basic CALayer objects and checking your build at
each step.

**Comment by xavicolomer** [comment]
Thanks for your answer

Please let me explain it a little better.

I create several CALayers inside View. Each of these CALayers contains the code above in the init function, and then I animate its position every frame. So the SVG code is inside the init of each CALayer, that's why I think it's weird that I only see one.

**Comment by adamgit** [comment]
Most people don't know how to add CALAyers to a UIView. It doesn't do what
they think it does. Because you assume it does one thing, but Apple didn't
code CALayer that way.

Do what I said: prove to yourself that you know CALayer first.
