### ISSUE TITLE
Resizing SVGs

### ISSUE THREAD

**Issue by jverdi** [SVGKit/SVGKit#15]
Is there a way to resize the SVG that is displayed via SVGKit?

I've tried displaying on iOS through SVGView/SVGDocumentView, but they don't seem to respond to frame/bounds changes.

I'm guessing this is because it is added directly as a CALayer and the SVGView doesn't resize its sublayers?

Please let me know if you can provide any insight.

**Comment by ghost** [comment]
same issue, here.
I want to resize the svg view's layer. Do anyone know in which class they've added the layers?

**Comment by ErwannRobin** [comment]
I would love to be able to resize svg as well. 
I mean, not only via the zoom factor which is not a proper way to do it IMHO. 
adamgit and  reklis seems the new true mainteneurs but the  reklis fork doesn't allow to submit comment. I hope that they read this thread here sometimes.

**Comment by reklis** [comment]
My fork is UIScrollView friendly, you can pinch and zoom in the iPad demo project.  If you need to scale views manually, you can do so two ways.  
1. Scale the UIView using the .transform property of the view
2. Scale the root CALayer using the .layer.transform property of the view

Scaling a view is a 2d transform, scaling a layer is a 3d transform.

**Comment by ErwannRobin** [comment]
the problem in this case is that the smooth lines appears pixelized if zoomed in too much. 
and if I create big size versions of my SVG to match the biggest size of what my users can zoom, there are 2 issues : 
- Memory overload 
- the line width is too thin 
  I am looking for a way to scale the svg graphics whitout changing the line width

**Comment by reklis** [comment]
If you are resizing the root layer and you are still seeing this my best guess is what's going on is you are hitting the CALayer cache.  The layer tree is cached for performance, but it's invalid once you've transformed.  Maybe manually invalidate the layer cache?

**Comment by ErwannRobin** [comment]
I don't get it : 
i tried to put an SVGView inside an UIScrollview like in your SVGPad sample, I tried to scale the view, to scale the layer, but it doesn't work. 
my code : 

```
SVGDocument* svgDocument = [SVGDocument documentNamed:@"CurvedDiamond"];
SVGDocumentView* docView = [SVGDocumentView documentViewWithDocument:svgDocument];
[docView.rootLayer setFrame:svgTestView.bounds];
[svgTestView.layer addSublayer:docView.rootLayer];
svgTestView.transform = CGAffineTransformMakeScale(5, 5);
```

is it better to user SVGView or SVGDocumentView ? 

BTW, if we zoom too much in SVGPad, the edges are also blurred : 
see : http://dl.dropbox.com/u/16455594/SVGPad-diamond.png or http://dl.dropbox.com/u/16455594/SVGPad-Note.png

**Comment by reklis** [comment]
Try adjusting the transform of the layer instead of the view, I haven't tried it, but it makes sense that it would work

**Comment by ghost** [comment]
I dont think it'll work because in SVGElement.m if u change self.transformRelative = CGAffineTransformIdentity; to a custom transformation the layers will be sorted randomly, I dont know what that is but the svg will be merged. And even if we think to give transformation to any layer, It'll be zoomed and in reality it'll be blurry.

what we need it to transform the paths with the relative scale before we create layers from that or say port those paths into layer using quartz.. 

I would like to mention about transformAbsolute property as well in the same class. I dont know why is there but it gives the same transformation as transformRelative.

**Comment by reklis** [comment]
scaling the paths before generating the layers really is the only "real" solution

**Comment by ghost** [comment]
but how to do that?

**Comment by reklis** [comment]
The short answer is you can't. SVGKit in it current state does not support mutable paths.  Either resize the original, or have multiple samples. Adamgit, Stich and I have been talkin a lot about transforms. Watch adamgit's fork for updates.

**Comment by adamgit** [comment]
You _can_ scale the layers and get them to re-render, already - although I'm not 100% sure how this is achieved, I know it works because if you use Apple's CATiledLayer with the layers from SVGDocumentView, you get the sharp zooming, infinitely.

I _believe_ Apple does something in changing the layer.transform - but there's more to it than that, there's some variables on CALayer that Apple hasn't documented very clearly.

LONG TERM ... I'm close to publishing something that allows SVG-triggered resizes, by supporting the SVG ViewBox commands. However, in the short term, you can investigate CATiledLayer, and find out what it's doing...

**Comment by jverdi** [comment]
To follow up, I was able to use CA transforms to scale the layers, but in my case, that presented its own headaches. I needed the ability to write the SVG out as an image file, and hit limitations of CALayer's renderInContext...

https://developer.apple.com/library/ios/documentation/GraphicsImaging/Reference/CALayer_class/Introduction/Introduction.html#//apple_ref/occ/instm/CALayer/renderInContext:

"Important - The Mac OS X v10.5 implementation of this method does not support the entire Core Animation composition model. QCCompositionLayer, CAOpenGLLayer, and QTMovieLayer layers are not rendered. Additionally, layers that use 3D transforms are not rendered, nor are layers that specify backgroundFilters, filters, compositingFilter, or a mask values. Future versions of Mac OS X may add support for rendering these layers and properties."

I was able to work around it, but I believe it was through rendering the SVG first, and then perform bitmap scaling.

**Comment by reklis** [comment]
@adamgit you forgot to include this link http://www.mlsite.net/blog/?p=1884

**Comment by lpalpac** [comment]
Can anyone answer to this?
http://stackoverflow.com/q/10432936/1357593
Thanks

**Comment by adamgit** [comment]
Update: I now have this working perfectly in my experimental fork.

It requires a small override to the current code (you have to change a property from "readonly" to "readwrite") but a couple of people have tried it and it works.

https://github.com/adamgit/SVGKit/tree/transforms

Steps:
1. edit SVGKImage.h and set the "viewBox" property to "readwrite"
2. to resize something, take the actual size (SVGKImage.size) and divide it by the size you want it to be (FINAL SIZE)
3. then multiply that by SVGKImage.size (yes, you're inverting this!)
4. finally, set SVGKImage.DOMTree.viewBox to this new size
5. call [SVGKImage newLayerTree] to regenerate at full resolution at the new size

e.g. if SVG outputs as 100x100, and you want it 300x300:
1. (above)
2. ratio = (100/300),(100/300) = (1/3,1/3)
3. SVG size \* ratio = (100 \* 1/3),(100 \* 1/3) = (33,33)
4. viewBox = (33,33)
5. (as above)

**Comment by mccpower** [comment]
Thanks for share how to resize, I'm applying but I can't see any change that after have changed viewboxframe property in SVGSVGElement.h (I can't find it in SVGKImage.h):

@property (nonatomic, readwrite) CGRect viewBoxFrame; // FIXME: this has NON TRIVIAL relationship to the viewport property 

and commented in SVGSVGElement.m:

@interface SVGSVGElement()
//@property (nonatomic, readwrite) CGRect viewBoxFrame;
@end

CODE to change the size and refresh
     NSLog(@"Size=%f, %f",im.size.width,im.size.height);
    im.DOMTree.viewBoxFrame=CGRectMake(0, 0, im.size.width\* (im.size.width/5000), im.size.height \* (im.size.height/5000));
    [im newCALayerTree];  
        NSLog(@"Size=%f, %f",im.size.width,im.size.height);

**Comment by reklis** [comment]
I'm not as familiar with adam's code as he is obviously, but I would suspect that simply _calling_ newCALayerTree is not enough.  You'll need to use the return value.  [self.view.layer addSublayer:[im newCALayerTree]]

**Comment by mccpower** [comment]
Thanks reklis I am using also a contentview and I was just removing and adding again IM, but I see that if I work with the layer the zoom is applied correctly!

**Comment by adamgit** [comment]
In the 2013base branch, this is now all handled automatically.

You simply change the value of the "size" property on SVGKImage (after parsing, obviously).

It automatically deletes the .CALayerTree reference, so you dont need to worry about that any more, just access .CALayerTree after you've changed the .size
