### ISSUE TITLE
In ScrollView Scale , Hou to make the text tag "font-size" change?

### ISSUE THREAD

**Issue by zccokie** [SVGKit/SVGKit#155]
![quest1](https://f.cloud.github.com/assets/6868231/2341344/00f41be2-a4d8-11e3-875f-657d36f13db7.png)

I add the SVGImageView to the ScrollView ,  When I change the scrollview scale, I want to change the text tag "font-size" , and make it display normal. but it not work.
Help me,thanks !
this is my code:  

-(void)scrollViewDidEndZooming:(UIScrollView *)scrollView withView:(UIView *)view atScale:(float)finalScale
{

```
float font_size =  12/scrollView.zoomScale;

NSLog(@"=====%f",font_size);
SVGKImage *document = imgView.image;
SVGDocument *svgDoc = document.DOMDocument;
NodeList *textList = [svgDoc getElementsByTagName:@"text"];
for (SVGElement *element in textList) {
    [element setAttributeNS:@"http://www.w3.org/2000/svg" qualifiedName:@"font-size" value:[NSString stringWithFormat:@"%f",font_size]];
}

view.transform = CGAffineTransformIdentity; // this alters view.frame! But *not* view.bounds
view.bounds = CGRectApplyAffineTransform( view.bounds, CGAffineTransformMakeScale(finalScale, finalScale));
[view setNeedsDisplay];

_scrollerView.minimumZoomScale /= finalScale;
_scrollerView.maximumZoomScale /= finalScale;
```

}

**Comment by adamgit** [comment]
You never add your SVGImage to the view in the code above.

I suggest you use SVGKLayeredImageView, and find the CALayer (I think CATextLayer?) instances, and set scale etc on the text-layers directly.

**Comment by zccokie** [comment]
I had used CATextLayer and SVGKLayeredImageView,but text is fuzzy yet.  in above code, this view is I added SVGKLayeredImageView. I don't know when the Scorllview scaled,  how to make the the CATextLayer display normarl. 
Can you help me or give me some example code?

**Comment by zccokie** [comment]
thanks , i  use CATextLayer and SVGKLayeredImageView Solved this question.
