### ISSUE TITLE
Start and end gradient not parsed correctly

### ISSUE THREAD

**Issue by lutfime** [SVGKit/SVGKit#157]
When use SVG with start and end point is percentage, SVGGradientElement does not convert the points to correct value. 

This is because when  [self normalizeGradientCoordinate:y:rectToFill] called, [SVGLength svgLengthFromNSString:[NSString stringWithFormat:@"%f",startPoint.x]] does not consider the '%' from "x1" attribute.

This is the culprit
SVGLength\* svgX1 = [SVGLength svgLengthFromNSString:[self getAttributeInheritedIfNil:@"x1"]];
        SVGLength\* svgY1 = [SVGLength svgLengthFromNSString:[self getAttributeInheritedIfNil:@"y1"]];
        CGPoint startPoint = CGPointMake(svgX1.value, svgY1.value);
        startPoint = CGPointApplyAffineTransform(startPoint, self.transform);
        startPoint = [self normalizeGradientCoordinate:[SVGLength svgLengthFromNSString:[NSString stringWithFormat:@"%f",startPoint.x]] y:[SVGLength svgLengthFromNSString:[NSString stringWithFormat:@"%f",startPoint.y]] rectToFill:rectForRelativeUnits];

**Comment by adamgit** [comment]
Yes, you'll need to implement percentages inside SVGLength. Please go ahead, and submit a pull request when done. There are full details in the W3C spec, I believe.

**Comment by lutfime** [comment]
Maybe I don't understand the real problem, but isn't percentage already implemented in SVGLength? Below is my workaround, I just add '%' after for string parameter in normalizeGradientCoordinate: so it will normalize the percentage value to 0-1. Although I don't know what the best way but this is sufficient for my need. 

NSString *attr1 = [self getAttributeInheritedIfNil:@"x1"];
NSString *attr2 = [self getAttributeInheritedIfNil:@"y1"];
NSString *lastChar = [attr1 substringWithRange:NSMakeRange(attr1.length-1, 1)];
if (![lastChar isEqualToString:@"%"]) {
     lastChar = @"";
}

SVGLength\* svgX1 = [SVGLength svgLengthFromNSString:attr1];
SVGLength\* svgY1 = [SVGLength svgLengthFromNSString:attr2];
CGPoint startPoint = CGPointMake(svgX1.value, svgY1.value);
startPoint = CGPointApplyAffineTransform(startPoint, self.transform);
startPoint = [self normalizeGradientCoordinate:[SVGLength svgLengthFromNSString:[NSString stringWithFormat:@"%f%@",startPoint.x, lastChar]] y:[SVGLength svgLengthFromNSString:[NSString stringWithFormat:@"%f%@",startPoint.y, lastChar]] rectToFill:rectForRelativeUnits];

**Comment by adamgit** [comment]
From the source:

"NSAssert( FALSE, @"Asked to convert a Relative Length value to a different type (NO conversions for this type are currently supported) (%i)", unitType );"

There is no code for converting a %age to a pixel value. Handling all the %age cases requires adding some system for an SVGLength to find the length of the parent element, and the grandparent element, etc.

I haven't read the spec for gradients, but if they are defined as interpretting %age as "a value from 0 to 1, ignoring the parent", then your approach would work in that limited case.

**Comment by lutfime** [comment]
Yes thats right. Below is an example SVG from Sketch which uses %. From my testing it does not call NSAssert, but the final value given by SVGKit for gradient points are clearly wrong (start = {-4.7, -3.9}, end = {-101, -101}).

I use code I posted before and use extra method in my app if gradient in SVG use % so that the gradient will be converted correctly. Well at least it works.

Just my thought its pretty strange because from spec if % used it is calculated from maskPath bound but it will use parent bound if number is used.

Example SVG from Sketch:
http://pastebin.com/1XfLfgXL

**Comment by trilogysci** [comment]
from the spec the units including % vary depending on the gradientUnits setting.
userSpaceOnUse or objectBoundingBox

**Comment by adamgit** [comment]
c.f. #160 and #165 .

@trilogysci - the person who originally implemented gradients doesn't seem to be around any more. Can you have a go at fixing these issues?

I suspect the change is mostly: "upgrade SVGLength so it can understand / convert %ages for gradients". I implemented the minimum bits of SVGLength we needed, following the spec, so that we could convert things into Apple 'points' for output/display. I guess you'll need to add a method something like:

"SVGLength: -(double) convertToPixelsInContext:(SVGElement*) parentElement"

-- i.e. if you have an SVGLength that's possibly in %age, you need to give it a parentElement for it to calculate the pixels value. SVGLength has no context (by design / according to spec, I think) so it cannot do this calculation without some help.

**Comment by lutfime** [comment]
What I know is, when objectBoundingBox is used as in my case, it need to convert the coordinate to 'userSpaceOnUse' or root frame first to get correct gradient location.

If it is layer or view, method convertPoint:toView: can simply be used but in this case we don't know the relationship between objectBoundingBox frame and root frame.

**Comment by dreampiggy** [comment]
Fix via #584
