### ISSUE TITLE
linearGradient gradientUnits objectBoundingBox not supported

### ISSUE THREAD

**Issue by trilogysci** [SVGKit/SVGKit#160]
when using the following gradient
      <linearGradient id="MyGradient" x1="0%" y1="0%" x2="100%" y2="100%" gradientUnits="objectBoundingBox">
        <stop offset="5%" stop-color="#F00" />
        <stop offset="95%" stop-color="#0F0" />
      </linearGradient>
The object is shown in a single color (green) and not transitioning from red to green.

**Comment by adamgit** [comment]
Perhaps the "percent" symbol is ignored by our parser?

If you change it to 0 / 1.0 instead of 0% / 100% etc .. does it work?

**Comment by dreampiggy** [comment]
Fix via #584
