### ISSUE TITLE
Clicking on any rendered SVG gives EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by RepublicOfAppsLLC** [SVGKit/SVGKit#164]
Hi,

This is an awesome repo, thanks for releasing this for us to use!

I just downloaded the v1.x branch and I'm trying to run in Xcode 5.1.1 on OS X 10.9.2.  I can click on cells in the initial tableview.  I can pan around the maps.  But as soon as I click on one of the regions and it draws the bounding box outline, the app crashes with EXC_BAD_ACCESS.  This indicates that there's a memory management bug somewhere in the code.  I haven't altered the code in any way.

This happens both when I run the app on on a device or in the simulator.  This is the Demo-iOS project.

Any ideas?  I'd love to use this but I'm not sure why it's crashing everytime I click on something when an SVG is being rendered.

These crashes happen on multiple different devices and on multiple Macs running Xcode, so it's not isolated and the crash happens 100% of the time when I tap on an SVG that's been rendered.

Any ideas?

Thanks again for this awesome work.

**Comment by adamgit** [comment]
Thats very strange.

I guess: either a recent commit had thus side effect and no-one noticed, or
xcode 5.1.1 is compiling in a different way.

Xcode now forces 64bit compatibility, so I would be suspicious of a 64bit
problem somewhere.

There should be zero (or very very few) build warnings, and if you do
static analysis (on both the library and the demo), you should get zero
hits (or maybe one hit for a false positive?).

...if not, probably a recent commit.

**Comment by aaarbk** [comment]
I'm having the same problem. The following warning is being generated by libtool, don't know if it has any connection to the problem:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: -dynamic not specified the following flags are invalid: -ObjC 
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/usr/lib/libxml2.dylib is a dynamic library, not added to the static library
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/usr/lib/libxml2.dylib is a dynamic library, not added to the static library

**Comment by adamgit** [comment]
What's the actual crash / where does it occur?

EXC_BAD_ACCESS doesn't really mean anything, it's a holding-message. It
could even be an assertion rather than a bug.

**Comment by aaarbk** [comment]
The location of the crash is not apparent from the stack trace - the crash was due to a deallocated object being released, which I got by enabling zombie objects: "`-[CAShapeLayerWithHitTest release]: message sent to deallocated instance 0xnnnnnnn`"

Stumbling along, I commented out:

```
[absolutePositionedCloneLayer release] // DetailViewController:214
```

and this appears to have fixed the problem - however I have not counted object allocations/deallocations to make sure that this is in fact the issue. (But seems like this was it.)

BTW, is there any special reason you haven't moved the project to ARC?

**Comment by adamgit** [comment]
IIRC the only reason for non-ARC was that the project predated ARC (ARC
libs can go in non-ARC projects anyway).

c.f. #127 it seems no-one minds if we upgrade to all the modern Objc-2.0
stuff (and ARC) in the next significant release.

I was hoping for a few major commits before then - e.g. replacement for the
crappy CATextLayer text - but everyone seems too busy this past 12 months
to get the commits in.

**Comment by adamgit** [comment]
"[absolutePositionedCloneLayer release]"

There were recent commits that fixed the memory counts on some "absolute" methods, so ... this is very possibly the cause.

**Comment by adamgit** [comment]
xlc just did a pull request that added a missing retain to an internal clone-layer method.

Tested with Xcode 4.x - everything is working fine.

Can you guys please re-test latest 1.x branch and see if this crash is fixed?

Thanks

**Comment by aaarbk** [comment]
The crash has been fixed for me with the latest commit.
