### ISSUE TITLE
Output has a green tint to it making images unusable

### ISSUE THREAD

**Issue by PgoTracker** [SVGKit/SVGKit#17]
The sample images when run on mac display with green tinting rather than the expected colour. Any word on a fix?

**Comment by adamgit** [comment]
The mattrajca main version DOES NOT WORK at the moment. IT WILL NOT RENDER SVG.

Please use the reklis fork until further notice (we are trying to repair the mattrajca fork, but this is non-trivial - it's almost a year out of date)

**Comment by adamgit** [comment]
The mattrajca main version DOES NOT WORK at the moment. IT WILL NOT RENDER SVG.

Please use the reklis fork until further notice (we are trying to repair the mattrajca fork, but this is non-trivial - it's almost a year out of date)

**Comment by adamgit** [comment]
The mattrajca main version DOES NOT WORK at the moment. IT WILL NOT RENDER SVG.

Please use the reklis fork until further notice (we are trying to repair the mattrajca fork, but this is non-trivial - it's almost a year out of date)

**Comment by adamgit** [comment]
The mattrajca main version DOES NOT WORK at the moment. IT WILL NOT RENDER SVG.

Please use the reklis fork until further notice (we are trying to repair the mattrajca fork, but this is non-trivial - it's almost a year out of date)

**Comment by adamgit** [comment]
The mattrajca main version DOES NOT WORK at the moment. IT WILL NOT RENDER SVG.

Please use the reklis fork until further notice (we are trying to repair the mattrajca fork, but this is non-trivial - it's almost a year out of date)

**Comment by adamgit** [comment]
The mattrajca main version DOES NOT WORK at the moment. IT WILL NOT RENDER SVG.

Please use the reklis fork until further notice (we are trying to repair the mattrajca fork, but this is non-trivial - it's almost a year out of date)

**Comment by adamgit** [comment]
The mattrajca main version DOES NOT WORK at the moment. IT WILL NOT RENDER SVG.

Please use the reklis fork until further notice (we are trying to repair the mattrajca fork, but this is non-trivial - it's almost a year out of date)

**Comment by adamgit** [comment]
The mattrajca main version DOES NOT WORK at the moment. IT WILL NOT RENDER SVG.

Please use the reklis fork until further notice (we are trying to repair the mattrajca fork, but this is non-trivial - it's almost a year out of date)

**Comment by adamgit** [comment]
The mattrajca main version DOES NOT WORK at the moment. IT WILL NOT RENDER SVG.

Please use the reklis fork until further notice (we are trying to repair the mattrajca fork, but this is non-trivial - it's almost a year out of date)

**Comment by adamgit** [comment]
The mattrajca main version DOES NOT WORK at the moment. IT WILL NOT RENDER SVG.

Please use the reklis fork until further notice (we are trying to repair the mattrajca fork, but this is non-trivial - it's almost a year out of date)

**Comment by adamgit** [comment]
The mattrajca main version DOES NOT WORK at the moment. IT WILL NOT RENDER SVG.

Please use the reklis fork until further notice (we are trying to repair the mattrajca fork, but this is non-trivial - it's almost a year out of date)

**Comment by adamgit** [comment]
The mattrajca main version DOES NOT WORK at the moment. IT WILL NOT RENDER SVG.

Please use the reklis fork until further notice (we are trying to repair the mattrajca fork, but this is non-trivial - it's almost a year out of date)

**Comment by adamgit** [comment]
NB the "millions of comments" is a bug in GitHub. Sorry.

**Comment by PgoTracker** [comment]
I'm using the reklis fork but there's no issue page for that
