### ISSUE TITLE
Have some tests

### ISSUE THREAD

**Issue by xlc** [SVGKit/SVGKit#171]
Need some tests to make sure everything are working. If unit tests are too much at least have some integration test to ensure some commonly used functionality are working. i.e. all SVG files in demo project should be rendered properly.

**Comment by adamgit** [comment]
Yes!

A couple of years ago, someone was working on unit tests, by taking screnshots programmatically (using Apple API's) and comparing them against pre-saved screenshots.

But they disappeared before finishing / committing. It's been a long time, I don't believe they're coming back, so we should redo this.

**Comment by adamgit** [comment]
Closing since there's nothing constructive here.
