### ISSUE TITLE
Not rendering dashed lines

### ISSUE THREAD

**Issue by llaughlin** [SVGKit/SVGKit#172]
Dashed strokes, specifically "stroke-dashedarray" aren't rendered correctly. 

For an example of this, look here: https://imgur.com/8ICZZcj,iS9GPRr. The first image is what appears in XCode, the second is what appears in the demo app.

**Comment by LeChatNoir69** [comment]
Hi there,

Idem for me. Dashed paths aren't rendered. Is it the SVG parser not ready for that ?
Any idea ?

Thxs,
Guillaume

**Comment by adamgit** [comment]
I believe this was added last year
