### ISSUE TITLE
EXC_BAD_ACCESS on readWhiteSpace

### ISSUE THREAD

**Issue by tspecht** [SVGKit/SVGKit#173]
I'm currently experiencing a rather random error that only occurs sometime. Any tips on how to resolve this?

Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x37ff5626 objc_msgSend + 5
1  Foundation                     0x2e107ce5 -[NSScanner scanCharactersFromSet:intoString:] + 204
2  MyApp               0x001fbe2f +[SVGKPointsAndPathsParser readMoveto:path:relativeTo:isRelative:](SVGKPointsAndPathsParser.m:269)
3  MyApp               0x001fbd8d +[SVGKPointsAndPathsParser readMovetoDrawto:path:relativeTo:isRelative:](SVGKPointsAndPathsParser.m:251)
4  MyApp               0x001fbcc7 +[SVGKPointsAndPathsParser readMovetoDrawtoCommandGroup:path:relativeTo:isRelative:](SVGKPointsAndPathsParser.m:235)
5  MyApp               0x001fbc6b +[SVGKPointsAndPathsParser readMovetoDrawtoCommandGroups:path:relativeTo:isRelative:](SVGKPointsAndPathsParser.m:225)
6  MyApp               0x001fdfa7 -[SVGPathElement parseData:](SVGPathElement.m:74)
7  MyApp               0x001fdabf -[SVGPathElement postProcessAttributesAddingErrorsTo:](SVGPathElement.m:27)
8  MyApp               0x001fb6f1 -[SVGKParserSVG handleStartElement:document:namePrefix:namespaceURI:attributes:parseResult:parentNode:](SVGKParserSVG.m:95)
9  MyApp               0x001f9a11 -[SVGKParser handleStartElement:namePrefix:namespaceURI:attributeObjects:](SVGKParser.m:308)
10 MyApp               0x001fa4e7 startElementSAX (SVGKParser.m:463)
11 libxml2.2.dylib                0x383a247b xmlParseStartTag2 + 2886
12 libxml2.2.dylib                0x383a0573 xmlParseTryOrFinish + 3062
13 libxml2.2.dylib                0x3839f319 xmlParseChunk + 472
14 MyApp               0x001f95bb -[SVGKParser parseSynchronously](SVGKParser.m:198)
15 MyApp               0x001f7033 -[SVGKImage initWithSource:](SVGKImage.m:199)
16 MyApp               0x001f6c9d +[SVGKImage imageWithContentsOfFile:](SVGKImage.m:142)
17 MyApp             0x001f6a43 +[SVGKImage imageNamed:](SVGKImage.m:118)
18 MyApp               0x00084cc5 -[MMCaptureViewController loadSlot:](MMCaptureViewController.m:296)
19 MyApp               0x000879a9 **49-[MMCaptureViewController advanceToNextRecording]_block_invoke489 (MMCaptureViewController.m:677)
20 UIKit                          0x2ffc9129 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 284
21 UIKit                          0x2ffc8d77 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 178
22 UIKit                          0x2ffc8c93 -[UIViewAnimationState animationDidStop:finished:] + 70
23 QuartzCore                     0x2fc15111 CA::Layer::run_animation_callbacks(void*) + 232
24 libdispatch.dylib              0x384d381f _dispatch_client_callout + 22
25 libdispatch.dylib              0x384da49f _dispatch_main_queue_callback_4CF$VARIANT$mp + 278
26 CoreFoundation                 0x2d73f8f1 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE** + 8
27 CoreFoundation                 0x2d73e1c5 __CFRunLoopRun + 1300
28 CoreFoundation                 0x2d6a8f4f CFRunLoopRunSpecific + 522
29 CoreFoundation                 0x2d6a8d33 CFRunLoopRunInMode + 106
30 GraphicsServices               0x32601663 GSEventRunModal + 138
31 UIKit                          0x2fff416d UIApplicationMain + 1136
32 MyApp               0x000343e3 main (main.m:16)

**Comment by adamgit** [comment]
There was an old commit where that line of code incorrectly dropped memory.
It was fixed a long time ago, but I'd check youre on latest 1.x branch

**Comment by adamgit** [comment]
Assuming this is from an old code version, closing.
