### ISSUE TITLE
Change CLANG_CXX_LIBRARY to 'libc++' in SVGKit.podspec ?

### ISSUE THREAD

**Issue by rhcad** [SVGKit/SVGKit#176]
The default `C++ Standard Library` in many apps is `libc++ (LLVM C++ standard library with C++ 11 support)`, but it's `libstdc++ (GNU C++ standard library)` in [SVGKit.podspec](https://github.com/SVGKit/SVGKit/blob/2.x/SVGKit.podspec).

So, there is a conflict between `libc++` and `libstdc++` after SVGKit used in app. I had to copy my [SVGKit.podspec modified](https://github.com/touchvg/TouchVG/blob/1.1.14/ios/SVGKit.podspec) to `~/.cocoapods/repos` to use SVGKit in my library project.

The CLANG_CXX_LANGUAGE_STANDARD in SVGKit.podspec can be changed to 'libc++'?

```
s.xcconfig = {
    'CLANG_CXX_LANGUAGE_STANDARD' => 'gnu++11',
    'CLANG_CXX_LIBRARY' => 'libstdc++',  # 'libc++' ?
    'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2'
  }
```

Best Regards!

**Comment by adamgit** [comment]
I don't use cocoapods, and I don't recommend them.

If the change works, and you can run the iOS demo app and all the files
open / display correctly, I imagine it's fine to change that. Go ahead and
submit a pull request.
