### ISSUE TITLE
Only v1.0 is available via pod install

### ISSUE THREAD

**Issue by j5136p1** [SVGKit/SVGKit#178]
if i use pod install i get only the v1.0. This version doesn't work with my Project. 
I can use https://github.com/SVGKit/SVGKit.git but not if i try to use it as dependency in a pod spec.

Are there any reasons why the newest version (not 2.x but at least 1.1.0) isn't added to pod spec repository?

Thanks Mirko

**Comment by adamgit** [comment]
We don't maintain the cocoapods project. If something on their site is
wrong, you're welcome to change it.

**Comment by j5136p1** [comment]
ok, then i will add the version to specs repository. Thanks

**Comment by j5136p1** [comment]
Hi, they have changed the handling for cocoa pod specs. Only owners can claim pods. i can do it for SVGKit but i must send a form (https://trunk.cocoapods.org/claims/new) to the cocaPods guys. And i'am not a owner. I would like to use SVGKit in my sdk but i need the v1.2 as pod because you can not use url in podspec file.  

 Can you help? Thanks

**Comment by adamgit** [comment]
If you have a problem with the way CocoaPods runs their system, this is the
wrong place to discuss it. We have no association with CocoaPods - if you
don't like their design, talk to them - we can't help you.

**Comment by maximveksler** [comment]
The problem is you can't specify a branch to pull from.

If you're Podfile looks as following:

```
pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '1.1.0'
```

You get the following error:

```
pod update
Update all pods
Analyzing dependencies
Pre-downloading: `SVGKit` from `https://github.com/SVGKit/SVGKit.git`, branch `1.1.0`
Downloaded and checked out branch: 1.1.0 from upstream /Users/idanbuberman/Library/Caches/CocoaPods/GitHub/8308a01fc1a5db5285df878f1b47aceacd4689a9
[!] No podspec found for `SVGKit` in /Users/idanbuberman/src/frienderers-ios/Pods/SVGKit/SVGKit.podspec
```

Any solution for this?

**Comment by j5136p1** [comment]
Hi,

1.2.0 is not a option for you? You can use the normal pod Syntax without :git to get this Version.
- Mirko

**Comment by adamgit** [comment]
I thought they'd changed that in latest CP? So that you explicitly can choose a git branch to pull from

(I thought we used it in a team I was working with recently)

**Comment by maximveksler** [comment]
Didn't work for us yesterday during the hackathon, ended up implementing something manual.

If you guys could reference a workable syntax for the Podfile to pull out the "stable" branch, doesn't really matter which one, just the one you call stable :) That would be awesome. We're tried both 

```
pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '1.1.0'
```

and 

```
pod 'SVGKit', '~> 1.2.0'
```

Both sadly failed to compile.

**Comment by j5136p1** [comment]
I'am using s.dependency 'SVGKit', '~> 1.2.0' in my podspec and it works
I just tried to use pod 'SVGKit', '~> 1.2.0' in my project and it also works

Maybe a hint from my side (I had have the same yesterday)

If you are using cocoalumberjack in your project without , '~> 1.0.0'.  They announced a beta version which doesn't work in my project. I've added , '~> 1.0.0' to the pod file.

I can only say that SVGKit 1.2.0 works for me

**Comment by adamgit** [comment]
NB: People have used those versions for many live apps, across iOS versions 
from 4.x to 7.x, xcode versions from 3.x (allegedly) to 5.x. There are bugs 
(I wouldnt use either version - as per the front page) but I feel pretty 
confident saying "they work."

We make SVGKit work great out of the box, for everyone, with almost zero 
setup. We know it works!

CP works fine for some people, but for years it has failed for others. 
Thats deeply frustrating: podfiles are evangelised as something "simple" 
but in reality are hugely complex, with plenty of bugs -- but we get blamed 
when they fail.

So. We can offer suggestions and guesses, but ultimately: we already 
maintain and support a fully working build + source of the library.

... If CP breaks it, that's a problem with CP, and you need to ask them 
what their scripts are doing to your build and why.

(It is easy to test. One click to download the full source of SVGKit, one 
click to run the demo project. Its all preconfigured to run immediately 
with no setup. Try it. If THAT doesnt work, this becomes a different matter!)

**Comment by adamgit** [comment]
Off the top of my head you need to upgrade your version of CP and reference 
the 2.x branch.

You probably need to upgrade ruby, and fix some ruby dependencies too. I 
had to last time I did this. If you don't code in ruby, that could be tricky.

Worked for me.

**Comment by j5136p1** [comment]
I've made a change in podspec file for 1.x of SVGKit. It was using the cocoalumberjack without a version tag. I've added , '~> 1.0'. If the request will be approved it should work

We must create a Tag V1.2.1 and add them to cocoa pods rep

Otherwise if the request is rejected we must change the SVGKit to handle cocoa lumberjack 2.0 changes.

**Comment by j5136p1** [comment]
One last thing. As a "Quick Hack" you can add pod 'CocoaLumberjack', '~> 1.0' as first call in your lokal pod file (also if you don't use it). Then it install the 1.9.x version and because it exists one the 2.0.x will not be installed as dependency of SVGKit.

**Comment by mdwem** [comment]
When using pod 'SVGKit', '~> 1.2.0' i get thid error
Undefined symbols for architecture armv7:
  "_DDLogCWarn", referenced from:
clang: error: linker command failed with exit code 1 (use -v to see invocation)
