### ISSUE TITLE
How to combine multiple SVG documents?

### ISSUE THREAD

**Issue by aykutersahin** [SVGKit/SVGKit#185]
What i need to do for combining multiple SVG Images in 1 SVGDocument? 
For Ex; these images;
1.
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"> 
svg width="400" height="110">
  rect width="300" height="100" />

&&&
2.
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"> 
svg height="140" width="500">
  ellipse cx="200" cy="80" rx="100" ry="50" />

Updated: Github crop some of the svg code, sorry for missing chars in code.

**Comment by adamgit** [comment]
The demo project contains an SVG file with many sub-SVGs (lots of yellow smiley faces). That's one way.

Another way is to use "document" tags, but I don't think we support that yet. I tried to get it working - it's probably 99% working - but we had no examples.

If the sub-SVGs above isn't good enoguh, please read the SVG Spec (online) and try making a document with multiple SVGs. If you make it public domain, we can include it in the Demo projects and people can test / improve the support until it works.

**Comment by adamgit** [comment]
I've just done a commit that allows you to embed SVG's directly into each other using the "image" tag.

(previously it only supported PNG, JPG, etc).

At this point, I think all bases are covered - you can copy/paste the tags from two files together, you can embed a new "SVG" sub-tag, or you can embed an "image" tag that points to an external file.
