### ISSUE TITLE
Releasing memory under ARC

### ISSUE THREAD

**Issue by paulgee31** [SVGKit/SVGKit#187]
I have a project using ARC, which has uses a SVGFastImageView and repeatedly loads SVG files using [SVGKImage imageNamed:]  and assigns them to the SVGFastImageView using the image  property. 

Before assigning the new image to the property, I'm setting the old image to nil and the SVGFastImageView image property to nil but the memory isn't released.

Am I doing something wrong or is there a way to ensure the memory is released.

**Comment by adamgit** [comment]
I would guess "bug triggered by ARC trying to access non-ARC" (ARC is not perfect).

However, rather than debug it, we want to upgrade SVGkit to use ARC throughout - which often makes ARC bugs disappear (this is the cleaner solution - we want to switch to ARC anyway!).

So ... our main branch ("2.x") needs upgrading to ARC. Either using the auto-upgrade, or by reviewing one of the unofficial ARC forks (some of them have a LOT of changes, no-one has had time to review them :( ).

IMHO: converting that and submitting a pull request would be quicker than debugging the actual problem here :). It might even find/fix the bug automatically during the auto-ARC-ify feature in Xcode.

**Comment by MaddTheSane** [comment]
IIRC, my biggest problem when converting to ARC was how SVGKImage cached the images, mainly how it overrides the dealloc function.

**Comment by paulgee31** [comment]
I'm not sure it is a bug but the way SVGKImage uses a global cache and states 

#define ENABLE_GLOBAL_IMAGE_CACHE_FOR_SVGKIMAGE_IMAGE_NAMED 1 // if ENABLED, then ALL instances created with imageNamed: are shared, and are NEVER RELEASED

I tried building with this disabled which gave various KVO warnings but didn't help the memory problem. 

I've decided to use UIWebVIew to render the SVG files instead. Thanks for the suggestions.

**Comment by adamgit** [comment]
@MaddTheSane yeah, in converting other projects, I found we often had to re-think some classes given ARC removes the dealloc call.

@paulgee31 sorry to hear that. Memory (de-)allocation is fine without ARC. When someone converts the current branch to ARC, I imagine it'll work fine.

**Comment by paulgee31** [comment]
Some I'm back for another attempt, as it struck me could I just compile the class that used SVGKit with the -fno-objc-arc build setting. I then set my SVGKFastImageView.image to nil and then call release on the image before assigning a new one. This keeps the memory usage low but I was seeing a:
An instance 0x1d774f10 of class SVGKImage was deallocated while key value observers were still registered with it. Observation info was leaked, and may even become mistakenly attached to some other object. Set a breakpoint on NSKVODeallocateBreak to stop here in the debugger. Here's the current observation info:
<NSKeyValueObservationInfo 0x1ca8cf50> (
<NSKeyValueObservance 0x1bb5ecb0: Observer: 0x1d774f10, Key path: DOMTree.viewport, Options: <New: NO, Old: YES, Prior: NO> Context: 0x0, Property: 0x176aa460>
)

So I remove DOMTree.viewport observer from the SVGImage  manually just before release and all seems happy now, except my gut which says this is a hack which could come back to haunt me.   

Any thoughts on what I should or shouldn't be doing?

**Comment by adamgit** [comment]
c.f. #184 - I think the observer stuff needs rewriting :)

**Comment by adamgit** [comment]
@MaddTheSane 's patch might fix it, but we've patched, re-patched, and re-re-patched this before, so I don't want to approve a patch until someone holds their hand up and says "I have fixed it, here's my test case that shows it broken, shows it fixed"

**Comment by michaelfrain** [comment]
Has there been any movement on this? We're using SVGKit in a project and in our process of preparing for iOS 8, this has gone from "random once-in-a-while crash" to "every time SVGKit is used crash".

**Comment by MaddTheSane** [comment]
Have you tried my fork?
Is it mainly the caching that is having problems? Have you tried disabling it?

**Comment by cutthis** [comment]
@MaddTheSane does your branch work with ARC? I'm having the same issue as the original poster with SVKImage not being released under arc

**Comment by MaddTheSane** [comment]
My fork uses ARC. You can also disable caching at runtime. Note that the main branch of my fork is _master_.

**Comment by ghost** [comment]
Try this in viewWillDisappear: method:

```
    [svgImageView.image.CALayerTree setObservationInfo:nil];
    [svgImageView.image.DOMTree setObservationInfo:nil];
    [svgImageView.image.DOMDocument setObservationInfo:nil];
    [svgImageView.image setObservationInfo:nil];
    [svgImageView.layer setObservationInfo:nil];
```
