### ISSUE TITLE
Can you port SVGKit in Swift?

### ISSUE THREAD

**Issue by Emasoft** [SVGKit/SVGKit#189]
Please port the SVGKit in Swift, it will make easier to contribute to the project and simpler to debug in native Swift projects.

**Comment by MaddTheSane** [comment]
It should be able to import Swift into a project that uses Swift. If a framework doesn't have modules included, you can include headers from the framework in a bridging header.

**Comment by adamgit** [comment]
This is absurd. No: No-one is going to delete 4 years of development to create a dumbed-down, lower-quality API.

**Comment by rhcad** [comment]
I have used SVGKit in [a Swift framework project](https://github.com/rhcad/ShapeAnimation-Swift/tree/SVG) as the following steps:
1. Drag SVGKit-iOS.xcodeproj into your Swift framework project.
2. Add SVGKit-iOS to the project's `Target Dependencies` and `Link Binary With Libraries`.
3. Add SVGKit's header files needed as your wish to the project and make them as public.
4. Add import statements in `ProjectName`.h which contains `you should import all the public headers of your framework using statements like` comment.
5. Now clean and build, you can use SVGKit in Swift code like `let image = SVGKImage.imageNamed("foo.svg")`.

Enjoy it with Swift!

**Comment by rhcad** [comment]
In order to not import too much headers of SVGKit into Swift code, I have remove some import statements about DOM in SVGKit #268.

I just use the following headers to load and draw SVG files:

#import "SVGKImage.h"
#import "SVGKParser.h"
#import "SVGKLayer.h"
#import "CALayerExporter.h"
#import "SVGKExporterNSData.h"
#import "SVGKExporterUIImage.h"
#import "SVGKImage+CGContext.h"

**Comment by maxdignan** [comment]
I found when I added this to my Build Settings > Header Search Paths it worked  -  ${PROJECT_DIR}/usr/local/include   (wherever the headers are compared to your project).

**Comment by MaddTheSane** [comment]
Another option would be to build SVGKit as a framework, and have it use a custom module map.

**Comment by RYG81** [comment]
so do we have it working in swift now?
