### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by vojto** [SVGKit/SVGKit#19]
Hi, I took the liberty of creating a Podspec for your great library, SVGKit.

Please review it here: https://github.com/CocoaPods/Specs/pull/228

Let me know if there's any problem.

Thanks for your great open-source contribution!

**Comment by adamgit** [comment]
Thanks. I'm afraid I've never heard of CocoaPods, so I don't know what we'd do with a Podspec? Can you explain this a bit more?

I had a quick look at the linked page and the "requirements" and it appears we'd need to declare a versioning strategy, start having official versions etc (can this be managed through GitHub? The page only gives instructions for git command line)?

At the moment, I don't know if we can support version numbers, they wouldn't make any sense. We're still migrating the library. But ... as I said, I've never heard of CocoaPods, so I might have misunderstood what's needed?

**Comment by idStar** [comment]
CocoaPods are increasingly supported and worthwhile. They're like RubyGems in the Ruby eco-system, but for Cocoa. I've not written a spec for them before, and just started using them. They definitely simplifying pulling down a third party library that has such a spec, and having all the build settings just write to incorporate the library into one's own app.

**Comment by adamgit** [comment]
We have a version number now, finally :). Master is now tagged at 1.0 - and each major release will be tagged too. If anythign else is needed for cocoapods, please open issues / email me directly

**Comment by Bodacious** [comment]
Hi guys - could you please update the cocoa-pod code? SVGKit is crashing when I try to install it using cocoa pods because of a bug in SVGRectElement which I believe has been addressed.

**Comment by adamgit** [comment]
It was updated a while back, I rememebr merging it. You might be stuck on
an old CP that doesnt update.

As I understand it, with the old CP, you have to update YOUR copy (this was
a major pain)  - although the new CP now tracks a branch instead of a
version (newer version of CP? Or we misunderstood the instructions first
time round, maybe? :)), so once you are on the new CP spec you wont have
this problem again.

**Comment by Bodacious** [comment]
Thanks - it looks like you were right :)

**Comment by lemonkey** [comment]
Did you ever publish the latest podspec that tracks a branch to the CocoaPods public repo?  The latest official version is still v1.2.0.
