### ISSUE TITLE
Performance Degradation in commit #e5b171dcd2b176e97c00bf3d971b513a83f77095

### ISSUE THREAD

**Issue by samus** [SVGKit/SVGKit#190]
I have an app that displays about 16 SVG images on a single screen.  Most of them are simple logos and average about 10 KB.  One is rather large with a lot of paths in it.  It's about 300 KB.  Prior to the commit in the subject line the screen would render quickly enough that it was fine for all of the work to happen on the main thread and not have any ui blocking issues.  With the changes introduced in that commit the screen locks up the main thread for 10+ seconds.  I tried putting the rendering into a background queue and dispatching the assignment of the completed image on the main thread but all I get is a UI that is blank but responsive with the SVGs being painted onto the screen at long intervals.  

The code pre-background rendering is nothing special.  It just uses a SVGKFastImageView inside of a collection view cell.  The SVGKFastImageView is init'd with a placeholder image that gets replaced with a logo that is later replaced when the collection view dequeues a cell.

**Comment by adamgit** [comment]
Github please link it:#e5b171dcd2b176e97c00bf3d971b513a83f77095

**Comment by adamgit** [comment]
Gah. Is it precoseluy that commut?

Only 1 line changed. If ylu delete the autoreleasepool does perf imorove?

**Comment by samus** [comment]
Previously I had a local pod spec pinned to an earlier version. After
noticing 1.2 was out I changed my pod file to point to the spec file in the
1.2 tag. I then noticed the slowness and went about trying to find the
latest commit in the 1.x branch that I could use.

**Comment by adamgit** [comment]
Ah, I think I've seen it. The log message that accompanies that line can get printed THOUSANDS of times!

Try commenting out the log message starting "Apple's implementation of scanCharactersFromSet seems to"

...if that fixes it, perhaps we delete the log message. It was a "this could go wrong, better put a warning to be safe" thing.

**Comment by adamgit** [comment]
More info: in the current build, logging seems to be set to Verbose by default.

I would strongly recommend you use the Release build (which should be using a much quieter logging setup). This can also increase general performance for your app.
