### ISSUE TITLE
DDLogCWarn is not a thing as far as I can tell

### ISSUE THREAD

**Issue by geraldcor** [SVGKit/SVGKit#196]
Throughout the code you have references to `DDLogCWarn` and I get many compilation errors because of it. I changed them all to `DDLogWarn` and it compiles just fine.

However, I also had to change `Pods-SVGKit-prefix.pch` to import `CocoaLumberjack.h` instead of `DDLog.h` to get rid of `"implicit declaration"` warnings and indeed compilation errors as well for other log levels used.

Is this indeed a bug or am I missing something after I updated my pods?

**Comment by adamgit** [comment]
Off the top of my head ... CWarn is for C functions where it would be 
illegal to call objectivec reflective methods - at best, it would crash. At 
worst, pointer corruption.

I would guess there's something wrong with your pods. But maybe its a new 
feature in xcode6?

**Comment by geraldcor** [comment]
I am on XCode 5 still. It probably is my pods because I did and update everything went to hell. Ok. I'll revert back and see if I can't figure it out. Would there need to be any Linker declarations I should be looking at?

**Comment by adamgit** [comment]
We try to keep the build customisation as light as possible.

I'd checkout the project without pods - the demo project is preconfigured 
and "known good", so you can check all non default build settings quickly, 
and then copy those across to your pods build (if different).

I dont like pods because they cause too many of these problems, with their 
opaque scripts, custom workspaces, etc ... blackbox stuff mixes badly with 
buildsystems, IME :).

**Comment by geraldcor** [comment]
Yeah...that's where I'm leaning. I was wowed by veiled simplicity. Ah well. It's nice when it works. Thanks.

**Comment by geraldcor** [comment]
I think there actually is an issue when using CocoaPods.

In the source you have Source > Vendor > Lumberjack and in there it defines `#define DDLogCWarn(frmt, ...)    LOG_C_MAYBE(LOG_ASYNC_WARN,    ddLogLevel, LOG_FLAG_WARN,    0, frmt, ##__VA_ARGS__)`

When using CocoaPods, Lumberjack is added as a dependency and the version on GitHub does not have DDLogCWarn defined anywhere. Also, the import as I mentioned above does need to be changed to `CocoaLumberjack.h`

I'll check in with Lumberjack and see if the omission of DDLogCWarn was on purpose.

**Comment by adamgit** [comment]
Ah.

Off the top of my head: to make CP work, we needed a special version of Lumberjack (because the original version didn't allow libraries to compile at all!). They changed that, added a new scheme where libraries can set a "default" logging level, that apps can then re-compile and override.

...but I think no-one has upgraded SVGKit to use this new feature yet (it requires us to set a different compile-time constant from the normal one. Instructions are on the main Lumberjack github page, but they're a little confusing / rushed.)

**Comment by adamgit** [comment]
So: our lumberjack version is probably 12+ months behind the latest version (because we don't want to upgrade without implementing that new feature)

**Comment by adamgit** [comment]
c.f. issue #163

**Comment by geraldcor** [comment]
Cool. Well I'll see if I can point the podspec to the older version for now and/or make SVGKit work with 2.x (and fork most likely). I did raise an issue in Lumberjack addressing the omission of the C functions, which they may be able to fix easily. It seems 2.x is Beta.

**Comment by adamgit** [comment]
I believe the change is only 2 lines of code + a couple of lines in the
Demo app to define its own preferred log-level.

Should be quick :)

**Comment by haemi** [comment]
any update on this issue? Would really love to update my Pods :)

**Comment by adamgit** [comment]
You could try it yourself? Or comment on the Lumberjack issue in their repo?

**Comment by geraldcor** [comment]
Yeah. Sorry. I'll do a pull request so you can at least see what I've done so you can update your own code. Or just update your pods pec to point at 1.9x. 

[sent from mobile device]

**Comment by chakrit** [comment]
For anyone encountering this problem in the meanwhile, I worked around this in my project by manually including CocoaLumberjack 1.9 at the top level (so SVGKit uses that instead of the latest version.)

``` ruby
pod 'CocoaLumberjack', '~> 1.9'    
pod 'SVGKit'
```

Ideally, the `1.9` requirement should be in the spec if it's required for compilation.

**Comment by caseyoneill** [comment]
This also got me until I found this thread. Is there anyway to have the podspec point to the correction dependency version?

**Comment by seltzered** [comment]
Looking at https://github.com/CocoaLumberjack/CocoaLumberjack/issues/220 where they talk about this change, it looks like it's okay to just rename the methods from DDLogC\* to DDLog\* methods when using Lumberjack 2.x . I'm still a bit lost as to _how_ "PRETTY_FUNCTION" does this, but from reading [this](http://www.delorie.com/gnu/docs/gcc/gcc_78.html) it seems like it's intended pass the whole function signature and allows it to be language-ignorant to an extent. 

I tried this in https://github.com/seltzered/SVGKit/compare/LumberJack-2.x-migration using lumberjack 2.x things build fine and run after the rename. Still doing more tests/cleanup before pull-requesting.

(for curiosity, also [tried the rename](https://github.com/seltzered/SVGKit/tree/changing-ddlogc-on-old-lumberjack-demo) when using lumberjack 1.x and got expected compile errors.

**Comment by scottbyrns** [comment]
I fixed it by deleting the logging from the library.
