### ISSUE TITLE
Support text

### ISSUE THREAD

**Issue by mattrajca** [SVGKit/SVGKit#2]

**Comment by vipin001** [comment]
I have put the image having text.The text is not writing anyway....... .Only blank images are producing. What should i do to get the characters.

**Comment by boobalaninfo** [comment]
I have solved this issue by using SVG editors. Please find the solution here.

http://greatindiaclub.oliwy.net/?p=1093

http://stackoverflow.com/questions/12275721/why-svgmap-text-field-is-not-showing-on-ipad-iphone-application/12275740#12275740

**Comment by adamgit** [comment]
The 2013base branch now has basic support for text (although most styling info - colors etc - is ignored)
