### ISSUE TITLE
Steps to Compile on iOS with XCode 4.2.1

### ISSUE THREAD

**Issue by trevelyan** [SVGKit/SVGKit#21]
Oddly, the sample XCode projects included in the distribution compiled flawlessly on my machine, yet I had difficulty compiling an independent project using the library. It took some time to figure out the solution, so I'm documenting it here in case others have difficulty. The solution ended up being:

(1) Adding the following import call to the top of the file CALayerExporter.m:

  #import <QuartzCore/QuartzCore.h>

And the following steps that are documented elsewhere, with minor changes to search paths according to the latest SDK:

(1) Add to following to Header Search Paths (NOT "User Header Search Paths") on the Build Settings Page:

  /usr/include/libxml2 

(2) Turn off Automatic Reference Counting on the Build Settings Page.

(3) Set "Missing Function Prototypes" to "No" on the Build Settings Page.

(4) Add the QuartzCore.framework and libxml2.dylib

**Comment by reklis** [comment]
Thanks for documenting this.  You could also use user header search paths, and tick on "always search user paths".  

When integrating arc/non-arc code in the same project you can enabled or disabled ARC on a per-file basis using these options:

enable : -fobjc-arc
disable: -fno-objc-arc

More here: http://clang.llvm.org/docs/AutomaticReferenceCounting.html

**Comment by trevelyan** [comment]
Just to clarify -- not sure why I missed it -- the files that need to be included at the top of CALayerExporter.m are CALayerExporter.h and QuartzCore/QuartzCore.h. The former in double quotes and the latter in triangular brackets.

**Comment by adamgit** [comment]
fixed in the 2013base branch, we believe. (I hope! I've deleted the git-submodule, which was causing several problems including this one)
