### ISSUE TITLE
SVG displaying issue: "Assertion failed".

### ISSUE THREAD

**Issue by Aft3rmathpwnz** [SVGKit/SVGKit#210]
I created SVG file in autumn 2013 to check its availability on ios. Then when I checked, I created much more SVG files the same way, but now, when I started to check them all I get next error: "Assertion failed: (corner_width >= 0 && 2 \* corner_width <= CGRectGetWidth(rect)), function void CGPathAddRoundedRect(CGMutablePathRef, const CGAffineTransform *, CGRect, CGFloat, CGFloat), file Paths/CGPath.cc, line 369." when try to open all of them except for the old one. I used the same figures and rules, can you help me to figure it out? Thank you! The working one: http://www.filedropper.com/floor4 . Another not working example: http://www.filedropper.com/floor5 .

**Comment by adamgit** [comment]
Have you checked what the assertion tells you to check?

Is it incorrect?

Is your file legal?

**Comment by Aft3rmathpwnz** [comment]
It's opening in Inkscape and in Xcode preview. Sorry for ridiculous question, but where I can see this code line to set breakpoint and see its condition, cause I can't find CGPath.cc implementation, and there are only stack operations in debug navigator.
Edit: Availability: Available in iOS 7.0 and later. Hm, I running it on iOS 6.1 simulator. But some working one SVG file is loading fine. I have no idea what's happening.

**Comment by MaddTheSane** [comment]
The CGPath.cc file is within iOS’s frameworks. Something inside of the CoreGraphics is raising an exception.
You’ll have to put a breakpoint before the CoreGraphics call and see if everything is alright.

**Comment by adamgit** [comment]
A thought: we wrote our own version of this method, that worked fine.

Then Apple added a method with the same name to ioS7, I think.

So we removed our implementation and started using Apple's.

Maybe our version was more forgiving?

**Comment by Aft3rmathpwnz** [comment]
There is no CGPathAddRoundedRect method in CoreGraphics on iOS 6.1. But how it can work now with 4th floor plan on iOS 6.1? What method is responsible for it on iOS 6.1?

**Comment by adamgit** [comment]
Sorry, wrote quickly on mobile phone. I meant: we replace it with Apple's
on iOS7, but (IIRC) for IOS 3/4/5/6 we use our old hand-written method.

**Comment by Aft3rmathpwnz** [comment]
Oh, okay, thank you, where I can find it? and why error message now on 6 is linking to cgpath's method, that not exists yet on iOS6, looks like magic)

**Comment by adamgit** [comment]
I would guess you're not building for iOS6, even though you think you are?

**Comment by Aft3rmathpwnz** [comment]
It builds for iOS 6. Anyway, the problem was having incorrect angle for rounded rects, it somehow broke maybe while copying svg files, or opening it in different Inkscape versions, or on different platforms (osx\win). Solved by reset all rounded rects to rects in Inkscape and make them rounded back.
