### ISSUE TITLE
How to change color for SVGKImage?

### ISSUE THREAD

**Issue by angeloh** [SVGKit/SVGKit#213]
How can I change color for SVGKImage?

**Comment by adamgit** [comment]
Please be more specific.

**Comment by Broich** [comment]
I once wrote a little category requiring a key "tintLayer".

```
- (instancetype)imageWithThemeColor {
    NSString *tagToFind = @"tintLayer";
    SVGElement *element = (SVGElement *)[self.DOMDocument getElementById:tagToFind];
    CALayer *layer = [self layerWithIdentifier:element.identifier];
    CAShapeLayer *shapeLayer = (CAShapeLayer *)layer;
    shapeLayer.fillColor = [[NRThemeManager sharedThemeManager] themeColor1].CGColor;

    return self;
}
```

**Comment by adamgit** [comment]
No update from OP in 1 month, so I'm closing this. It's not really an Issue.

**Comment by Juice007** [comment]
I know a method that can change the color of an UIImage.
So, we should get the UIImage from SVGKImage firstly.

    UIImage *img = [SVGKImage imageNamed:@"imageName"].UIImage;

And then, we can define a method like this:

    - (UIImage *)changeTintColorWithImage:(UIImage *)img color:(UIColor *)tintColor {
    UIImage *imageIn = img;
    CGRect rect = CGRectMake(0, 0, imageIn.size.width, imageIn.size.height);
    CGImageAlphaInfo alphaInfo = CGImageGetAlphaInfo(imageIn.CGImage);
    BOOL opaque = alphaInfo == kCGImageAlphaNoneSkipLast
    || alphaInfo == kCGImageAlphaNoneSkipFirst
    || alphaInfo == kCGImageAlphaNone;
    UIGraphicsBeginImageContextWithOptions(imageIn.size, opaque, imageIn.scale);
    CGContextRef context = UIGraphicsGetCurrentContext();
    CGContextTranslateCTM(context, 0, imageIn.size.height);
    CGContextScaleCTM(context, 1.0, -1.0);
    CGContextSetBlendMode(context, kCGBlendModeNormal);
    CGContextClipToMask(context, rect, imageIn.CGImage);
    CGContextSetFillColorWithColor(context, tintColor.CGColor);
    CGContextFillRect(context, rect);
    UIImage *imageOut = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return imageOut;
    }
OK. this method can help us change the color of an image.It mainly use some APIs in CoreGraphics.
And I suggest you can create a category with UIImage, it will be convenient to use.
