### ISSUE TITLE
SVGKit will crash on every new device resolution and you won't be able to test it until you have the new device

### ISSUE THREAD

**Issue by newmaniese** [SVGKit/SVGKit#219]
We were shocked to start getting the reports that our applications were crashing on the new IPhones, we tested everyone of them on the simulator.

Right now, if a device doesn't match the existing if statements, SVGKit will crash the application. There has to be a better way to detect resolution and have a reasonable fallback in case there is a device that doesn't match our expectations.

I will be looking into this and hope to be providing a pull request shortly, but wanted to start a discussion in case there is logic as to why this was implemented this way.

**Comment by adamgit** [comment]
Assertions only fire if you're running a DEBUG build, and/or you've enabled them explicitly in your live builds. Did you ship a debug build? Or is the default return value - 0.0f - causing a crash elsewhere?

This situation is severe enough that it's worth having an assertion during development: the whole rendering stack is corrupt if we don't know your PPI ...but get asked for it by your SVG file. Off the top of my head, the spec gives no definition of what should happen here (?).

**Comment by newmaniese** [comment]
I think NSAssert still raises errors unless `NS_BLOCK_ASSERTIONS` is set as a preprocessor macro. It is NSAssert that is raising this error in our production code. This is not debug code, but we do not define NS_BLOCK_ASSERTIONS in our macros.

I agree with the severity of the error. It just feels a little hardcoded right now. Going to see if there isn't some configuration that we can ascertain this value from.

**Comment by adamgit** [comment]
Even if your project has this wrong (and it is "wrong" to delete that
macro: Apple put it there for good reason), this should be present in the
SVGKit build instructions, not your project. A Release build of SVGKit
should be stripping out the assertions before it even gets included into
your project - might be that SVGKit's Release target is now broken?

(NB: if block-assertions is missing from your release build, I'd say your
version of Xcode has serious problems, or someone has messed with your
build at some point. Apple defined it as a required build setting for
release, and Xcode has supported this automatically for years.)

**Comment by SachinAhujaGit** [comment]
From Xcode 5, we have "Enable Foundation Assertions" setting available. Currently, the latest SVGKit's build setting is set to Yes for both debug and release targets.Set debug as yes and release as no to block assertions in release build. This is also the apple's default settings.
