### ISSUE TITLE
Loads blank image when loading svg generated with potrace

### ISSUE THREAD

**Issue by ThomasCle** [SVGKit/SVGKit#22]
I'm using potrace to generate a svg from a bmp-file. SVGKit can't load the generated SVG, but Illustrator can.

Check out more detailed description of my problem here:
http://stackoverflow.com/questions/11470110/svgkit-does-not-show-potrace-generated-images

**Comment by adamgit** [comment]
c.f. answer on SO - for now, you cannot use transforms in SVGKit core.

But this branch has good support for transforms: https://github.com/adamgit/SVGKit/tree/transforms

(support is complete in code, but it needs a few additional parser lines to parse all variations of words like "Scale", "scale", etc.)

**Comment by adamgit** [comment]
PS: you probably don't have a blank image, just an image that's completely off-screen.

This is another part of SVG that main SVGKit doesn't support yet, but the branch linked above _does_ support, and correctly resizes your SVG's to fit the screen (as they're supposed to) - even if it doesn't recognize all the transform commands.

**Comment by reklis** [comment]
How stable do you consider the transforms branch at this point?  Should we being integrating into the trunk?

**Comment by adamgit** [comment]
Very stable, but ... Im still making sweeping changes to the API. This is
probaby the last round od major changes

**Comment by adamgit** [comment]
FYI - I've just updated the transforms branch above. I think it is now better than main SVGKit in all ways except for fixes in past 2 months. So ... e.g. the libxml2 fix is missing, and I think some stuff to do with stylesheets, and ... anything else since I forked.

**Comment by ThomasCle** [comment]
Thanks adam! The SVGKit works with my svg files with translate and scale. But there seems to be a problem when zooming on the UIView containing the SVGKImage layer. (this worked with the old document solution :-) ).

Here's a screenshot of the simulator showing the problem:
http://i.imgur.com/O57dM.jpg

Again thank you for the support. I'm very grateful for your help.

**Comment by adamgit** [comment]
Apple never documented their zooming properly - you're using UIScrollView, right?

SVGKit has used various tricks (which only partially worked) at different times to try and fake it.

In my branch, I've tried to clean everything out. Right now, if you want sharp zooming, you have to implement it in your app, using a custom UIScrollView - NB: this appears to be Apple's preferred approach

(this is bad API design by Apple - the rendering classes should make this decision. Originally, they did - and there's still some legacy Apple code for doing that - but it causes problems with other parts of Apple's API if you use it. You can try recursively calling "shouldRasterize = TRUE" on every CALayer in the CALayerTree - that will probably fix it for you _temporarily_)

EVENTUALLY I want to write a bunch of custom subclasses of Apple's classes, and workaround their API. But that's going to be a lot of work, and it's more likely that someone else will do it before I have the time :(

**Comment by adamgit** [comment]
I believe this is now FIXED in my fork:

https://github.com/adamgit/SVGKit/

...use an SVGKImageView and it will automatically re-render. Unless you tell it not to (which is REQUIRED with Apple's UIScrollView - in that case, you should call:

   [svgKitImageView setNeedsDisplay]

in Apple's "didEndZooming:atScale:" callback

**Comment by adamgit** [comment]
and in the 2013base branch
