### ISSUE TITLE
Potential leak of object (Using SVGKit (1.2.0))

### ISSUE THREAD

**Issue by Maskime** [SVGKit/SVGKit#220]
Hi,

Thank you for this great work. To help you here is a bunch of warnings that shows since I updated XCode to v6 :
- Pods/SVGKit/Source/UIKit additions/CALayer+RecursiveClone.m:53:51: Potential leak of an object
- Pods/SVGKit/Source/UIKit additions/CALayer+RecursiveClone.m:54:48: Potential leak of an object
- Pods/SVGKit/Source/UIKit additions/CALayer+RecursiveClone.m:65:7: Potential leak of an object
- Pods/SVGKit/Source/UIKit additions/CALayer+RecursiveClone.m:74:43: Potential leak of an object
- Pods/SVGKit/Source/UIKit additions/CALayer+RecursiveClone.m:77:7: Potential leak of an object
- Pods/SVGKit/Source/SVGKImage.m:289:4: Potential leak of an object stored into 'self'

Again, thank you for this great work it helped me to win a tremendous amount of time on my current projet.
Cheers

**Comment by adamgit** [comment]
I'm afraid we're not supporting anything older than version 2.0

If these leaks still exist on 2.x branch, please re-open with details.
