### ISSUE TITLE
iPhone 6 crash

### ISSUE THREAD

**Issue by bsousa156** [SVGKit/SVGKit#225]
*\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Not supported yet: you are using an iPhone that didn't exist when this code was written, we have no idea what the pixel count per inch is!’”

**Comment by adamgit** [comment]
And you're using the current version?

**Comment by bsousa156** [comment]
No. After updating the issue was solved.
Many thanks.
