### ISSUE TITLE
CocoaLumberjack 2.x requires migration in code

### ISSUE THREAD

**Issue by buttifabio** [SVGKit/SVGKit#230]
CocoaLumberjack 2.x requires migration in code.
If i add only pod 'SVGKit', '~> 1.2' to my project it raises errors because of automatic installation of 2.x CocoaLumberjack.

I fixed by manually importing pod 'CocoaLumberjack', '~> 1.9' before importing SVGKit project.

You should update your podspec file or migrate all the logging code.

Thank you.

**Comment by seltzered** [comment]
just for anyone context-digging, the 1.x branch has this fix: https://github.com/SVGKit/SVGKit/commit/7422e85f6d34a9dcc1f9b25ac5f8963170d01f66 . 

FWIW, I want to start looking into migrating to 2.x (started playing with things on MTS's fork https://github.com/seltzered/SVGKit/compare/LumberJack-2.x-migration & commented on (https://github.com/SVGKit/SVGKit/issues/74#issuecomment-55513533 ) using lumberjack's flag bit(s) to identify svgkit-specific logging), but it'll be ~ 2 weeks before I can look into it again.

**Comment by adamgit** [comment]
Any progress on this?

If we can migrate direct to Lumberjack 2.x, there's (IMHO) no point in us backfixing the 1.x issues any more - we'll go straigth to 2.x, and push out a new point release of SVGKit, saying "now uses/supports Lumberjack 2.x"

**Comment by seltzered** [comment]
Hey @adamgit , just saw your comment!  I'm finally spending this weekend and next week working through this, starting on MTS's fork (that's honestly just the one I'm more familiar with) then switching to this one.

Will write some more plans soon after playing with things tonight & tomorrow (experimenting/pushing things to https://github.com/seltzered/SVGKit/tree/LumberJack-2.x-migration )

**Comment by seltzered** [comment]
Still working on it, but I'm planning to just introduce a settable flag bit for SVGKit, and have methods using the flag bit within a SVKLog.h file. So...largely following https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/FineGrainedLogging.md

NOTE: As you may see in the [branch](https://github.com/seltzered/SVGKit/tree/LumberJack-2.x-migration), I'm adding in CocoaLumberjack via spec.dependency then installing it via a local-referencing Podfile. I couldn't find a way within cocoapods to coerce dependencies to the 'vendor' directory that originally contained lumberjack, so let me know if you (or @MaddTheSane ) have an issue with the repo containing a 'pods' directory for lumberjack.

**Comment by mdwem** [comment]
What is the latest pod spec for the SVG kit.I tried  pod 'SVGKit', '~> 1.2.0' ,however this doesn't seem to have the new files

**Comment by adamgit** [comment]
Lumberjack is now a self-contained framework in its own subfolder, currently linked as v2.1.0 (latest, Jan 2016).

I'm assuming this issue is fixed. If not, re-open with details.
