### ISSUE TITLE
SVG kit for ios 8

### ISSUE THREAD

**Issue by mdwem** [SVGKit/SVGKit#235]
Hi,

I tried the steps listed in ios 8 xcode 6 but was unable to compile.The C/C++ Compiler Version" = "LLVM Compiler 2.0 as mentioned is not supported.Is this library available for the new iOS.

**Comment by adamgit** [comment]
Whatever Apple is now using should be fine.

They appear to have arbitraily renamed the compiler, and deleted old ones.

**Comment by adamgit** [comment]
You say "was unable to compile" but you don't give any info on what went wrong. Please re-open if you have a specific proboelm

**Comment by mdwem** [comment]
It says file not found SVGKit/SVGImage.h .when i try to import it The only available in xcode is 'LLVM 6.0'

**Comment by smithtopher** [comment]
I'm able to compile in xcode 6 with no problems. 

Regards running on iOS8 #214 will cause the app to crash when deallocating certain SVGKit objects. Might want to wait for this to be resolved before depending on SVGKit for any production iOS8 app.

**Comment by mdwem** [comment]
Hi,did you follow the steps as listed in the documentation.I tired but couldn't get it working

**Comment by adamgit** [comment]
Open the demo project, and run that. We've made sure everything there is setup 100% correctly. If it works, then you've made a mistake somewhere, or you've found some strange new bug in Xcode.

Try making your project match the demo project.

**Comment by adamgit** [comment]
I testd just now: everything builds correctly with SVGKit, running Xcode 6.0.1 on OSX 10.9.5

**Comment by mdwem** [comment]
i see the header search path to be 'Source  calayer-exporter' in the demo project.Should i change that in my project as well

**Comment by mdwem** [comment]
Hi,
I followed these steps.
Open "SVGKit-iOS.xcodeproj", and Build it (cmd-B)
in left navbar, scroll to bottom, and open the "Products" section
right click the library ("libSVGKitBLAHBLAH.a") and select "show in finder"
GO UP ONE FOLDER
select the "Debug-universal" (or Release-universal if you were building in Release mode) folder
Drag/drop the .a file and the "usr" folder into your project (select the "Copy files" checkbox)
In Build Settings, select "Other Linker Flags" and add "-ObjC"
Edit your build settings and set "C/C++ Compiler Version" = "LLVM Compiler 2.0"
Add ALL the frameworks and 3rd party libraries listed below (go to "Build Phases", and "Link Binary with Libraries"): 

Am i missing anything
