### ISSUE TITLE
Getting Started incomplete

### ISSUE THREAD

**Issue by revolter** [SVGKit/SVGKit#241]
I can't make it work, mostly because of the step 6. What does `Drag/drop the .a file and the "usr" folder into your project` mean? Should I drag them into Finder or into XCode? And if I drag them intro XCode, in which panel or screen? Or what folder or group? Can't I copy them into the project folder using Finder and them `Add files` in XCode?

**Comment by adamgit** [comment]
Dragging ANYWHERE in Xcode should work fine - it's up to you how you want
to structure your folders.

Likewise, "add files" SHOULD work.

Historically, for most of the past five years, the "add files" dialog in
Xcode was broken (mulitple ways), and Apple couldn't be bothered to fix it
:(, causing a lot of confusion among developers. So, a lot of us are a bit
suspicious of it still (even though it mostly works correctly these days) -
we're probably being too suspicious :).

**Comment by revolter** [comment]
The step 9 also says that you should add `libxml2.dylib` in the `Link Binary with Libraries` section, but the Demo project doesn't have it added. Why is that?

**Comment by adamgit** [comment]
The demo project DOES have it, I double-checked. I don't believe you'd be
able to run it (nor compile it!) without that.

**Comment by adamgit** [comment]
PS: thanks for checking the instructions - once you get it working, if you
want to rewrite them to make it clearer/better, suggestions welcome!

**Comment by revolter** [comment]
Sorry! I had the `SVGKit-iOS` opened. It still can't find "SVGKit.h" file when I CMD click it or when I build the project.

PS: I would gladly rewrite it to be easier for beginners like me to integrate it if I could make it work

**Comment by adamgit** [comment]
Close everything, (xcode has MAJOR bugs if you open more than one project
at once).

Try:
1. Open SVGKit-iOS on its own, build, quit
2. Open Demo project on its own, build.

If it still cant find SVGKit.h, it usually means something in your
header-import has got corrupted. Look in the build settings, and check all
"header paths" "user paths" etc. Often you'll find something absurd - like
Apple double-escaping (which is always incorrect, and breaks Xcode) paths
or similar.

Xcode 6 has known bugs here on Apple's side - they can and do corrupt your
project file! (IMHO it's such a bad thing to do (corrupt a project) that
they should have been testing and unit-testing much more aggressively!)

**Comment by adamgit** [comment]
Sometimes, someone will submit a code patch, and accidentally corrupt the
Demo project. This is hard to detect - and usually manifests with "can't
find SVGKit.h".

I don't think that's the case right now - and worse: it won't affect people
who were already building successfully, so its very hard for us ot notice -
but it's a possibility too.
