### ISSUE TITLE
Couldn't load svg file! (Output is empty)

### ISSUE THREAD

**Issue by quant-algo** [SVGKit/SVGKit#242]
In our project We've used SVGKit for rendering icons. This icon is not rendering. Apparently It's because it has a little sophisticated paths combination. 
https://www.dropbox.com/s/7sbnmjpdn5wem8g/folder.svg?dl=0

**Comment by adamgit** [comment]
Please read the compulsory notes that were shown to you when you created the issue:

https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md

Otherwise I'll have to close your issue, sorry.

**Comment by quant-algo** [comment]
I understand. I don't expect anyone to solve this issue.
It's a bug report.
Where should i put it?

**Comment by adamgit** [comment]
Reply here with detail of what SVG commands are failing, ideally with a copy/paste of the lines of your SVG file that are affected.

Not required, but would increase chances of it being fixed sooner: screenshot of what it ought to look like, and a note to say you're licensing the file itself as public domain or MIT, so that we can include it in the test suite going forwards

**Comment by quant-algo** [comment]
Here's a sample code.

```
{ 
   .....
   imageView.image = [className imageFromSVGSampleNamed:@"folder.svg" size:20.0]
  .....
}
.....

+ (UIImage*)imageFromSVGSampleNamed:(NSString*)name size:(CGFloat)size
{
    BOOL shouldAntialias = YES;
    CGFloat multiplyFlatness = 1.0f;
    CGInterpolationQuality interpolationQuality = kCGInterpolationDefault;
    image *svgkImage = [SVGKImage imageNamed:name];
    [image setSize:CGSizeMake(size, size)];
    if( [image hasSize] )
    {
        //DDLogVerbose(@"[%@] DEBUG: Generating a UIImage using the current root-object's viewport (may have been overridden by user code): {0,0,%2.3f,%2.3f}", [self class], image.size.width, image.size.height);

        UIGraphicsBeginImageContextWithOptions( image.size, FALSE, [[UIScreen mainScreen] nativeScale] );
        CGContextRef context = UIGraphicsGetCurrentContext();

        [image renderToContext:context antiAliased:shouldAntialias curveFlatnessFactor:multiplyFlatness interpolationQuality:interpolationQuality flipYaxis:FALSE];

        UIImage* result = UIGraphicsGetImageFromCurrentImageContext();
        UIGraphicsEndImageContext();


        return result;
    }
    else
    {
        NSAssert(FALSE, @"You asked to export an SVG to bitmap, but the SVG file has infinite size. Either fix the SVG file, or set an explicit size you want it to be exported at (by calling .size = something on this SVGKImage instance");

        return nil;
    }
}
```

Image does not renders at all.

![screen shot 2014-11-17 at 8 06 08 pm](https://cloud.githubusercontent.com/assets/132761/5073454/3aa61104-6e97-11e4-9269-3039516692d4.png)

I'm not sure about icon's licensing. It came from our designer. I'll ask him about that.

**Comment by adamgit** [comment]
Use the debugger and find out what's not rendering. Xcode has a great 
debugger, and you can breakpoint that method and step through and watch it 
build up the image.
