### ISSUE TITLE
Zooming performance very bad

### ISSUE THREAD

**Issue by lumaxis** [SVGKit/SVGKit#243]
I'm trying to implement a map view using SVGKit and kept pretty close to the example in the Demo Project in my project. One issue I'm noticing now is that the performance of the scroll view zooming is practically unusable, both with a FastImageView and a LayeredImageView.
My .svg is rather large with around 1.5MB and understandably the rendering of the CALayers takes very long. Does anyone have an idea or a sample how to do this efficiently? My only other idea what be to try to have gradual zooming levels which are controlled via a e.g. a button.
Thanks for any help!

**Comment by adamgit** [comment]
That is an enormous svg. Potentially uses gigabytes of RAM to render, even 
on high performance library!

I would either/both:
1. Simplify it: collapse some line segments using a map simplification 
   algorithm. I've used this to great effect myself, plenty of algorithms our 
   there for this.
2. Split your content into two or more SVG files, for different tiled areas 
   of your Map. Rendering each tile separately gives more opportunities for 
   apple to cahce data.

You could try using apples CATiledLayer class for 2 - but its a terrible 
class and hard to use well in this scenario. If you go that route, make 
sure you use the collapsed layer of FastImageView, and not the separate 
layers of LayeredImagaeView.

Alternatively, render the tiles yourself - probably very fast to have a 
grid of NxM svgfastimageview  instances, each rendering a different svg.

If still not fast enough, play with exporting each svg tile to a UIImage 
(takes a second or so), and rednerinf that. When user zooms, re render 
uiimage at higher resolution.

**Comment by lumaxis** [comment]
Thanks so far adam for the tips! I tried simplifying my svg with SVGCleaner and that worked to some extent:
![screenshot 2014-11-26 01 04 48](https://cloud.githubusercontent.com/assets/406937/5194036/6d7a6a68-7508-11e4-85d6-1d469c9674a8.png)

Still, zooming is pretty bad. Your second idea is still interesting, though it doesn't exactly apply to my case. My map is of a building with different rooms and floors stacked as layers on top of each other.
Now I'm trying to figure out how to do the manual rendering of UIImages as you proposed.
