### ISSUE TITLE
Building Library

### ISSUE THREAD

**Issue by lastMove** [SVGKit/SVGKit#244]
Hello,
I know that it's not the best place to ask that.
But I am encountering the iOS 8 issue ( #235 ) 
So I wanted to try the @MaddTheSane fork. But I didn't reach to build the _universal_ library.
When I build it i can only find libSVGKit-iOS.1.2.0pre.a in the _Debug-iphonesimulator_ directory which is not for the good Architecture.
What am I doing Wrong?
(Sorry for my bad english)

**Comment by MaddTheSane** [comment]
I have enabled issues, etc, on my fork. Report the issue there and I'll see what I can do.

**Comment by lastMove** [comment]
thank you
