### ISSUE TITLE
Pods for v2.x

### ISSUE THREAD

**Issue by mdwem** [SVGKit/SVGKit#258]
Hi,

Is there a pod specification for version 2.x.

**Comment by seltzered** [comment]
Assuming you're referring to the 2.x branch of this repository, 2.x is still under development - no _tag_ has been made for any 2.x release yet, which is what I believe cocoapods looks at when just typing in something like:

pod 'SVGKit' 

There is a technically a podspec kept within the 2.x branch though. For now, you may want to try pointing to the git repo + 2.x branch in your podfile. It should look something like this:

pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'

Keep in mind you're following an in-development repository by doing this, so you may want to watch for updates.

**Comment by K-Be** [comment]
Now in pods project arc is selected.

**Comment by mdwem** [comment]
Hi,thanks.i got it working.
For any updates/commits done to the repo are pod specs updated as well.
If i am using pods in my project,how can i get those changes.
Thanks again.
