### ISSUE TITLE
Please support the full svg 1.1 specifications: many svg images are not displayed correctly

### ISSUE THREAD

**Issue by Emasoft** [SVGKit/SVGKit#264]
This library would be very useful if it supported the full svg 1.1 specifications. Almost all svg images or icons I tried are not displayed correctly. In this incomplete state the library is not usable. Please finish the excellent work that you have started.

**Comment by adamgit** [comment]
Next time, read the (required) guidelines before posting your issue.

I'm closing this - it's incorrect and useless.
