### ISSUE TITLE
SVG images not displayed/unsupported

### ISSUE THREAD

**Issue by Emasoft** [SVGKit/SVGKit#265]
SVGKit doesn't seem to be able to display some svg buttons I've made in Inkscape in an ios app I'm working on. This is how my buttons should look for reference:
![ios_app_buttons](https://cloud.githubusercontent.com/assets/713559/5924670/d56b48a0-a65d-11e4-95b4-7377a6b7eda9.png)

You can download the original svg file from my google drive (click on the download button):
http://goo.gl/m7TbmM

**Comment by adamgit** [comment]
Those are beautiful buttons - very nice!

We need you to work out specifically which features are failing. Is it the
gradients? the transparency? the shapes? the drop shadows? the layering?
etc.

As it stands, SVGKit is rendering the overwhelming majority of SVGs (both
in the specification and on the web) correctly, even including some
difficult / huge ones. Fingers crossed: it may be only one or two minor
bugs that are causing yours to fail.

...but with SVG, if its a complex image like yours, a minor bug can cause
many visual defects at once.

**Comment by Emasoft** [comment]
Have you tried to display the above svg file with SVGKit? Many things are rendered wrong or not displayed.

**Comment by adamgit** [comment]
Sure. But its not my file. All the files I use work fine, including huge 
complex ones. If you want someone to do the work to diagnose, investigate, 
plan, code, and debug a solution for you, you'd need to pay them.

If you want someone to do some of.that for.free, the more you do yourself 
the more likely someone else is to help.you.

Right now you've done nothing, except take a project that many people have 
given you for free. My last estimate was that its approx $150,000 of code. 
You need to give something if you want others to be interested in doing 
even more work for you.

**Comment by Emasoft** [comment]
Sorry, I didn't intended to force you to do anything. You asked "which features are failing" and I was just saying that the elements rendered wrong are too many to be listed. Almost 90% of the features seem missing. The image is almost flatted out. Here is how SVGKit renders it:

![svgkit svg buttons bug screenshot](https://cloud.githubusercontent.com/assets/713559/5967362/78512328-a80c-11e4-92cf-a7728fe04ae9.png)

Anyway, I'm just reporting this problem and asking if you can fix it. If you don't want/can't fix it, I understand perfectly. You did an incredible job already with this library. I'll find another solution for displaying my svg assets.

**Comment by Emasoft** [comment]
Any update on this?

**Comment by flemingm** [comment]
If you split the file into files for each button this will help with trouble shooting.
Then do a regression on one of the  single button producing several .svg files to test and debug with.
Removing features such as: gradients, the transparency, the shapes, the drop shadows, the layering.
    ie. one that is the white boarder only.
  2nd that is the centre of the button only.
3rd one that has no gradients just solid colors.

provide the SVG files, the picture of the expected results and the result you get.  

This will shorten the time for someone to look into the issue and identify the bug.

**Comment by Emasoft** [comment]
Ok, here it is a splitted version of the two main buttons svg files, you can download the zip from here: 
https://drive.google.com/file/d/0BxexooDWEb8ublZlcm5yRWpXTzQ/view?usp=sharing

Here are the screenshots of each svg file included in the zip:

![schermata 2015-02-20 alle 20 28 22](https://cloud.githubusercontent.com/assets/713559/6307870/b3549268-b93f-11e4-9ee0-c9813bdd1580.png)
![schermata 2015-02-20 alle 20 27 56](https://cloud.githubusercontent.com/assets/713559/6307871/b37ed320-b93f-11e4-9db2-9a9629f68c64.png)
![schermata 2015-02-20 alle 20 24 58](https://cloud.githubusercontent.com/assets/713559/6307873/b38145ba-b93f-11e4-8c46-f4530a0ba6f4.png)
![schermata 2015-02-20 alle 20 24 49](https://cloud.githubusercontent.com/assets/713559/6307875/b3899a4e-b93f-11e4-8a0b-041376cfae41.png)
![schermata 2015-02-20 alle 20 24 17](https://cloud.githubusercontent.com/assets/713559/6307872/b38068f2-b93f-11e4-9efd-4b4e6e49e462.png)
![schermata 2015-02-20 alle 20 23 59](https://cloud.githubusercontent.com/assets/713559/6307874/b387732c-b93f-11e4-9f6c-0365857f1f93.png)

**Comment by Emasoft** [comment]
@flemingm I've made what you asked. Is this of any help to fix the problem?

**Comment by adamgit** [comment]
@Emasoft - Everyone here is a volunteer. As per the Issue guidelines, if you want someone else to fix it for you, to do free work (unpaid) for you, you need to work out the actual, precise problem first.

Otherwise ... why would someone debug YOUR problem?

**Comment by kritikaperiwal12** [comment]
I have a SVG image file and the task is to parse that image. But i am not able to get the solution. I used a lot of Frameworks for that but nothing is working in my case. I am able to show image using Pocket SVG but text is not appearing in this case. Can anyone help me.

Link of SVG image file:  https://drive.google.com/file/d/1kdoApJ606kCXd8tfYqWGjAqs_BTOhY94/view?usp=sharing
