### ISSUE TITLE
This Type Error Are Created In My SVGKit,

### ISSUE THREAD

**Issue by akshay5993** [SVGKit/SVGKit#267]
DOESNT WORK, APPLE's API APPEARS BROKEN???? - About to mask layer frame ({{0, 0}, {729.31, 268.966}}) with a mask of frame ({{604, 22}, {158, 117}})
2015-01-28 11:53:11:593 Demo-iOS[828:60b] [SVGGradientElement] set gradient layer start = {1.1514591, 0.034577973}

 [SVGGradientElement] set gradient layer end = {1.1514591, 0.62850505}
2015-01-28 11:53:11:593 Demo-iOS[828:60b] [SVGGradientElement] set gradient layer colors = (
    "<CGColor 0x16e88660> [<CGColorSpace 0x16e094a0> (kCGColorSpaceDeviceRGB)](0.960784 0.964706 0.964706 1)",
    "<CGColor 0x16e88600> [<CGColorSpace 0x16e094a0> (kCGColorSpaceDeviceRGB)](0.882353 0.882353 0.882353 1)",
    "<CGColor 0x16e88a90> [<CGColorSpace 0x16e094a0> (kCGColorSpaceDeviceRGB)](0.882353 0.882353 0.882353 1)",
    "<CGColor 0x16e6cde0> [<CGColorSpace 0x16e094a0> (kCGColorSpaceDeviceRGB)](0.960784 0.964706 0.964706 1)"
)
2015-01-28 11:53:11:593 Demo-iOS[828:60b] [SVGGradientElement] set gradient layer locations = (
    0,
    "0.33",
    "0.66",
    1

**Comment by adamgit** [comment]
I don't see an error there. Please read the guidleines that were linked to
when you created the Issue.

**Comment by akshay5993** [comment]
I am Take the many Svg gradient object but, at svgfile starting execution time, my application is creshed....

and above all instruction are display in log window.

**Comment by akshay5993** [comment]
![sofan](https://cloud.githubusercontent.com/assets/10737063/5936673/e6bc66c0-a70c-11e4-8cd6-f6a3eb95f7bc.png)

I am working with this kind of svg(I have given you png of that) and it doesn't get loaded, infact it crashes in svgkimage.m with log 
DOESNT WORK, APPLE's API APPEARS BROKEN???? - About to mask layer frame ({{0, 0}, {729.31, 268.966}}) with a mask of frame ({{604, 22}, {158, 117}})
[SVGGradientElement] set gradient layer start = {1.1514591, 0.034577973}

the same above error is repeated many times in log.

is there anything wrong I am doing? should I use svgkfastimageview or layered? and layered imageview is crashing with this svg.

Is this kind of svg supported by svgkit? If yes how? Please instruct me.

Please help, thanks.

**Comment by adamgit** [comment]
That isn't the crash. Those are just standard warnings.

You need to find the cause of the crash - Xcode should pause on the crash
automatically. If not, your xcode is misconfigured and you'll need to
figure out how to breakpoint it on a crash. We need the stacktrace (info on
what line number has the crash, plus the error irself if there is one)

**Comment by akshay5993** [comment]
I am working on another application. will take your help later on.

Thank You.
