### ISSUE TITLE
After compiling the lib, what files are needed to import in another project

### ISSUE THREAD

**Issue by cutthis** [SVGKit/SVGKit#270]
I've created the libSVGKit-iOS.1.2.0.a but I don't have any entry headers to the library. Which are these?

Thanks.

**Comment by adamgit** [comment]
Do the install instructions on front page not work?

If they need updating for xcode6, please change the README file and submit 
a pull request.

**Comment by cutthis** [comment]
Hey,
I've created the library but I'm not sure how to use it in another project. I do have XCode 6, but besides copying the .a file, what headers are needed or I can import directly from the library something?

Thanks.

**Comment by Svantulden** [comment]
Like the step-by-step installation on the project page says at step 6:

```
6. Drag/drop the .a file and the "usr" folder into your project (select the "Copy files" checkbox)
```

The headers are in the usr folder you need to copy.

**Comment by cutthis** [comment]
I've read the instructions 9 times. Missed that point every time. Thanks for pointing it out.
