### ISSUE TITLE
Opacity attribute is ignored when using fill=url()

### ISSUE THREAD

**Issue by Anubis88** [SVGKit/SVGKit#272]
When the fill attribute is using a 'url' then the opacity attribute is ignored. Here is an example svg image to prove this. Opening with Safari (WebKit) displays fine but rendering with SVGKit gets a wrong result.

**Example SVG:**

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     width="212.6px" height="212.6px" viewBox="0 0 212.6 212.6" enable-background="new 0 0 212.6 212.6" xml:space="preserve">
<radialGradient id="SVGID_1_" cx="106.3" cy="106.3" r="106.3" gradientUnits="userSpaceOnUse">
    <stop  offset="0" style="stop-color:#FFFFFF"/>
    <stop  offset="1" style="stop-color:#000000"/>
</radialGradient>
<circle opacity="0.2" fill="url(#SVGID_1_)" cx="106.3" cy="106.3" r="106.3"/>
</svg>
```

**WebKit** (Correct rendering):
![webkit](https://cloud.githubusercontent.com/assets/11063221/6252442/a52b43ae-b79a-11e4-8ca9-750430595947.png)

**SVGKit** (Wrong rendering):
![svgkit](https://cloud.githubusercontent.com/assets/11063221/6252444/a9c79ed0-b79a-11e4-8900-85107310e609.png)

**Comment by Anubis88** [comment]
Just wondering if this issue could this issue be fixed. I'd really need it for my project.
Thanks in advance.

**Comment by adamgit** [comment]
If you need it, you're welcome to fix it, or offer to pay someone else to fix it if you don't have time.

Otherwise, it will wait until someone else decides it's more fun to fix a bug for you, than to work on their own project.

**Comment by Anubis88** [comment]
I'll just assume that you had a bad day, that's all. :)

I've fixed the issue. If you tell me how to commit the fix I'd like to contribute to the project. Thank you.

**Comment by MaddTheSane** [comment]
Fixes are usually done via pull requests: just fork the repository, pull your fork, commit your changes, push your changes to your fork, compare, create pull request.

**Comment by adamgit** [comment]
EDIT: what MTS said :)

Great. All you need do is:
1. Fork the project
2. Run the demo project and check your chnage hasn't broken any of the previously-working images
3. Commit to your fork
4. On the github page for your fork, there will be a big butotn at the top "submit pull request"

...and it's all automatic from there. Modulo one of the rest of us checking your source chagnes

**Comment by Anubis88** [comment]
Ok I just did, I hope it worked.

**Comment by adamgit** [comment]
Worked fine.

Would be great to get another pull request which adds your example file to the Demos project. That requires:
1. add it to the folder with the other SVGs
2. edit the Sample Licenses.txt to explicitly say its yours, and you're releasing it as public domain
3. edit the Demo project where it has a list of SVG filenames (I usually do a project-wide search for "monkey", it quickly finds the NSString array with all names), and add your new filename to the array.

**Comment by adamgit** [comment]
PS: Orta today recommended we try using FBSnapshotTestCase to do automated tests of all the sample SVGs. Looks like all we need to do is modify the Demos project to automatically zoom out/in each image when rendering (so it fits the available area), and add a dozen or so lines of code to trigger the automatic tests. Would be especially good for something like this where the "wrong" result looks almost "right"

**Comment by Anubis88** [comment]
Added demo file as requested.
