### ISSUE TITLE
Path data not parsed correctly (completely distorted)

### ISSUE THREAD

**Issue by Anubis88** [SVGKit/SVGKit#273]
These are two examples of red circles using just path data with a fill. They both render perfectly in WebKit but the second appears completely distorted. Some of the commands and parameters are clearly misinterpreted by the parser and therefore rendered as "distorted" path shapes:

**Correctly parsed by SVGKit**

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg id="Icons" xmlns="http://www.w3.org/2000/svg" xml:space="preserve" height="240px" viewBox="0 0 240 240" width="240px" version="1.1" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 240 240">
    <path fill="#f00" d="M120,238C54.9,238,2,185.1,2,120S54.9,2,120,2s118,52.9,118,118S185.1,238,120,238z"/>
</svg>
```

**Incorrectly parsed by SVGKit**

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg id="Icons" xmlns="http://www.w3.org/2000/svg" xml:space="preserve" height="240px" viewBox="0 0 240 240" width="240px" version="1.1" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 240 240">
    <path fill="#f00" d="m120 238c-65.1 0-118-52.9-118-118s52.9-118 118-118 118 52.9 118 118-52.9 118-118 118z"/>
</svg>
```

The second one was cleaned up with [Scrour](http://www.codedread.com/scour/).
Both examples use **valid path data** and conform to the [SVG File Format](http://www.w3.org/TR/SVG/paths.html).

_Would be great to fix this issue, thanks._

**Comment by adamgit** [comment]
If you want to improve the parser, you could probably make it handle these 
examples easily.

 The example you posted looks to me pretty nasty, albeit as you say legal. 
I'm surprised that anything would output such messy paths (it has very poor 
legibility).

Out of interest, is it scrour that's outputting that, or is it something 
even nastier that scrour is cleaning up?

**Comment by adamgit** [comment]
PS: scour is pretty interesting itself. Its a shame that it damages 
document structure - there's no need to do that, and it is a very bad thing 
IMHO. It would be interesting to reproduce some of scours behaviour in svgkit.

Svgkit doesnt do much cleaning right now, although sunple things around 
styles would provably be easy to add. But I've used svgkit to go a bit 
further and actually reduce the memory usage of the doc.

(Scour reduces text size, which isn't useful in most cases. Htmltidy and 
friends can do that almost as well. What's really useful with svg is 
reducing the render complexity - eg by simplifying paths)

**Comment by Anubis88** [comment]
Thanks for your quick answer. Unfortunately saving svg files from applications like Adobe Illustrator generates files two or three times as big with lots of unused elements and gibberish. If you work with a massive amountof different svg resources, cleaning them up manually turns impossible, that's why I use **scour**.
Although you are right, what it does is reduce the text size using less amount of data preserving the original shapes. It might not be the best way to draw paths but they are parsed fine on a Java library I'm using for Android, so I it would be good to parse them correctly on **SVGKit** too.

**Comment by adamgit** [comment]
Yep, agreed - AI generates terrible files. As mentioned, I've used HTML 
tidy tools in the past to fix it, they get rid of most of the cruft without 
altering structure.

**Comment by Anubis88** [comment]
Committed a fix for this bug.
