### ISSUE TITLE
Assertion in SVGLength? App crashes in apple app store review. 

### ISSUE THREAD

**Issue by andreasapptitude** [SVGKit/SVGKit#274]
Using SVGKit 1.20.0, my app is getting rejected from app store. If I managed to re-symbolicate the crash log correctly, the issue is an assertion in SVGLength - here's a stack track extract:

```
0   CoreFoundation                  0x1831da59c 0x1830b4000 + 1205660
1   libobjc.A.dylib                 0x193e340e4 0x193e2c000 + 32996
2   CoreFoundation                  0x1831da45c 0x1830b4000 + 1205340
3   Foundation                      0x1840614f4 0x183fb8000 + 693492
4   Robot                           0x100156ad0 +[SVGLength pixelsPerInchForCurrentDevice] (SVGLength.m:184)
5   Robot                           0x10015626c +[SVGLength initialize] (SVGLength.m:92)
```

It would appear that apple is testing with "devices" that are either too new for SVGLength, or somehow identify themselves differently - I don't experience the crashes myself.

For now, I will try to just run without assertions, but here's the heads up :)

Thanks for a cool library, I hope I will have a decent addition to the "apps that use SVGKit" soon!
- A

**Comment by adamgit** [comment]
You should always ship with assertions off! They are meant for during 
development only.

**Comment by adamgit** [comment]
That said, it would be great to ask them what they're testig  with and 
explain that we need to know the PPI to calculate correct values of pixels 
when an SVG is specified in inches.

Off the top of my head, they don't give us an API for this. Maybe if you 
prod them, they will start ;)

**Comment by andreasapptitude** [comment]
I flip-flop a bit on what assertions should _really_ be used for... Anyway, I will ask around, to see if they are willing to shed some light on their procedures :)

Again, awesome library - I have had a great time animating svg lately!

**Comment by andreasapptitude** [comment]
Well, prod or not - they don't reply... Worth a try though. The app has passed review, if interested goto  http://buzzybots.com
- A

**Comment by adamgit** [comment]
Add a link to the wiki page
