### ISSUE TITLE
MonoTouch Support

### ISSUE THREAD

**Issue by paulpatarinski** [SVGKit/SVGKit#275]
How can I get SVGKit working with Xamarin MonoTouch? I have taken a look at https://github.com/jamesmundy/SVGKit.Xamarin but it does not seem to build.

**Comment by adamgit** [comment]
Good luck to anyone trying this. To be clear: Xamarin is way outside 
expected usage of svgkit. I would recommend using c# svg libraries instead.

Last year, their sales people told me it was perfect and always worked with 
all iOS code "better than xcode". If they still.make those claims, then 
maybe its worth asking their tech support why its not working - there's 
nothing strange or magical about svgkit.
