### ISSUE TITLE
Can you please add XCode6 framework build target for this project?

### ISSUE THREAD

**Issue by GasimGasimzada** [SVGKit/SVGKit#283]
I am also trying to build this project as a Framework, which makes the integration so much cleaner. Currently, I am getting a weird error "Use of undeclared identifier 'ddLogLevel'"; so I am investigating. Will update this post, once I get this framework into a working condition. I would have wanted to make a pull request but there are information that I won't be able to commit (like Bundle Identifier etc).

**Comment by adamgit** [comment]
Do you need a new bundle identifier for making this a framework?

**Comment by GasimGasimzada** [comment]
AFAIK you do. I have already successfully compiled it. Importing the framework in the following way:

```
 import SVGKit 
```

Just makes it so much cleaner, with the framework being its own project. I will test it tonight and see if this works. And if it does, I will check to see if I can remove the bundle identifier from the project.

**Comment by GasimGasimzada** [comment]
I got it to work finally. Here are my options:

```
I got it to work finally. Here are my options:
Target Name: SVGKitFramework
Product Name: SVGKit // this one is important!
Other Linker Flags: -ObjC

// to match the the project settings:
Info.plist File: XCodeProjectData/SVGKitFramework/Info.plist
Prefix Header: XCodeProjectData/SVGKitFramework/SVGKitFramework.pch

Header Search Paths: added /usr/include/libxml2
Objective-C Automatic Reference Counting: NO

Compile Files: All 100 items
Link Binary with Libraries:
    QuartzCore.framework
    Foundation.framework
    CoreGraphics.framework
    libxml2.dylib
Header Files: All 128 items
```

And usage is very simple:
1. First add SVGKit Project as a sub project
2. Add these settings in Build Phases:
   
   Target Dependencies: Add SVGKitFramework
   Copy Files: Add SVGKit.framework
