### ISSUE TITLE
Embedded images cause a crash

### ISSUE THREAD

**Issue by BrandonZacharie** [SVGKit/SVGKit#292]
I have an SVG file with embedded images generated by [Adobe Illustrator](https://www.adobe.com/products/illustrator.html). Each base64 encoded `href` has line breaks after every 76 characters. These line breaks result in a crash. Below is a truncated example from the file I'm working with.

```
<image xlink:href="data:image/jpeg;base64,/9j/4AAQSkZJRgABAgECiQKJAAD/7AARRHVja3kAAQAEAAAAHgAA/+4AIUFkb2JlAGTAAAAAAQMA
EAMCAwYAADALAABptwAA1cT/2wCEABALCwsMCxAMDBAXDw0PFxsUEBAUGx8XFxcXFx8eFxoaGhoX
Hh4jJSclIx4vLzMzLy9AQEBAQEBAQEBAQEBAQEABEQ8PERMRFRISFRQRFBEUGhQWFhQaJhoaHBoa
...
```

In short, I see two issues here. Crashes; [this can be prevented by making sure `NSInputStream-initWithData` is not invoked with `nil`](https://github.com/SVGKit/SVGKit/blob/3d157a0cd1fd535be7609242c19d541aa9c32596/Source/Sources/SVGKSourceURL.m#L15). Invalid data URLs; [this can be fixed by removing invalid characters (i.e. line breaks) prior to invoking `NSURL+URLWithString` which will otherwise return `nil`](https://github.com/SVGKit/SVGKit/blob/5de23c041b8878858a19e0d6e57aca0cff023bcd/Source/DOM%20classes/Unported%20or%20Partial%20DOM/SVGImageElement.m#L88);

**Comment by adamgit** [comment]
Is it legal for the base64 data to contain line-breaks?

(I mean: does the relevant RFC allow for it)

If so ... we should filter them out.

If not ... let's add an Adobe-specific Assert along the lines "illegal Adobe file detected" and then deal with it. As an assert, it'll disappear in production, but during testing you'll get the warning that the SVG itself is probably bad.

**Comment by adamgit** [comment]
The NSInputStream class is clearly anaemic: Apple neglected to implement quite a few core features there.

So, IMHO ... we should handle the nil NSData ourselves. However, again, we should be raising an assert on that (it really shouldn't happen!).

Personally, I'd like to see a way for every SVGKSource class to say "here's the NSError's I encountered while attempting to get up and running" -- c.f. the SVGKParser class and subclasses and extensions, which report on "why" the SVG failed to parse.

**Comment by BrandonZacharie** [comment]
I agree. I'll take a look at the RFC and report back here.

**Comment by adamgit** [comment]
Is this fixed now with @greghe 's commit?

**Comment by BrandonZacharie** [comment]
With that commit, white space is removed. It solves my immediate issue so I vote to close this issue. However, a crash will still occur as mentioned.

**Comment by adamgit** [comment]
I don't believe a crash will occur.

**Comment by BrandonZacharie** [comment]
Invoking `NSInputStream-initWithData` with `nil` will throw. I updated the links in my original comments to point to the lines in the repository history I referenced. I see things have changed since so I can't say for sure there is still an issue.

**Comment by adamgit** [comment]
But we no longer have a situation where that can happen? I refactored to move everything through a single method that has a nil guard to prevent this. I'm hoping it's working as intended?
