### ISSUE TITLE
Cascade attributes defined by the 'g' element to its children

### ISSUE THREAD

**Issue by mattrajca** [SVGKit/SVGKit#3]
Necessary to get the 'Lion' sample working...

**Comment by ahti** [comment]
Can You give any estimate on how long it will take You to implement cascading and transforms?

**Comment by adamgit** [comment]
This has been implemented in one of the forks - I think the code is in main, but not enalbed by default?

**Comment by adamgit** [comment]
The 2013base branch now has partial support for cascading - the code is there, but only the "common" cascadeable items have been hooked up.
