### ISSUE TITLE
Build success but missing headers

### ISSUE THREAD

**Issue by Dino4674** [SVGKit/SVGKit#30]
I've already opened [issue](https://github.com/reklis/SVGKit/issues/19) on reklis's fork before and had no luck building.

I told my friend to try and he gets the same result as me.

Both of us followed REDME on this page.

Both of us use XCode 4.5.1.

He gets "build" folder in derived data folder, I get "build" folder in project root folder.

Bot of us get .a library file and usr/.... with headers.

After copying .a and .h files to the new project and importing SVGDocument.h, error appears on missing header "SVGStyleCatcher.h".

I looks like this header is slipping somewhere in building process (this happens on both computers, mine and my friend's).

**Comment by adamgit** [comment]
Next major update will be a merge of this fork: https://github.com/adamgit/SVGKit/

Try that, should build better (lots of old code has been removed, and the project files have been regenerated with latest Xcode, because Xcode has problems with backwards compatibility :( )

**Comment by Dino4674** [comment]
I cloned yours repo and I have the same erros as in [this issue](https://github.com/adamgit/SVGKit/issues/13)

What are the exact steps to build SVGKit library from yours repo? Thanks.

**Comment by adamgit** [comment]
That appears to be an Xcode bug. The solution is in the thread you linked - add two import lines to CALayerExporter header (one for UIKit, one for QuartzCore)

**Comment by Dino4674** [comment]
Adam, I've buit yours library:
1. I added those two imports and I get .a and usr folder (in project/build folder). Shouldn't this be in derived data?
2. Here is my sample code:

```
#import "ViewController.h"
#import "SVGKImageView.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.

    [self.view addSubview: [[SVGKImageView alloc] initWithSVGKImage: [SVGKImage imageNamed:@"Lion.svg"]]];
}

@end

```

And I get an error in SVGKit.h:

![error](http://www.pohrani.com/f/2Y/Tz/2ehzMhSD/screen-shot-2012-10-23-a.png)

Am I doing something wrong?
I just cloned yours repo. Should I init those submodules also?

**Comment by Dino4674** [comment]
```
#import "SVGDefsElement.h file not found"
```

is the error I get after clean build (added two imports before, UIKit and QuartzCore)

What is the problem here?

**Comment by adamgit** [comment]
Bug in Xcode 4 - it puts header files as "protected" by default, instead of
"public" (which is the correct default). I'm not sure why Xcode was
building the project fine for me even without that header :(

I've moved the headers from protected to public, should work now.

(transforms branch)

**Comment by Dino4674** [comment]
OK, definitely a progress but after clean build I drag&drop headers and .a file and now I get this error:

![error](http://www.pohrani.com/f/1F/OU/3dlLbsza/screen-shot-2012-11-04-a.png)

This looks like a build settings issue (?)

I added libxml2.dylib framework.
Also, if I remove -ObjC in "Other linker flags" I get "only" five errors, not seven like on attached image.

**Comment by Dino4674** [comment]
I needed to add QuartzCore framework also.
BTW, this is how Lion.svg is rendered:

![lion](http://www.pohrani.com/f/4/XK/2piqdwP3/screen-shot-2012-11-04-a.png)

**Comment by adamgit** [comment]
Yes, you need to include ALL the frameworks and libs from the install instructions ;).

Lion.svg uses Styles, which weren't supported when I forked - the code is there, but for some reason its disabled. I believe they're now enabled in main SVGKit?, I'm waiting for someone to successfully merge my fork, then we can check and re-enable if necessary.
