### ISSUE TITLE
path is not rendered

### ISSUE THREAD

**Issue by GeraudBourdin** [SVGKit/SVGKit#302]
I don't know why and how to fix this but this svg path isn't rendered. It show well in a browser. Am i missing something ?

```
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" width="593" height="200" version="1.0" id="ezcGraph">
    <path d="M 2.50,101.00 L 378.40,101.00 A 81.90,57.52 0 0,1 283.45,157.78 Z" style="fill:#000000;" id="ezcGraphCircleSector_51"/>
</svg>
```

Best regards

**Comment by adamgit** [comment]
Check the log file.

**Comment by adamgit** [comment]
I mean: look at the console log. Should be your first step, always.

**Comment by GeraudBourdin** [comment]
Log file do not show anything. That's why i posted the svg code here.

**Comment by adamgit** [comment]
When I run your SVG, I get a specific error message on the console, which
explains why this isn't rendering.

**Comment by greghe** [comment]
The issue is the "A" path command is not supported. It's a tricky command to support, since there is no direct analog in Core Graphics.

**Comment by GeraudBourdin** [comment]
I run it as a titanium appcelerator module so logs was hidden. Sorry for that. 
Thanks for your answers. Hope this will be fixed one day as some libs in android handle it very well that would be great to see that on ios. 
Best regards.

**Comment by adamgit** [comment]
Ouch. That's a pain with Titanium :(.

If you have ideas on implementing it, go for it. I don't really understand
the A command. I suspect there's some way of calculating it quite easily
using existing maths libraries, and approximating a curve using straight
lines? But that's outside my exprience.

(and ... I've never seen an SVG so far that actually uses this command!)

**Comment by GeraudBourdin** [comment]
As i see in the svg 1.1 spec A and a is design for drawing an arc path : 
Draws an elliptical arc from the current point to (x, y). The size and orientation of the ellipse are defined by two radii (rx, ry) and an x-axis-rotation, which indicates how the ellipse as a whole is rotated relative to the current coordinate system. The center (cx, cy) of the ellipse is calculated automatically to satisfy the constraints imposed by the other parameters. large-arc-flag and sweep-flag contribute to the automatic calculations and help determine how the arc is drawn.

no way to draw arc with core graphics ?

**Comment by adamgit** [comment]
Apple never implemented ELLIPTICAL arcs, IIRC. Only circular ones.

I guess they thought "well, you could simply scale a circle to make an
ellipse".

I guess SVG is afraid you'd be forced to do lots of scale transforms if you
have a path with many ellipses, but that seems a super-rare use-case, and
anyway begs that Path get an internal transform mechanic ... IMHO a cleaner
solution.

**Comment by greghe** [comment]
I have the A command (mostly) working. Supporting rotations is all I have left to do. Hopefully I can finish it this weekend. 

#303

**Comment by GeraudBourdin** [comment]
Wow you did it fast ! Thanks a lot ! Very impressive. Have a nice weekend :)

**Comment by GeraudBourdin** [comment]
Hi, i am trying this feature (sorry for my late reply i didn't have access to my mac so i couldn't test it). 
It seems to render but only lines, i mean there is no curves at all. Am i missing something  ? I test with the .svg provided in the pull request's thread (#303).

**Comment by adamgit** [comment]
arcs01 and arcs02 are working fine. I test everything before accepting people's pull requests. If it's in, it worked.

If they don't work for you, we need a lot more information - c.f. writing a good issue http://t-machine.org/index.php/2013/12/22/reporting-issues-in-open-source-software/

**Comment by adamgit** [comment]
i.e. ios version, device, app, filename, what happened when you looked in the debugger, etc.

**Comment by GeraudBourdin** [comment]
Hi, sorry for wasting your time :/ I think the real problem is between my chair... and my computer.
I have tested with your real life example IOS App. And with a complex svg file (a pie chart) it looks perfect ! 
My problem is that i trying to use your great lib in a Titanium ios module to give access to this lib to appcelerator. Now, i understand that i have a real problem: your IOS app test render perfectly some svg that my "bridged" module that include your lib don't (like the smiley svg, gradient isn't render).

For now, i'am trying to reading and understand your IOS app code to learn how i need to use it. I guess, this challenge is too big for a beginner, but that's how i like to learn. 

Sorry guys, your lib works perfectly and the real problem is on my side. 
Have a nice day.

**Comment by adamgit** [comment]
No worries - just be careful to test with the demo app whenever reporting 
problems (that's what its there for! to make sure we have a common 
reference point)

When sth works in demo, but not in your code, you can/should use the soirce 
- settjngs of the demo project to help you figure out why your project is 
  failing.

That said ... there should be NOTHING that prevents this working find in 
Titanium. Perhaps go through the app settings and NIB files and double 
check everything is the same. Its bizarre that its partly working. maybe go 
through and check the other SVGs to see if any work?

**Comment by GeraudBourdin** [comment]
I guess, sometimes some words can be really good help. You are right, specially when you say "Its bizarre that its partly working"... That was a Titanium issue. I needed to manually delete generated files before launching their automated build.py file... Now all is working perfectly. 
Here is my test file (if you want to test it, it is a generated pie graph by the php lib ezcgraph ) : http://bourdin.name/pieChart.svg

The smiley svg works well too. Once again, thank you very much for the help, your lib and your really quick PR. I guess, this issue can be closed, as on my side, path are now perfectly rendered.
