### ISSUE TITLE
Error loading source file

### ISSUE THREAD

**Issue by d2ns** [SVGKit/SVGKit#310]
in  SVGImage.m line 106
wrong: SVGKSource\* source = [self internalSourceAnywhereInBundleUsingName:name];
correct: SVGKSource\* source = [SVGKSourceLocalFile internalSourceAnywhereInBundleUsingName:name];

**Comment by adamgit** [comment]
Please submit a pull request. I cannot change this - xcode won't run (using latest xcode 6.3 from last week, it seems broken) - and it may be days before I can downgrade.

I don't know how this got past testing - should have broken the build immediately?

**Comment by adamgit** [comment]
Fixed now.
