### ISSUE TITLE
Can not work with svg files created with Affinity Designer 1.2

### ISSUE THREAD

**Issue by d2ns** [SVGKit/SVGKit#311]
(SVGKImage *)imageNamed:(NSString *)name; only works with svg files containing:
<svg width="59px" height="51px" version="1.1" ...

since update to 1.2 Affinity Designer exports svg files containing:
<svg width="100%" height="100%" viewBox="0 0 57 49" version="1.1" ...

This results in SVGKImages having no content. The parser needs to convert the viewBox to absolut width and height in px

**Comment by adamgit** [comment]
SVG doesn't work like that. "100%" has almost zero meaning in this context.

But ... latest commits explicitly added workarounds for software that does this width=100% thing. Works fine.

So ... As per the instructions you should have seen when opening the issue (they were at the top of the page - if that's too subtle, please complain to github.com!), we'll need a lot more info than this.
