### ISSUE TITLE
SVG text elelment

### ISSUE THREAD

**Issue by hirpatel** [SVGKit/SVGKit#32]
Hi..

its can't rendering my svgtext within my svg file.

please give me any solution for rendering text element of svg.

**Comment by adamgit** [comment]
I think reklis was working on Text support but I have no idea of the current status, sorry. You could try looking at reklis's fork, and/or contacint him directly:

https://github.com/reklis/SVGKit

**Comment by adamgit** [comment]
Basic SVG Text now works in the 2013base branch. Fancy styles are NOT supported, although it would be trivial for you to add if you needed them (look in the file SVGTextElement, there's very little code to look at)
