### ISSUE TITLE
zoom not working for monkey.svg

### ISSUE THREAD

**Issue by liuxuan30** [SVGKit/SVGKit#322]
The main page is saying "Zoom, pan, and (with the Monkey only:) hit the "Animate" button"

However I don't see any zoom effect for the monkey svg, no matter how many times I hit animation button.

Could someone help?

Currently, I want to use SVGKit to render map and can zoom, scroll, and render with different color when selected some parts of the map.

**Comment by adamgit** [comment]
The animate button animates.

Zoom is implemented by apple, using their built-in UIScrollView.

I think the demo has zooming disabled in code at the moment - this is not
SVGKit, it's Apple classses, so if you make your own app, Zooming should
work as expected.

**Comment by liuxuan30** [comment]
But what will happen when clicking animate button, on my side, I see nothing happens or animates.

**Comment by adamgit** [comment]
The demo uses the filename to decide what to do when you press the button.
Use the debugger to see for yourself exactly what happens. Recent updates
have changed the way that we pass-around the "filename of current file" - I
suspect there is some code that is trying to compare a string against what
is now an SVGKSource (it used to be a string too).

The monkey's head should wobble.

**Comment by jaouahbi** [comment]
For Zoom.

- (UIView *)viewForZoomingInScrollView:(UIScrollView *)scrollView{
    
    return self.contentSVGView;
}
- (void)scrollViewDidEndZooming:(UIScrollView *)scrollView
                       withView:(UIView *)view
                        atScale:(CGFloat)scale
{
  // 1 set the new scale for the SVG (self.document.scale)
  // 2 reload the SVG with the scale (...)
}
