### ISSUE TITLE
2.x support iOS8 with ARC enabled apps?

### ISSUE THREAD

**Issue by liuxuan30** [SVGKit/SVGKit#323]
Sorry I had to open this issue more like a Q&A, because our project now wants to use SVGKit to render maps. I am also new to SVG world.

Our app now supports iOS 7, 8 and above. I notice that 2.x branch is still not converted to ARC? If I use 2.x version of SVGKit, will it has any potential crashes/bug on apps that is managed by ARC? 

Someone said the 'master-arc' branch has lots of changes compared to the "official" branch, and I don't want weird bugs for those "changes" in arc branch.

Could someone help clean up the questions?

**Comment by adamgit** [comment]
ARC projects should work fine with non-ARC libraries - that was Apple's
guarantee (IIRC).

You could manually upgrade the main 2.x branch to ARC (Xcode has a built-in
feature for doing this). If it works, and nothing breaks, submit a
pull-request and we will merge it into 2.x and make it ARC going forwards.

**Comment by liuxuan30** [comment]
I see. Thanks
