### ISSUE TITLE
Does this library has stable version, that I can use for production?

### ISSUE THREAD

**Issue by ghost** [SVGKit/SVGKit#327]
Does this library has stable version, that I can use for production?

Even demo app dosen't work without tricks?

**Comment by adamgit** [comment]
As per the guidelines you were presented when writing your issue:
1. It works fine for everyone else. If it doesn't work for you, you REALLY need to explain clearly and in detail exactly how and why.
2. Many of us use 2.x in production, it's recommended
3. If you want something that's not changing, the releases page (linked to from front page) has several you can choose from
