### ISSUE TITLE
Performance issue while rewriting handlePinch for zooming, any better ways?

### ISSUE THREAD

**Issue by liuxuan30** [SVGKit/SVGKit#328]
I draw a svg map using SVGKit, and I embed the SVG UIView into a UIScrollView, and enabling zooming and scrolling feature with UIScrollView.

I rewrite the UIScrollView pinch gesture aciton handler:

``` Objective-C
// in my custom UIScrollView.m:
- (void)handlePinch:(UIPinchGestureRecognizer *)pinch {
    CGFloat scaleToZoom;
    if (pinch.scale > 1 && self.zoomScale == self.maximumZoomScale)
        return;
    if (pinch.scale > 1) {
        scaleToZoom = pinch.scale;
        scaleToZoom = MIN(self.maximumZoomScale, scaleToZoom);
    } else {
        scaleToZoom = self.zoomScale * pinch.scale;
        scaleToZoom = MAX(self.minimumZoomScale, scaleToZoom);
    }
    [self setZoomScale:scaleToZoom animated:YES];
}
```

The purpose of the code is to avoid some strange behaviour after it reaches maximum zoom scale of minimum one.

However, It is not as smooth as the system `handlePinch` implementation. I don't know how Apple implement `handlePinch`, any ideas?

**Comment by seltzered** [comment]
I'm honestly clueless about using views within scrollviews, but just to throw my 2 cents in...

1) Are you using SVGKLayeredView so that core animation is supported?
2) Another method would be to resize by performing the zoom with the SVGKLayer via setAffineTransform/CGAffineTransformMakeScale and setPosition (you could use setFrame but you're potentially throwing away any ongoing animation). 

You may also want to check the SVGKit demo project - there might be a zooming demo in there.

**Comment by liuxuan30** [comment]
Yeah I am using the multi layer view. UISCrollView's `setZoomScale` did not use CGAffineTransform? I make the assumption, `setZoomScale` is using CGAffineTransform underlyingly.

**Comment by adamgit** [comment]
I've never been able to reproduce Apples implementation cleanly.

I think Apple does something internal, like disabling all rendering which 
zooming.

There is NO REASON why zooming should be slow, but Apple makes it slow. I 
suspect it is some coding optimization left over from iOS version 2.0 that 
they never fixed.

There are ways to do what apple does, eg you can freeze and resume CA  
rendering, or use OpenGL to do ultra fast zooming, but you have to do a lot 
of reading about the Apple APIs on how to do that.

**Comment by liuxuan30** [comment]
I see. Now I have revert back to system handler, and try to work around from there. The system implementation is quite smooth...

**Comment by lastMove** [comment]
Hi,
You said that "The purpose of the code is to avoid some strange behaviour after it reaches maximum zoom scale of minimum one.". Which Behavior did you have?
I am using zooming within my application (with pinchToZoom) and it works smoothly

**Comment by seltzered** [comment]
One other thing to maybe consider is making the layer "setRasterize:YES" when the pinch gesture starts and "setRasterize:NO" at the end of the gesture. this may help performance in a way similar to how preview.app makes things kinda pixelated (which is the tradeoff with this) when zooming into things then re-renders at the end.

**Comment by liuxuan30** [comment]
@lastMove As you can see my demo code, I mistakenly overwride the system `handlePinch`, and after it reaches maximum zoom scale, say 3, if you pinch again, `pinch.scale` will be 1, so some of my code will use this 1 value to zoom, and that starts the odds. I think I misunderstood how pinch scale works and the way I handle it. But the true difference is `[self setZoomScale:scaleToZoom animated:YES];` slower than the default implementation inside `handlePinch`. I am not sure if switch off animated could help. Anyway, I have changed back to system one, and it seems working great now.

**Comment by MapXL** [comment]
Hello everyone,

I am trying to add maps using SVGKIT. I am debugging the sample code. I replaced rainbow image with the map image. It is not zooming at all. Also, the countries name in the map are getting removed after zooming. No clue or code for zooming. Please help.
