### ISSUE TITLE
Adding new element from string to existing SVG-Image

### ISSUE THREAD

**Issue by alaija** [SVGKit/SVGKit#329]
I got confused...

I have SVGKLayeredImageView displays SVGKImage. Now I got new SVG-element that I want add to existing SVGKImage, how I can implement this?

```
NSString *sourceString = @"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"1000\" height=\"500\"></svg>";
SVGKImage *image = [[SVGKImage alloc] initWithSource:[SVGKSourceString sourceFromContentsOfString:sourceString]];
SVGKLayeredImageView *imageView = [[SVGKLayeredImageView alloc] initWithSVGKImage:image];
[self.view addSubview:imageView];

//  Element that I want to add to 'image' and display on 'imageView'
NSString *newElement = @"<rect id=\"superId\" width=\"100\" height=\"100\" x=\"0\" y=\"0\" fill = \"#3333\" fill-opacity = \"1\"/>";
```

**Comment by adamgit** [comment]
SVGKit currently only renders SVG's.

You're asking to render "a piece of of an SVG, that is not an SVG itself".
SVGKit can't do that.

What you _can_ do is:
1. Load your SVG as an SVGKImage ... add the Rect node in correct place on
   the tree of SVGElement's (I think you create an SVGRect instance) ... then
   tell SVGKit to re-draw the image (using [image newCALayer])

or
1. Create Apple rendering commands for your rect - e.g. "new CALayer" +
   "layer.backgroundColor = XXX" ... etc

or
1. Make a new SVG file as an NSString, that is empty apart from your new
   code. This must be a legal SVG file - must be wrapped in an "svg" tag etc.
   Then you render this as a second SVGKImage, and draw it on-screen over the
   top of your original SVGKImage.

**Comment by alaija** [comment]
Thanks, first method works for me.
