### ISSUE TITLE
SVGImageElement don't parse images with "https:" prefix

### ISSUE THREAD

**Issue by alaija** [SVGKit/SVGKit#330]
... cause SVGImageElement.m line 92 , should be:

```
if ([_href hasPrefix:@"http:"] || [_href hasPrefix:@"https:"])
```

instead

```
if ([_href hasPrefix:@"http:"] )
```

or just need to check prefix without semi-colon.

**Comment by adamgit** [comment]
Yep. Submit a pull request, and I'll approve it.
