### ISSUE TITLE
iphone 6+ not support. When we do fix it?

### ISSUE THREAD

**Issue by mefilt** [SVGKit/SVGKit#332]
iphone 6+ not support. When we do fix it?
    if( [platform hasPrefix:@"iPhone"]) // catch-all for higher-end devices not yet existing
    {
        NSAssert(FALSE, @"Not supported yet: you are using an iPhone that didn't exist when this code was written, we have no idea what the pixel count per inch is!");
        return 326.0f;
    }

**Comment by adamgit** [comment]
If you calculate the PPI and add the necessary "if ... then" bit above, it
will work fine.

Please submit a Pull Reuqest and I'll merge it.

(NB: this doesn't affect your apps on the app store - it only affects you
during development)
