### ISSUE TITLE
monkey.svg does not shake head

### ISSUE THREAD

**Issue by ChenWuLin** [SVGKit/SVGKit#333]
I thought [self.sourceOfCurrentDocument.keyForAppleDictionaries isString:@"Monkey"]  never be true. may be you want [self.sourceOfCurrentDocument.keyForAppleDictionaries containsString:@"Monkey"].

however the CABasicAnimation doesn't work also.

**Comment by ChenWuLin** [comment]
my svgkit demo version is 2.x  downloaded yesterday

**Comment by alexandre-g** [comment]
need to change it in two places in DetailViewController.m to fix:
Change:
`if ([self.sourceOfCurrentDocument.keyForAppleDictionaries isEqualToString:@"Monkey"]) {`
to `if ([self.sourceOfCurrentDocument.keyForAppleDictionaries rangeOfString:@"/Monkey.svg"].location != NSNotFound) {`

and likewise for: `if ([options.localFileSource.filePath isEqualToString:@"Monkey"]`

**Comment by adamgit** [comment]
Please check out the git project, make the change, commit, and do a pull
request (use the button on website, it will do it automatically)
