### ISSUE TITLE
does SVGKit support <animation>  tag now?

### ISSUE THREAD

**Issue by ChenWuLin** [SVGKit/SVGKit#335]

**Comment by lastMove** [comment]
No

**Comment by adamgit** [comment]
Most people are using Apple's CALayer / Quartz / CoreAnimation library for animation - this is much more powerful than SVGKit, and a lot easier to use.

NB: currently there are no standard SVG editing applications that support svg animation! There are some commercial-only ones, but they are unreliable. Support for SVG animation is currently rare.

**Comment by ChenWuLin** [comment]
Thank you all
