### ISSUE TITLE
Why SVGKImage CALayerTree get {-1.5, -1.5} position?

### ISSUE THREAD

**Issue by alaija** [SVGKit/SVGKit#336]
Hey, I have a problem, when I write:

```
{
...
imageView = [[SVGKLayeredImageView alloc] initWithSVGKImage:[self cleanWhiteBoardWithSize]];
NSLog(@"%f, %f", imageView.image.CALayerTree.x, imageView.image.CALayerTree.y);
...
}

- (SVGKImage *)cleanWhiteBoardWithSize
{
    CGSize localSize =  CGSizeMake(1000, 1000);
    NSString *content = [NSString stringWithFormat:@"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 %.f %.f\"></svg>", localSize.width, localSize.height];
    return [[SVGKImage alloc] initWithSource:[SVGKSourceString sourceFromContentsOfString:content]];
}
```

I expect it will output "0, 0" to console, but I get "-1.5, -1.5".

Can you explain why it happen?

**Comment by adamgit** [comment]
That's strange.

Use the debugger and check what is setting the .x and .y variables.

Also try hardcoding the string - don't use %f - it might be that something
funny is happening in the string conversion.

**Comment by alaija** [comment]
"SVGSVGElement.m" lines 257:269

```
- (CALayer *) newLayer
{

    CALayer* _layer = [[CALayerWithChildHitTest layer] retain];

    [SVGHelperUtilities configureCALayer:_layer usingElement:self];

    /** <SVG> tags know exactly what size/shape their layer needs to be - it's explicit in their width + height attributes! */
    CGRect newBoundsFromSVGTag = CGRectFromSVGRect( self.viewport );
    _layer.frame = newBoundsFromSVGTag; // assign to FRAME, not to BOUNDS: Apple has some weird bugs where for particular numeric values (!) assignment to bounds will cause the origin to jump away from (0,0)!

    return _layer;
}
```

I spent a little time for research, and found that happens on frame update when viewport is equal to SVGRectUninitialized(). Do we really want to update frame, in this case?

Do we really want use frame? As you mentioned at "CALayer+RecursiveClone.m" line 33 comment: "According to Apple's docs, it's officially unsupported for writes".

p.s. I have not much experiences with Layers, so I can't answer to my questions by myself.

**Comment by adamgit** [comment]
Maybe if you:
1. save the origin (layer.center? layer.origin? I can't rmember)
2. overwrite _layer.bounds
3. restore the origin you saved in 1 above

...if this works, we could stop writing to .frame
