### ISSUE TITLE
SVGKImage not releasing

### ISSUE THREAD

**Issue by Wiesman** [SVGKit/SVGKit#337]
I'm trying to implement a thumbnail screen in iOS for a bunch of SVG images, but I quickly run out of memory. To make the thumbnails, I do something like this:

SVGKImage *svg = [SVGKImage imageNamed:filename];

UIImage *img = [svg UIImage];
svg = nil;
img = [img imageByScalingToSize:CGSizeMake(32, 32)];

Even though I'm setting the svg reference to nil, the app never seems to free the memory and I run out. I know that 1.2 doesn't use ARC (my project does). Is there a way for me to force the svg to be unloaded? 

I've confirmed that the memory being used by the thumbnail UIImage is very small and not the problem.

**Comment by adamgit** [comment]
You're welcome to convert the 2.x branch to ARC. So long as there's no
other changes, and it builds correctly with no new crashes / errors, I'd
happily integrate a pull request for that.

(the main contributors agreed that 1.x would be the last non-ARC branches,
but it's been over a year and it seems no-one's loved ARC enough to do the
conversion + debug it!)

**Comment by adamgit** [comment]
Now converted to ARC on main. No reported leaks (from Xcode analyser). I'm assuming this is now fixed
