### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ddustin** [SVGKit/SVGKit#34]
If you use SVGKit on a bunch of SVG's it eventually starts leaking.

The worst problem is that gradients cause a huge leak. If you disable gradients the library works for a lot longer but still runs out of memory after loading enough.

Is anyone else aware of this or working on it? In diagnosing the issue I spotted a lot of comments in the same sections of code about the memory issues.

I have a branch that disables gradients:
https://github.com/ddustin/SVGKit

**Comment by adamgit** [comment]
If you switch to my fork:

   https://github.com/adamgit/SVGKit/

I can help with this (this fork will - soon - overwrite the main SVGKit).

But the main project is now so far behind that I don't want to get into "deep" problems like memory leaks.

(NB: on my fork, gradients are off by default; you might need to copy/paste the gradient code from master - and then I can look at it and try fixing it up)

**Comment by adamgit** [comment]
That fork is now merged as the branch "2013base" please try there.

**Comment by ddustin** [comment]
The biggest memory leak is that parent's retain children and children
retain parents. Change it to assign and it's fixed.

**Comment by adamgit** [comment]
I'm afraid you'll have to be more specific - I ran clang just now, and
found zero leaks that you describe.

(I've pushed latest with all clang-errors fixed, to be sure)

**Comment by ddustin** [comment]
https://github.com/ddustin/SVGKit/commit/cacd53e5fef17c845e0d4d85ceda9733b4c556e8

**Comment by adamgit** [comment]
OK, thanks. I've reproduced that as best I can in the 2013 branch (there's a lot more variables now in Node) :

https://github.com/SVGKit/SVGKit/commit/22bb2a14011988ac56e81e3988f4cb7097fc209f
