### ISSUE TITLE
Saving to disk an SVGKImage loaded from URL.

### ISSUE THREAD

**Issue by dani-mp** [SVGKit/SVGKit#341]
Hi.

I'm trying to write to disk an `SVGKImage` loaded from a URL. My idea is to make some attribute changes (change color) before save it, but I receive a crash when using `appendXMLToString`. The crash is:

```
Found a namespace (http://www.w3.org/XML/1998/namespace) in node (svg) which wasn't listed in the KNOWN namespaces you provided (<CFBasicHash 0x608000463980 [0x7fff7cbe4ed0]>{type = immutable dict, count = 2,
entries =>
    0 : <CFString 0x6080000546d0 [0x7fff7cbe4ed0]>{contents = "http://www.w3.org/1999/xlink"} = xlink
    1 : <CFString 0x608000250a10 [0x7fff7cbe4ed0]>{contents = "http://www.w3.org/2000/svg"} = <CFString 0x7fff7baffd00 [0x7fff7cbe4ed0]>{contents = ""}
}
); you MUST provide a COMPLETE list of known-namespaces to this method
```

This is the code that I'm using to try to accomplish this:

``` swift
// Load the image and change color.
let urlImage = NSURL(string: "https://valid-file-from-internet.svg")
let image = SVGKImage(contentsOfURL: urlImage)
colorElement(image.DOMTree, color: NSColor.redColor()) // Change the fill attribute recursively.
image.newCALayerTree()
self.imageView.image = image // Here the image is shown correctly with the color changed.
// Write to disk.
let ms = NSMutableString()
let allNamespaces = image.DOMDocument.allPrefixesByNamespaceNormalized as Dictionary<NSObject, AnyObject>
ms.appendString("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n")
image.DOMDocument.rootElement.appendXMLToString(ms, availableNamespaces: allNamespaces, activeNamespaces: NSMutableDictionary()) // The crash happens here :(
let data = image.exportNSDataAntiAliased(true, curveFlatnessFactor: 1.0, interpolationQuality: kCGInterpolationDefault, flipYaxis: false)
let url = NSFileManager.defaultManager().URLForDirectory(NSSearchPathDirectory.CachesDirectory, inDomain: NSSearchPathDomainMask.UserDomainMask, appropriateForURL: nil, create: true, error: nil)?.URLByAppendingPathComponent("test.svg")data.writeToURL(url!, atomically: false)
```

To make sure that the problem wasn't related with the changing of the color, I've commented out that lines as well, and the crash still happens.

Do you have any clue that what could be happening?

**Comment by adamgit** [comment]
I'm maybe misunderstanding, but it looks as though:
- The error is saying you've added a tag with no namespace.
- In your code, you added a tag with no namespace.

What happens if you change your code to include a namespace? (off the top
of my head: your xml tag is invalid; I thought all XML docs required
namespaces?)

**Comment by dani-mp** [comment]
Thanks for your reply. Do you mean the wrong line is:

```
ms.appendString("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n")
```

I tried to replicate the code I saw here: http://t-machine.org/index.php/2013/11/17/svgkit-programmatic-editing-of-svg-files-on-ios/, and I copied that.

**Comment by adamgit** [comment]
Hmm. Well, that code used to work, so ... yeah, it looks like something
strange is happening here :(.

I suggest you use the debugger and find out what line of code is crashing,
and what it was expecting, but lacked, and why.

**Comment by dani-mp** [comment]
Yeah, the line that is crashing is

``` swift
image.DOMDocument.rootElement.appendXMLToString(ms, availableNamespaces: allNamespaces, activeNamespaces: NSMutableDictionary())
```

when I list the namespaces after retrieving them using `allPrefixesByNamespaceNormalized` I don't get the one that it seems that after appears when perform the line above.

**Comment by adamgit** [comment]
No, that's not the line. That's a method that calls code that ... calls
code that ... causes the crash. Use your debugger and find out what ACTUAL
line is going wrong! Find the words that provide the error message. All the
source is included in the projct.
