### ISSUE TITLE
It looks we cannot publish apps to app store with adding libxmyl2.2.dylib to linked binaries

### ISSUE THREAD

**Issue by ColinUNC** [SVGKit/SVGKit#346]
libxmyl2.2.dylib

**Comment by adamgit** [comment]
Do you have a docs URL  / announ ent from Apple about this?

**Comment by ColinUNC** [comment]
http://stackoverflow.com/questions/27809352/are-ios-8-apps-with-embedded-dylibs-allowed-on-the-app-store

**Comment by adamgit** [comment]
That's something different - you're not allowed to link your OWN dylibs 
(never been allowed to - although you sort of can now, with son limitations).

But libxml isn't ours - it's Apple's - so that's always been allowed.

I don't think this will.change?

**Comment by MaddTheSane** [comment]
There is a libXML provided by the system. I can see if there’s a problem with a third-party dylib, but it is provided by Apple itself…

**Comment by greghe** [comment]
You also shouldn't specify a library version beyond the "2". So you really should link in 

libxml2.dylib

which is a symbolic link to the current version (be it 2.2 or otherwise).

**Comment by adamgit** [comment]
Its a somewhat buggy and unmaintained library (the one apple links at 
least) IMHO - I'd rather stick to a known version and be confident it has 
the bugs we know :)

**Comment by greghe** [comment]
The problem with that approach is that if version 2.2 is not on the device, the app will not launch.

**Comment by adamgit** [comment]
If version 2.2. is not on the device, then we've never tested with it, and
it's not guaranteed / expected to work anyway.

The linking is done by the developer, not by SVGKit itself, so ... if you
are shipping an app you don't expect to / can't update (ever), you can
easily choose to link 2 instead, no?

**Comment by adamgit** [comment]
(if libxml didn't have such huge holes in missing code, major bugs ... I'd
be less concerned. Or if we were dynamically linking in an environment
where the available libraries changed often, I'd be more keen on generic
version numbers. But Apple very very rarely updates their libs.)

**Comment by greghe** [comment]
Yes, the linking is specified by the app, not the framework (unless the framework is packaged as a dynamic library). And yes, a library like xml2 is unlikely to change versions in the future. Nevertheless, if version 2.2 is not present that would mean it has been replaced by a newer version which is backward compatible with all earlier 2.x versions. 

For anyone interested in this issue see the [Apple developer documentation](https://developer.apple.com/library/prerelease/ios/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/VersionInformation.html#//apple_ref/doc/uid/20002255-BCIECADD)

**Comment by adamgit** [comment]
Current version of xml2 has at least one MAJOR bug in implementation - docs
- headers say one thing, the code does the opposite.

What does "backward compatible" even mean in this situation? Will they
rewrite the docs to do something stupid (the implementation is bad and
wrong), or will they fix the implementation to do what it was supposed to
do in the first place?

We've had to code against this bad implementation; we can take bets on
whether the implementation will still work after upgrade. I would prefer
that the linking fails at that point, forcing people to get an updated
version of SVGKit that's been tested against the new version.
