### ISSUE TITLE
Assertion failure when parsing coordinates

### ISSUE THREAD

**Issue by BjornRuud** [SVGKit/SVGKit#347]
I have a SVG file which crashes the parser. The coordinates seem OK to me but scanning the coordinates fails. The SVG renders correctly in web browsers. This was tested with latest 2.x branch.

```
<svg id="Layer_1" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 59.879 39.266" xml:space="preserve" height="39.266px" viewBox="0 0 59.879 39.266" width="59.879px" version="1.1" y="0px" x="0px" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/">
<path d="M44.482,0.275h-29.085c-8.352,0-15.122,6.77-15.122,15.123,0,8.352,6.77,15.122,15.122,15.122h9.056l5.486,8.249,5.487-8.249h9.057c8.352,0,15.121-6.771,15.121-15.122,0-8.353-6.77-15.123-15.122-15.123z" stroke="#6FC05D" stroke-miterlimit="10" stroke-width="0.55" fill="#008080" fill-opacity="#008080" 
sensio-stroke="LineColor" sensio-fill="FillColor" sensio-fill-opacity="FillColorOpacity" sensio-stroke-width="LineWidth"/>
</svg>
```

```
Assertion failure in +[SVGKPointsAndPathsParser readCoordinate:intoFloat:],
SVGKPointsAndPathsParser.m:322

(lldb) po scanner.string
l5.486,8.249,5.487-8.249

(lldb) po scanner.scanLocation
12
```

I'm stumped, but if anyone can point me in the right direction I will attempt a fix.

**Comment by adamgit** [comment]
I'm on mobile, can only glance, but it looks like you have three numbers 
there - 2d coords should be only two numbers.

It appears to crash on second comma, which makes sense to me - it wasn't 
expecting 3d input.

(that might well be legal, though! the spec does allow for some non obvious 
commissions)

**Comment by greghe** [comment]
change line 369 of SVGKPointsAndPathsParser.m from 

`[SVGKPointsAndPathsParser readWhitespace:scanner];`

to 

`[SVGKPointsAndPathsParser readCommaAndWhitespace:scanner];`

**Comment by BjornRuud** [comment]
Thanks greghe, that was it. I submitted a pull request for the fix.

**Comment by adamgit** [comment]
I thought this was merged months ago, apparently not. Merged now, thanks!
