### ISSUE TITLE
I need UIIimage from SVGImage

### ISSUE THREAD

**Issue by sri3kanth** [SVGKit/SVGKit#35]
Hi ,

I need the UIImage Object from SVGImage,how can i get this UIImage,

Thanks 
Srikanth

**Comment by adamgit** [comment]
UPDATE: this is merged into master now (for anyone reading this in future)

In my fork: https://github.com/adamgit/SVGKit/

SVGKImage.UIImage = returns the UIImage.

NB: I have NOT TESTED THIS! ... the code is pretty simple, and I use it on other projects frequently, but it needs testing here. I have no projects where I would use this feature, so I can't easily test it.

**Comment by sri3kanth** [comment]
thanks

Thanks&Regards
Srikanth I
