### ISSUE TITLE
Timeline for when official public pod version will support Retina HD devices (aka 3x / iPhone 6+)?

### ISSUE THREAD

**Issue by lemonkey** [SVGKit/SVGKit#351]
Ran into this gem when running some experimental SVGKit based code using v1.2 on my iPhone 6+ device:

SVGLength.m -pixelsPerInchForCurrentDevice

NSAssert(FALSE, @"Not supported yet: you are using an iPhone that didn't exist when this code was written, we have no idea what the pixel count per inch is!");

(iPhone7,1 isn't defined in this case)

**Comment by adamgit** [comment]
Cocoapods is simply not supported.

CP continues to be riddled with bugs, badly designed, poorly integrated 
with xcode. Causes way too many headaches for something that is supposed to 
make life easy.

So ... where people update the podspec themselves - great! But we're not 
committinf to supporting CP.

**Comment by lemonkey** [comment]
Thanks for the update.

**Comment by lemonkey** [comment]
Are you ok with hosting public forks on Cocoapods? I have a need to use SVGKit as a subspec for my own static library project, and while I could use a private podspec repo, just checking in case I don't.

**Comment by adamgit** [comment]
What's the impact, what would you need?

If you want to maintain appropriate podspec files on main svgkit that would 
be fine too.

BUT .. CocoaPods team keeps blocking us from this when we've tried, and 
each person who volunteered to maintain it has given up, got frustrated 
with CP, or disappeared. Its very unimpressive.

**Comment by lemonkey** [comment]
Actually, nevermind. I'm just hosting it on a private spec repository. The main need was due to the fact that it is being included as a dependency in a static library that itself is also a dependency for an iOS app.  I can just periodically pull in the latest on 2.x, tag it bump my own private podspec version appropriately.
