### ISSUE TITLE
SVGKImage.h comment about UIImage not supported yet

### ISSUE THREAD

**Issue by lemonkey** [SVGKit/SVGKit#352]
Is the following still a valid comment in the header for SVGKImage.h? Seems like the UIImage property is working as expected with the latest on the 2.x branch:

> - UIImage: not supported yet: will be a cached UIImage that is re-generated on demand. Will enable us to implement an SVGKImageView that works as a drop-in replacement for UIImageView

**Comment by adamgit** [comment]
I don't think we return an actual "UIImage" instance, though? We return
SVGKImage, but I'd hoped we might (one day) provide a subclass of UIImage
that transparently replaced UIImage.
