### ISSUE TITLE
Same SVG file works from NSBundle, fails from URL

### ISSUE THREAD

**Issue by p2** [SVGKit/SVGKit#354]
New SVGKit user here, and I'm encountering something weird. [This SVG map](https://commons.wikimedia.org/wiki/File:H1N1_USA_Map_by_confirmed_deaths.svg) can be included in the app bundle and loads/renders just fine. It doesn't render when using the `SVGKImage` initializer with the URL. It works when I manually load NSData myself, write it to disk and instantiate the image. It does not work when I go this way but use `SVGKSource`.

I've installed v 1.2 via CocoaPods and am using SVGKit via Swift. So to reiterate:
### Works: from bundle

Include `map.svg` in the app bundle and:

``` swift
let image = SVGKImage(named: "map.svg")
// image can be used
```
### Fails: `contentsOfURL`

``` swift
let url = NSURL(string: "https://upload.wikimedia.org/wikipedia/commons/0/0a/H1N1_USA_Map_by_confirmed_deaths.svg")!
let image = SVGKImage(contentsOfURL: url)
// image is nil
```
### Works: download & `contentsOfFile`

``` swift
let url = NSURL(string: "https://upload.wikimedia.org/wikipedia/commons/0/0a/H1N1_USA_Map_by_confirmed_deaths.svg")!
let dirs = NSSearchPathForDirectoriesInDomains(.CachesDirectory, .AllDomainsMask, true)
if let data = NSData(contentsOfURL: url), dirs = (dirs as? [String])?.first {
    let path = dirs.stringByAppendingPathComponent("map.temp.svg")
    data.writeToFile(path, atomically: true)
    let image = SVGKImage(contentsOfFile: path)
    // image can be used
}
```
### Fails: download & `SVGKSource`

``` swift
let url = NSURL(string: "https://upload.wikimedia.org/wikipedia/commons/0/0a/H1N1_USA_Map_by_confirmed_deaths.svg")!
if let data = NSData(contentsOfURL: url) {
    let src = SVGKSource(inputSteam: NSInputStream(data: data))
    let rslt = SVGKParser.parseSourceUsingDefaultSVGKParser(src)
    let image = SVGKImage(parsedSVG: rslt)
    // src and rslt are non-nil, image is nil
}
```

Not sure if I'm doing something wrong or if somebody else can confirm. In any case, thanks for a great framework!!

**Comment by adamgit** [comment]
v1.2 was released 2 years ago.

It's for people that were using it 2-3 years ago, as a courtesy before we
started making lots of sweeping improvements that moved API methods around,
changed signatures, etc.

As per front page: you should be using the master branch (2.x)!

**Comment by p2** [comment]
Well I'm using CocoaPods, it says 1.2 there and that the release was in December 2014?

Trying the `:head` flag.

**Comment by p2** [comment]
Indeed, thanks, using the `:head` flag works (and allows me to get rid of the Lumberjack workaround mentioned elsewhere). FWIW, log output is:

```
Installing SVGKit HEAD based on 1.2.0 (was HEAD based on 1.2.0)
```

Thanks.

**Comment by adamgit** [comment]
CocoaPods isn't supported. Last time we tried to add support, the
maintainers of CP locked-us out from updating it on their system (!) and
were less than helpful. CP does a lot of Weird Stuff to your build files,
most of which is undocumented, and a lot of it is buggy.

By contrast ... if you grab the source, it takes minimal effort to either
build-as-binary or embed directly in your project.

**Comment by adamgit** [comment]
(personally, I'd like to convert the project to an Apple Framework, now
that Apple has removed the ban they placed on iOS Frameworks. That would
make it a single drag/drop install process, much better than both CP and
our current setup!)

**Comment by p2** [comment]
Yeah I know. I've just recently CP-enabled two of my frameworks; works for me but I've seen what you are saying with other frameworks.

I've heard good things about **Carthage** (since you mention "real" Frameworks), but haven't looked into it yet.
