### ISSUE TITLE
CRASH in iOS 8 for .svg files

### ISSUE THREAD

**Issue by ghost** [SVGKit/SVGKit#356]
Hi,

In my application I've encountered an issue in class SVGGradientLayer.m, method `[renderInContext:]`.

On devices with iOS8, when calling the [super renderInContext:], the application will crash if a layer has zero bounds, this issue is discussed here: 
http://stackoverflow.com/questions/27193493/ios-8-crash-renderincontextuigraphicsgetcurrentcontext.

The solution they suggest to overcome this issue is checked and works well.

This fix worked for me:

 `if (!CGRectIsEmpty(self.bounds)) {`
`[super renderInContext:ctx];` 
`}`

Could someone please add this fix?

**Comment by adamgit** [comment]
If it works for you, submit a pull request. Github does all the work for 
you, you literally commit your change to your fork then press the "submit 
pull request" button on the website - the rest is automatic.

**Comment by ghost** [comment]
OK, will do.

Thnx for the quick reply
