### ISSUE TITLE
How to highlight an area in SVGKit?

### ISSUE THREAD

**Issue by zaxonus** [SVGKit/SVGKit#36]
Hi,

I posted a question here a few days ago:
http://stackoverflow.com/questions/13928800/geographical-maps-with-svgkit

In between I got my hands dirty trying to use CALayer  and CAShapeLayer objects in order to understand how these works.
Things have become a bit clearer, but I still am with the main problem unsolved.

How can I highlight a specific area in a map (SVG file) ?
I know this area is identified by: [svgView.document layerWithIdentifier:@"myLayerID"]

I suppose I need to set the proper mask (CAShapeLayer). But how do I set it?
SVGKit probably has some API to make this easy. Am I wrong?

My experience with SVGKit is basically zero. Except for what I just mentioned.

Thanks in advance.

**Comment by adamgit** [comment]
Use the 2013base branch (not master).

OPTION 1: copy the demo code

Look in the demo project (Demo-iOS) and search for the code which makes the monkey's head animate (when you press the Animate button).

That code works by fetching a CALayer and then using Apple aniamtions. You could the same thing with your code.

HOWEVER: note that this REQUIRES using the slower version of SVGKImageView - SVGKLayeredImageView (again, serarch the demo project source to see the docs on this)

OPTION 2: add a new layer

Alternatively, you can use the SVGKFastImageView, but you will have to "copy" the layer you want to use, and then do:

[UIView.layer addSubLayer:myNewLayer]

to add it to one of the views on-screen.

Either way, I suggest you then Google for "calayer shadow" it's very easy to add a glow effect to any CALayer, Apple's code does all the work for you.

**Comment by zaxonus** [comment]
Hi,

Thanks for your reply.

I will try to follow your suggestions and see.

I am convinced, what I want to do should not be so difficult, I just have a
hard time to put my hands on the information I need to put things together.

Bye.

**Comment by zaxonus** [comment]
You mean the shakeHead method?

I am not sure I understand, because I am not trying to make an animation.
I just need to highlight a precise area on a map.

**Comment by zaxonus** [comment]
Sorry I closed by mistake.

**Comment by adamgit** [comment]
You mostly need to read the Apple API's that you're using. Judging by your posts above, you haven't followed the Apple documentation.

What you're describing sound easy to me (if I understand it correctly) - but since it uses Apple API's, you'll find it difficult until you learn the API's involved.

This has nothing to do with animation, but animation works on a layer-by-layer basis, so I thought you'd find it useful to look at code that isolates a single layer, and acts upon it.

**Comment by zaxonus** [comment]
Yeah, thanks. I am sure you are right. I need to read and understand.
My problem is that since I do not see the big picture of how things should be done, I don't exactly know what to study an read about. I started with CALayer and CAShapeLayer, but there are still a lot of trial and errors.
