### ISSUE TITLE
SVGImage bounding box.

### ISSUE THREAD

**Issue by Brekhunchenko** [SVGKit/SVGKit#360]
Hi! :)
I'm trying to find bounding box (smallest rectangle completely enclosing all points in the path) of SVKImage.
Maybe someone has had this problem and worked out there own solution? Please let me know if so :)

**Comment by wasimshigri** [comment]
you can do hittest ..it will give you the layer of that rectangle.the layer contains all the informations for that rectangle

**Comment by adamgit** [comment]
You can use Apple's CALayer class to read this information directly - when you read the .CALayerTree variable from an SVGKImage object, it has automatically been sized to be the exact bounding-box of the SVG
