### ISSUE TITLE
Issue in hit Test

### ISSUE THREAD

**Issue by wasimshigri** [SVGKit/SVGKit#364]
If i draw some  non-rectangle shape using the tag "path" and do hit test, it gives hittest true for the whole rectangular area which is not the part of this shape. 
I want to get hit test true if i touch exactly only on this shape. Any idea for this? thankx

**Comment by adamgit** [comment]
SVGKit should be using CGPathContainsPoint to give you an accurate answer.

Use the debugger and check - it might be you've found a bug in that method (it's an Apple method, not ours! So we assume it's correct).

It might be that your path is too complex for the Apple API to work - does it cross over / intersect itself?

**Comment by wasimshigri** [comment]
i triend both..the closed path and open path.. for both shapes it gives same result..it give hit test for the whole rectangular area inside which the shape fits..

**Comment by adamgit** [comment]
Right, but what happens when you debug it?
