### ISSUE TITLE
 issues of the text display on the picture

### ISSUE THREAD

**Issue by LiJiao09** [SVGKit/SVGKit#366]
I find a question on my project:
1.My text contained in images,but in the mobile phone display is not complete....
2.And words was two lines, according to the results in a line..
why?

Thanks for any help!

**Comment by adamgit** [comment]
Text currently uses Apple's CATextLayer, which isn't powerful enough to support all of SVG Text.

Someone has to replace Apple's class with a better implementation, but that is a lot of work.
