### ISSUE TITLE
Using DOM find start/end points for a specific tags like line

### ISSUE THREAD

**Issue by waseemsmartfissiom** [SVGKit/SVGKit#367]
How to get the start/end points for a specific tag (like line)?
SOme one sugested to use DOM..I dont know how does he means? can any body give an idea what is DOM and how to use it for fetching the start/end points for specific tags?

.

**Comment by adamgit** [comment]
SVG is built on DOM, it's how all standards read and write XML documents.

If you look in the recipes linked from front page, there are some for
finding specific tags in SVG file using DOM commands.

**Comment by waseemsmartfissiom** [comment]
Thankx..
I fetched the list of lines by this:
 NodeList *mynodes1=[image.DOMDocument getElementsByTagName:@"line"];

but it only contains two end points..It dosent tells about the stroke-width or width of the line..For that i am using:
 CAShapeLayer *shapeLayer=[element newLayer];
     float strokeWidth=shapeLayer.lineWidth;

It gives me the width of line but it is slow..i have to find widht of tousands of lines within a second..and have to do it continously..so it takes too much time..is there any other way to find the width of line?
thankx

**Comment by adamgit** [comment]
Save the values in a variable! Dotn recalculate everybframe.

Also, have a look at the CSS code in svgkit. We have methods that 
automatically calculate the width etc by reading all parent items, and 
stylesheets.

They are how we get the right info to tell Apple what to draw - but you can 
invoke the same methods to get the same data.

**Comment by waseemsmartfissiom** [comment]
Thank you so much for response. I solved this issue by the following code:
    NSString\* actualStrokeWidth = [element cascadedValueForStylableProperty:@"stroke-width"];
        CGFloat strokeWidth = [actualStrokeWidth integerValue];
