### ISSUE TITLE
iPhone 6s/6s+ not suported

### ISSUE THREAD

**Issue by EdwinDijkshoorn** [SVGKit/SVGKit#368]
There is an assertion failure when using a 6s(+) iPhone (not the simulator the actual phone)
+(float) pixelsPerInchForCurrentDevice (SVGLength.m)

**Comment by adamgit** [comment]
Yes. Has no effect on a live app, but if you have one of the phones, you 
can add the missing line of code.

Please send a Pull Request on gothub website when you've done it so 
everyone else can use it.

(Apple doesn't share this critical data via api, so we have to have code 
with each new I device :()

**Comment by jtmilne** [comment]
Does this mean that every time a new phone is released this library will crash with an assertion failure?

**Comment by adamgit** [comment]
No, it won't crash - it will assert.

And yes, it will do it on every new phone: it has to, because Apple doesn't
provide an API.
