### ISSUE TITLE
Demo app crashes on iOS6

### ISSUE THREAD

**Issue by hlfcoding** [SVGKit/SVGKit#37]
```
Demo-iOS[8012:c07] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported input units in the SVGLength variable passed in for 'x': 0'
```

Only some examples cause the crash. I haven't gone through all of them.

**Comment by adamgit** [comment]
It's hard to tell, since you didn't say which file you tested, but I believe: No, only one file had that bug, since it's a very specific issue around 0-valued anonymous units. It's fixed now anyway.
