### ISSUE TITLE
Interface Builder support

### ISSUE THREAD

**Issue by hlfcoding** [SVGKit/SVGKit#38]
Have `SVGKFastImageView` support Interface Builder, instead of:

```
WARNING: you have initialized an SVGKImageView with a blank image (nil). Possibly because you're using Storyboards or NIBs which Apple won't allow us to decorate. Make sure you assign an SVGKImage to the .image property!
```

**Comment by adamgit** [comment]
How, exactly, would we do that?

The warning text is pretty clear: Apple forbids us. I don't know what you're thinking we could do instead?

To be clear: I'd love this feature too, but I don't know how it would be possible.

**Comment by hlfcoding** [comment]
Got it, thanks. Just wanted to make sure the warning was up-to-date.

**Comment by jamesmundy** [comment]
So only way to use SVGKit is to add the ImageViews at runtime? (Might be a bit of an obvious question but I'm pretty new to iOS).

**Comment by adamgit** [comment]
Interface Builder allows you to assign arbitrary objects. The interface is shockingly bad, but ... Apple doesn't really want you integrating your own classes/apps/features into IB (they used to support it, then they removed the support, and the features).

Most people give up and add the views in code. It's less hassle than fighting Apple.

**Comment by MaddTheSane** [comment]
Xcode 6 adds support for some IB options for custom views, but they must have a few macros defined in the header.

**Comment by jamesmundy** [comment]
Ah, thanks for the information. That's a shame.

**Comment by lastMove** [comment]
Now it's finally possible with IBDesignable.
Two examples.
http://www.thinkandbuild.it/building-custom-ui-element-with-ibdesignable/
https://www.weheartswift.com/make-awesome-ui-components-ios-8-using-swift-xcode-6/

**Comment by jamesmundy** [comment]
Ah excellent, thanks.

**Comment by adamgit** [comment]
That is very cool.

Who's going to make one for SVGkit?

**Comment by jdarowski** [comment]
I desperately need this. Might try working it out.
