### ISSUE TITLE
Plenty linker warnings

### ISSUE THREAD

**Issue by sashkasashkin** [SVGKit/SVGKit#380]
I build library on my mac according instructions "Build the static library (automatic)".
I add static library with folder usr to my project. And build my project on my mac (sashkasashkin) without warnings. 
But when my project builds on another mac (secondmac) I have plenty linker warnings:

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: /var/folders/xm/pldbmd2s17b19gqsn8tddqgh0000gr/C/org.llvm.clang.sashkasashkin/ModuleCache/16088Q0VAWMOY/Foundation-3DFYNEBRQSXST.pcm: No such file or directory

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: /var/folders/xm/pldbmd2s17b19gqsn8tddqgh0000gr/C/org.llvm.clang.sashkasashkin/ModuleCache/16088Q0VAWMOY/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: /var/folders/xm/pldbmd2s17b19gqsn8tddqgh0000gr/C/org.llvm.clang.sashkasashkin/ModuleCache/16088Q0VAWMOY/Darwin-38I6DLZ5IH61J.pcm: No such file or directory

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: /var/folders/xm/pldbmd2s17b19gqsn8tddqgh0000gr/C/org.llvm.clang.sashkasashkin/ModuleCache/16088Q0VAWMOY/Darwin-38I6DLZ5IH61J.pcm: No object file for requested architecture

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: /var/folders/xm/pldbmd2s17b19gqsn8tddqgh0000gr/C/org.llvm.clang.sashkasashkin/ModuleCache/16088Q0VAWMOY/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: /var/folders/xm/pldbmd2s17b19gqsn8tddqgh0000gr/C/org.llvm.clang.sashkasashkin/ModuleCache/16088Q0VAWMOY/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: /var/folders/xm/pldbmd2s17b19gqsn8tddqgh0000gr/C/org.llvm.clang.sashkasashkin/ModuleCache/16088Q0VAWMOY/UIKit-1V5UHAPTOD24G.pcm: No such file or directory

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: /var/folders/xm/pldbmd2s17b19gqsn8tddqgh0000gr/C/org.llvm.clang.sashkasashkin/ModuleCache/16088Q0VAWMOY/UIKit-1V5UHAPTOD24G.pcm: No object file for requested architecture

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: /var/folders/xm/pldbmd2s17b19gqsn8tddqgh0000gr/C/org.llvm.clang.sashkasashkin/ModuleCache/16088Q0VAWMOY/Dispatch-2LX9MWM6UEPQW.pcm: No such file or directory

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: /var/folders/xm/pldbmd2s17b19gqsn8tddqgh0000gr/C/org.llvm.clang.sashkasashkin/ModuleCache/16088Q0VAWMOY/Dispatch-2LX9MWM6UEPQW.pcm: No object file for requested architecture

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: Could not resolve external type c:objc(cs)NSMutableArray

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: Could not resolve external type c:objc(cs)NSObject

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: Could not resolve external type c:objc(cs)NSObject

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: Could not resolve external type c:objc(cs)NSString

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

warning: Could not resolve external type c:objc(cs)NSDate

while processing /Users/secondmac/Documents/Projects/MyProject/Library/SVGKit/libSVGKit-iOS.1.2.0.a(DDLog.o):

I found the solution on this link: https://forums.developer.apple.com/thread/17921
Precompile Prefix (GCC_PRECOMPILE_PREFIX_HEADER) = NO
Debug Information Format (DEBUG_INFORMATION_FORMAT) = DWARF with dSYM
Enabled Modules (C and Objective-C) (CLANG_ENABLE_MODULES) = NO

But I can't disable modules because I use @import in my project.

When I set Debug Information Format (DEBUG_INFORMATION_FORMAT) = DWARF only without dSYM  in my project warnings are disappeared on second mac.

Can you help me? DWARF without dSYM prevents the capture of crash reports by Crashlytics, HockeyApp, etc.

**Comment by popwarfour** [comment]
Looks like you have some relative file paths from your first mac in there. I would suggest using cocoapods to manage your dependencies. It's easy to setup and very well documented.

**Comment by sashkasashkin** [comment]
how I can use cocoapods for svgkit? what I need write in podfile to install SVGKit?
Thank you

**Comment by popwarfour** [comment]
Install cocoapods via terminal,
    `sudo gem install cocoapods`

Create a new file called `Podfile` in the root of your directory with this as the contents,
    `source 'https://github.com/CocoaPods/Specs.git'`
    `pod 'SVGKit', '~> 1.2.0'`

Install any dependencies from your Podfile via terminal,
    `pod install // use "pod update" in the future for making changes`

From now on open your project with `.xcworkspace` instead of the `.xcodeproj`.

If all went well everything should work. Cocoapds should have created a directory here `~/.cocopods/`. Explore that folder a bit.

**Comment by sashkasashkin** [comment]
Thank you, popwarfour!

I've done it!
Mark:
pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'

**Comment by seltzered** [comment]
Ah, nice to see you're pointing to the latest branch, think I'll try to add the cocoapods branch line to the readme, this is the second issue related to this in the past week.

**Comment by ghost** [comment]
SVGKit is working for me also with CocoaLumberjack version 2.0.

My Podfile contains the next lines:

pod 'CocoaLumberjack', '~> 2.0'

pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch =>
'2.x'

On Fri, Nov 13, 2015 at 7:42 PM, Vivek Gani notifications@github.com
wrote:

> Ah, nice to see you're pointing to the latest branch, think I'll try to
> add the cocoapods branch line to the readme, this is the second issue
> related to this in the past week.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SVGKit/SVGKit/issues/380#issuecomment-156498146.

## 

Guy, iOS Team

**Comment by seltzered** [comment]
Good to hear. Added https://github.com/SVGKit/SVGKit/pull/381 to help clarify things.
