### ISSUE TITLE
Layout of object using "use" not working...

### ISSUE THREAD

**Issue by flemingm** [SVGKit/SVGKit#384]
Sample image: https://upload.wikimedia.org/wikipedia/commons/5/5f/Flag_of_Quebec.svg

should have 4 objects drawn, only 1st one is displayed correct.
other three do not offset - so they are drawn on top of each other.

ie.

```
use xlink:href="#quarter" x="350"
use xlink:href="#quarter" y="250"
use xlink:href="#quarter" x="350" y="250"
```

Full code for SVG:

```
 <?xml version="1.0" encoding="UTF-8"?>

 <svg version="1.0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="600" height="400">

<rect width="600" height="400" fill="#fff"/>

<g id="quarter">

    <rect width="250" height="150" fill="#002495"/>
    <path d="M 149.49815,93.070319 c 1.60698,-2.389976 1.46998,-7.621923 -1.74298,-9.468905 -2.45798,-1.228988 -5.23395,-.747993 -6.53094,.309997 -2.08798,1.262987 -4.09896,5.301947 -4.09896,9.391906 l 7.20993,-.009 -.002,8.050923 -14.96385,-.008 c .196,4.14096 2.45398,7.45792 6.65593,9.3049 -.54099,1.74499 -3.07497,5.30195 -6.55493,5.06095 -.68699,3.76397 -1.33999,5.87694 -4.46896,9.29691 -3.13096,-3.41897 -3.78396,-5.53294 -4.47095,-9.29691 -3.47997,.241 -6.01394,-3.31596 -6.55494,-5.06095 4.20196,-1.84698 6.45994,-5.16394 6.65594,-9.3049 l -14.96485,.008 v -8.050923 l 7.20793,.009 c 0,-4.089959 -2.00798,-8.128919 -4.09796,-9.391906 -1.29699,-1.05699 -4.07196,-1.537985 -6.52894,-.309997 -3.214964,1.846982 -3.352962,7.079929 -1.74598,9.468905 -15.181846,-2.818972 -13.675861,-17.480825 -8.503913,-22.803772 4.179958,-4.299957 8.736913,-4.97195 12.250873,-3.615964 7.98592,2.862972 13.35687,12.402876 13.61787,26.652734 h 4.17595 c 0,-12.95387 -2.25397,-17.083829 -8.12692,-33.353666 -2.95797,-7.688924 -1.18098,-17.194829 4.10696,-25.947741 1.89398,-3.136969 4.25996,-5.96894 6.97893,-9.00191 2.71698,3.03297 5.08295,5.864941 6.97693,9.00191 5.28795,8.752912 7.06493,18.258817 4.10896,25.947741 -5.87594,16.269837 -8.12992,20.398796 -8.12992,33.353666 h 4.17596 c .261,-14.249858 5.63395,-23.789762 13.61787,-26.652734 3.51396,-1.354986 8.07392,-.683993 12.25187,3.615964 5.17095,5.322947 6.67694,19.9848 -8.50491,22.803772 z" fill="#fff"/>

</g>
<use xlink:href="#quarter" x="350"/>
<use xlink:href="#quarter" y="250"/>
<use xlink:href="#quarter" x="350" y="250"/>
```

**Comment by flemingm** [comment]
I check out SVGKParserDefsAndUse.m
and it seem  to be picking up x and y location but don't know where to go from here to fix the issue.

**Comment by adamgit** [comment]
That's the parser class. Now you probably need to find the class that does
rendering/layout for this feature - something without "parser" in the name.

 A global search for getAttribute( "use" ) or similar might find it.

Old features often have rendering + parsing in a singke file, but most of
that have been split into separate files by now.

**Comment by flemingm** [comment]
found it in newLayerWithElement() in SVGKImage.m  
looks like it create a layer but does no adjustment.

I try adjusted CALayer 's frame but that did not work.

but looking closer maybe SVGUseElement  's -(void)layoutLayer:(CALayer *)layer 
is where this should happen? 

 Tried the following but did not work:

-(void)layoutLayer:(CALayer _)layer
{
    if( [instanceRoot.correspondingElement respondsToSelector:@selector(layoutLayer:)])
        [((SVGElement<ConverterSVGToCALayer>_)instanceRoot.correspondingElement) layoutLayer:layer];

```
CGRect lFrame = layer.frame;

lFrame.origin = CGPointMake( lFrame.origin.x + [self.x pixelsValue], lFrame.origin.y + [self.y pixelsValue] );
layer.frame = lFrame;
```

}

Any ideas?

**Comment by adamgit** [comment]
Looks sensible.

I don't have time to test myself, sorry.

Quick thoughts:
1. CALayer is very easy to get wrong - lots of apple API "quirks" (is bugs, 
   but now so old that they're effectively official)
2. CGFrame can be unpredictable data internally.

So I'd breakpoint your lines of code and check the contents of each layer 
and frame as it runs, line by line in debugger - you might find that one is 
being zeroed and then getting ignored, or similar.

(we've had a few bugs where that kind of thing had happened)

**Comment by flemingm** [comment]
solved it.  

  // NOTE Lauyout of SVGUseElement is not done in SVGUseElement.m due referencing object tree. It done in SVGKImage.m - newLayerWithElement:

added to child loop..

```
/**
 Generate child nodes and then re-layout

 (parent may have to change its size to fit children)
 */
NSUInteger sublayerCount = 0;
for (SVGElement *child in childNodes )
{
    if ([child conformsToProtocol:@protocol(ConverterSVGToCALayer)]) {

        CALayer *sublayer = [[self newLayerWithElement:(SVGElement<ConverterSVGToCALayer> *)child] autorelease];
```

   if (saveParentNode) {   // Use element (offsets) adjust sublayers.   TODO: Size adjustment.
                CGRect lFrame = sublayer.frame; 
                lFrame.origin = CGPointMake( lFrame.origin.x + layer.frame.origin.x, lFrame.origin.y + layer.frame.origin.y );
                sublayer.frame = lFrame;
                //DEBUG SVGKitLogVerbose(@"\t[%@] DEBUG:  childern (class:%@) to CALayer (class:%@ frame:%@ pointer:%@) for id = %@", [self class], NSStringFromClass([child class]), NSStringFromClass([sublayer class]), NSStringFromCGRect( sublayer.frame ), sublayer, child.identifier);
            }
   ....

Attached is updated file..

[SVGKImage.m.zip](https://github.com/SVGKit/SVGKit/files/60565/SVGKImage.m.zip)

**Comment by adamgit** [comment]
Great! Can you submit a pull request?

(clone the repository, make the change, commit it, and then from github
website should be a big button "submit pull request")

That way I can auto-merge it, and it credits you as author etc.

**Comment by dmurtagh** [comment]
@flemingm's previous fix doesn't seem to be working any more. I'm not sure if it's something that's changed on the Apple CALayer side.
The workaround I found is to use set the x and y translations in use tags on the matrix transform.

In SVGKParserDefsAndUse.m I added this fix:

if( [attributes valueForKey:@"x"] != nil )
				useElement.x = [SVGLength svgLengthFromNSString:[((Attr*)[attributes valueForKey:@"x"]) value]];
			if( [attributes valueForKey:@"y"] != nil )
				useElement.y = [SVGLength svgLengthFromNSString:[((Attr*)[attributes valueForKey:@"y"]) value]];
            
            // Damien: "x" and "y" aren't working in <use> tags. This fix in SVGKImage isn't working: https://github.com/SVGKit/SVGKit/issues/384#issuecomment-159151069
            // Only way I've figured out to fix this is to add the x and y elements to the transform
            useElement.transform = CGAffineTransformTranslate(useElement.transform, useElement.x.value, useElement.y.value);
            useElement.x = 0;
            useElement.y = 0;
