### ISSUE TITLE
ISsue on iphone 6 plus

### ISSUE THREAD

**Issue by waseemsmartfissiom** [SVGKit/SVGKit#388]
Assertion failure in +[SVGLength pixelsPerInchForCurrentDevice], /Users/waseem/projects/SVGKit-2.x/Source/DOM classes/SVG-DOM/SVGLength.m:165

**Comment by adamgit** [comment]
Read the message. Asserts because its impossible not to. If you have the device, add the code for it.

I thought someone else had already added it. are you sure you have current up to date code?
