### ISSUE TITLE
App crashes sometime while loading SVG image

### ISSUE THREAD

**Issue by Priyanka-Razdan** [SVGKit/SVGKit#391]
Hi,

I had integrated SVGKit to display .svg images in my app in swift, it works fine but sometimes for loading some images, application get crash with the following reason:

CALayerWithClipRender.m line 26
-[CALayerWithClipRender renderInContext:]

I had searched the reason and many says that instead of using CGRectNULL in the source you must use CGRectZero, but i had libSVGKit-iOS. 1.2.0.a file which contains all the .m file so unable to changes the source. Could you please update the source or please provide any advice to overcome the issue.
Any help would be appreciated.

Thanks

**Comment by adamgit** [comment]
Where did you get that file from?

**Comment by Priyanka-Razdan** [comment]
I had downloaded the zip and followed the instruction to integrate it in the project.
In the instruction it is mentioned copy libSVGKit-iOS. 1.2.0.a  into the project

**Comment by adamgit** [comment]
Version 1.2 is more than 2 years old. Your project should not be generating
that file, and it should not be in the docs. I think this is a bug in the
recent commits.

We are experimentally using SVGKit as a Framework - you don't need to do
any copying, just use it as a Framework. But it looks like no-one updated
the instructions.

The new instructions should say "drag/drop the Framework into your project"
and have no other steps, I think. Unfortunately, I didn't update it myself,
you'd have to ask @Dschee

**Comment by Priyanka-Razdan** [comment]
I think the current source is also not updated as when i download the source zip again it has libSVGKit-iOS. 1.2.0.a version only. Could you please provide the latest code or framework.
That would be a great help!
thanks

**Comment by Priyanka-Razdan** [comment]
@Dschee
Hi, 
I think the current source is also not updated as when i download the source zip again it has libSVGKit-iOS. 1.2.0.a version only. Could you please provide the latest code or framework.
That would be a great help!
thanks

**Comment by Jeehut** [comment]
Hi Priyanka-Razdan, I'm not using this library any more (I opted for JAMSVGImage instead: https://github.com/jmenter/JAMSVGImage) but as adamgit mentioned you can now include SVGKit as a framework. Steps to do this were very similar to any other framework as far as I can remember, for example you can find steps for adding Alamofire here – you can do it for SVGKit the same way, I think: https://github.com/Alamofire/Alamofire#embedded-framework

I hope this helps.

**Comment by adamgit** [comment]
Thanks @Priyanka-Razdan for the info on library filename - I've fixed that (uses the correct filename now) in latest commit.

I am testing the Framework verison now, I'll update when its ready

**Comment by adamgit** [comment]
Framework version is now running, seems to work OK.

I have only done basic tests, but it's worth trying now.

**Comment by Priyanka-Razdan** [comment]
@adamgit 
Hi,
Thanks a lot for your help.
Could you please elaborate the instructions of how to add the framework version. As when i integrated it in swift it is giving errors.
Thanks.

**Comment by adamgit** [comment]
I don't use swift, I have no idea how you use frameworks in it. I suggest 
googling for help on frameworks and swift - svgkit is / should be exporting 
a standard framework.

NB: We don't have a test project for framework builds yet, so there may be 
bugs. I don't have time to create one right now, but if you have problems, 
I suggest making a normal objecticeC project first, and seeing of framework 
is working there.

Full instructions are on the front page.of the site!
