### ISSUE TITLE
2.x animation did not work

### ISSUE THREAD

**Issue by JohnWong** [SVGKit/SVGKit#398]
The monkey can't animate any more. It works fine in master branch.

**Comment by adamgit** [comment]
Last time I chekxed (approximately 6 months ago), it was working in 2.x. Can you rewind a few months, identify which commit broke it?

It might be very recent.

**Comment by JohnWong** [comment]
@adamgit I've found the commit that may broken the animation.
https://github.com/SVGKit/SVGKit/commit/a99abd2601fe7f5a49b1330d800042ec6ad737f7

**Comment by alexandre-g** [comment]
in DetailViewController.m change 
`if ([self.sourceOfCurrentDocument.keyForAppleDictionaries isEqualToString:@"Monkey"]) {`
to `if ([self.sourceOfCurrentDocument.keyForAppleDictionaries rangeOfString:@"/Monkey.svg"].location != NSNotFound) {`

and same in the other place where its used in that file (search for "monkey")

**Comment by adamgit** [comment]
Great. Please submit a pull request and I'll merge it now

**Comment by JohnWong** [comment]
Fixed in a6af3a160854145c05d313dda83a40c0ea70d21a
