### ISSUE TITLE
App crashes. An instance of class SVGKLayeredImageView was deallocated while key value observers were still registered with it

### ISSUE THREAD

**Issue by JohnWong** [SVGKit/SVGKit#401]
Choose monkey.svn and tap back button. It crashes.

**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7a1ac870 of class SVGKLayeredImageView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7a1af3a0> (
<NSKeyValueObservance 0x7a1af370: Observer: 0x79f6d780, Key path: timeIntervalForLastReRenderOfSVGFromMemory, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x7a1af1b0>

**Comment by adamgit** [comment]
What device / iOS version? I ran this exact test, and it didn't crash for
me.

**Comment by JohnWong** [comment]
Demo project of iOS version. At commit of a6af3a160854145c05d313dda83a40c0ea70d21a. More details in PR #402 . Fixed now.
