### ISSUE TITLE
Demo project won't build after recent changes

### ISSUE THREAD

**Issue by alexandre-g** [SVGKit/SVGKit#405]
no such file or directory: '/Users/alex/Desktop/SVGKit_2x/SVGKit/SVGKitLibrary/Demo-iOS-Prefix.pch'

@adamgit can you please fix this? I could myself but would probably ruin the new project structure you had in mind

**Comment by alexandre-g** [comment]
Actually, i figured it out but now its complaining about CALayerExplorer that's been turned off

**Comment by adamgit** [comment]
Are you using that class? It hasn't been maintained for many years now.

**Comment by alexandre-g** [comment]
No, not using it. The demo won't compile without it though

**Comment by alexandre-g** [comment]
should be fixed with 7b3b39f5aba8911ba8b8ca9bc1b5926d2e62381e
