### ISSUE TITLE
Cannot remove an observer <SVGKFastImageView 0x7f55bb70> for the key path "layer" <SVGKFastImageView 0x7f55bb70>

### ISSUE THREAD

**Issue by tato469** [SVGKit/SVGKit#409]
Hello I am having the following problem:

```
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <SVGKFastImageView 0x7c0478e0> for the key path "layer" from <SVGKFastImageView 0x7c0478e0> because it is not registered as an observer.'
```

Despite of the fact I am using the branch 2.0.0:

```
 pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.0.0'
```

pod installs me the branch 2.x:

```
Installing SVGKit 2.x (was 2.x)
```

I searched a bit and I found that maybe [this](https://github.com/SVGKit/SVGKit/blob/c364d5c01d8a3cd15236b0c1787189e835dd4bed/Source/UIKit%20additions/SVGKFastImageView.m) version of SVGKFastImageView could help me but nothing happens
.

So have someone fixed this problem in any branch? Thanks.

**Comment by tato469** [comment]
**SOLVED:** I set my podfile to and the problem has been fixed.

```
platform :ios, '9.1'
```

**Comment by adamgit** [comment]
Is this something that needs to be changed in the podfile in SVGKit?

If so, please submit a pull request and I'll merge it.

**Comment by tato469** [comment]
No, everything is fine :)

**Comment by dayjer** [comment]
For anyone else who ends up here -- I encountered this issue in 2.x because I had previously removed these KVO to prevent crashes in older SVGKit. e.g.

```
@try {
    [self removeObserver:self forKeyPath:@"tileRatio"];
    [self removeObserver:self forKeyPath:@"showBorder"];
   [self removeObserver:self forKeyPath:@"layer"];
    [self removeObserver:self forKeyPath:@"image"];
    [self.layer removeObserver:self forKeyPath:@"transform"];
    [self.image removeObserver:self.image forKeyPath:@"DOMTree.viewport"];
}

@catch (NSException *exception) {

}
```

Removing this appears to resolve the issue.

**Comment by adamgit** [comment]
Thanks, @dayjer . Someitmes I wish github had a mailing list, so we coudl send out advice / announcements like this to everyone :)

**Comment by tato469** [comment]
Great @dayjer.
