### ISSUE TITLE
SVG format issues

### ISSUE THREAD

**Issue by sversov** [SVGKit/SVGKit#41]
Hi, i have strange issue with svg files created  in Illustrator 5. Some of them does not opened at all. Some of them open wrong way ( no text ). 
Could you please give recommendation of how to create svg right way. What is the major requirements of SVGKit concerning sag files format ?
By the way , is it possible to render text as vektors ?

Thank you in advanced.

**Comment by adamgit** [comment]
I added TEXT support _very_ recently - I have done all the hard work, all that is left is the "easy" work of applying Transforms and Attributes (i.e. colors).

Someone has written code that MIGHT provide this, but their commit contains lots of other files - you'd have to edit the SVGText file on its own.

See here: https://github.com/SVGKit/SVGKit/pull/39 - also there's some discussion in the comments on whether this will work, other ideas etc.

Try it! (it might work first time, but we haven't had time to test it yet)

**Comment by adamgit** [comment]
Text support is a lot better now. We DO NOT CURRENTLY SUPPORT "tspan" tags (delete the tags themselves, and everything will work fine).
