### ISSUE TITLE
Cannot remove Observer for key 'size' (if any one know please help)

### ISSUE THREAD

**Issue by ghost** [SVGKit/SVGKit#42]
'Cannot remove an observer <SVGKFastImageView 0x18f974e0> for the key path "size" from <SVGKImage 0x171579f0> because it is not registered as an observer.'

I have not used any addition of observer in my code. this is in kit . Please help me how to get rid this issue because xcode is giving me nothing.

thanks

**Comment by ghost** [comment]
-(void) addInternalRedrawOnResizeObservers
{
    [self addObserver:self forKeyPath:@"layer" options:NSKeyValueObservingOptionNew context:internalContextPointerBecauseApplesDemandsIt];
    [self.layer addObserver:self forKeyPath:@"transform" options:NSKeyValueObservingOptionNew context:internalContextPointerBecauseApplesDemandsIt];
//  [self.image addObserver:self forKeyPath:@"size" options:NSKeyValueObservingOptionNew context:internalContextPointerBecauseApplesDemandsIt];
}

-(void) removeInternalRedrawOnResizeObservers
{
    [self removeObserver:self  forKeyPath:@"layer" context:internalContextPointerBecauseApplesDemandsIt];
    [self.layer removeObserver:self forKeyPath:@"transform" context:internalContextPointerBecauseApplesDemandsIt];
//  [self.image removeObserver:self forKeyPath:@"size" context:internalContextPointerBecauseApplesDemandsIt];
}

By commenting these two lines now it is not crashing. let me know why it is so.

**Comment by adamgit** [comment]
Short answer: Apple's Key/Value observer system is "broken by design" and they never fixed it.

Long answer: HOWEVER ... You should NOT be getting the extra "remove" attempt. No-one else has this. So: it's only you. But you've not provided any info about what versions you're using, what files you're loading, etc -- so we can't really help.
