### ISSUE TITLE
The file CALayerWithChildHitTest.h have a typo

### ISSUE THREAD

**Issue by brunogama** [SVGKit/SVGKit#427]
When using HFS+ with case-sensitive fs the project will not compile to solve the issue the import must import the header file with the correct filename.

`#import "CALayerWithClipRender.H"`

should be 

`#import "CALayerWithClipRender.h"`

**Comment by adamgit** [comment]
Ouch. Good catch. Please fix it and submit a Pull Request - I can't directly edit from web interface.
