### ISSUE TITLE
2.x: Fill attribute on root <svg> element ignored

### ISSUE THREAD

**Issue by cpboyd** [SVGKit/SVGKit#434]
I've been using Google's Material Design icons: https://design.google.com/icons/

Google establishes a fill attribute on the root <svg> element, and only lists a `fill="none"` on paths without a fill.

Using SVGKit, it seems to expect a fill attribute for each path and doesn't pay attention to a fill attribute on the root element.

**Comment by adamgit** [comment]
Can you find a bit in the spec that describes this and how it should work?

Probably very quick to add/alter by using the existing code that inherits
attributes downwards.

**Comment by cpboyd** [comment]
@adamgit I've just found that they say `Inherited: yes` in the spec (most other fill attributes seem to be marked as inherit as well):
https://www.w3.org/TR/SVG/painting.html#FillProperty

I'm not sure if the spec notes anything special about the root element.

**Comment by adamgit** [comment]
Off the top of my head - we already inherit fills on elements,
atuoamtically. Possibly a bug that we don't honour that on the root element
alone?

**Comment by cpboyd** [comment]
I just took some time going through the code and found this while condition:
https://github.com/SVGKit/SVGKit/blob/2.x/Source/DOM%20classes/Unported%20or%20Partial%20DOM/SVGElement.m#L631

Basically, we stop once we find the root <svg> element without acknowledging attributes within it.
Additionally, group <g> tags will also stop inheritance according to this code.

It seems to me that certain values should inherit all the way to the root <svg> element.

I can work on a pull request.

**Comment by adamgit** [comment]
Yep, sounds like a bug to me.

**Comment by cpboyd** [comment]
Should be fixed with pull request #444.
