### ISSUE TITLE
SVG crashes app

### ISSUE THREAD

**Issue by jbolter** [SVGKit/SVGKit#44]
Hi guys, we have an SVG that we're trying to use with the 2013 branch that crashes the demo app.  Can you guys see what you think is wrong with it? I'm trying to figure it out but I thought I'd send it over to see what you thought.

https://dl.dropbox.com/u/14879894/sprite.svg

Thanks,
Justin

**Comment by adamgit** [comment]
If you read the console log, it tells you exactly what's wrong.

In short: we have no example SVGs that use the IMAGE tag, so no-one has updated the code for it recently.

c.f. https://github.com/SVGKit/SVGKit/issues/45 -- the solution MIGHT BE a simple copy/paste - but I'm afraid I don't have time to try this myself right now, sorry

**Comment by adamgit** [comment]
This is now fixed in latest SVGKit/2013base branch - https://github.com/SVGKit/SVGKit/tree/2013base
