### ISSUE TITLE
SVGKImage initialize failed

### ISSUE THREAD

**Issue by HIIgor** [SVGKit/SVGKit#440]
I've use all kinds of method to make a SVGKImage, but it returns nil。 The path of svg file can be found through pathForResource: type: .
Just like this
 `SVGKImage *image = [SVGKImage imageNamed:@"a.svg"];

```
    _svgImageView = [[SVGKImageView alloc] initWithSVGKImage:image];`
```

Do you have any ideas?

**Comment by adamgit** [comment]
If it returns nil, there is always an explanation loggd to the console!
Read your logs.
