### ISSUE TITLE
Assertion failure in +[SVGKPointsAndPathsParser readCoordinate:intoFloat:]

### ISSUE THREAD

**Issue by sebasbad** [SVGKit/SVGKit#445]
1. Installed pod:
   `pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'`
2. Loaded svg 

``` swift
let svgkImage = SVGKImage(named: "Ghostscript_Tiger")

let svgkFastImageView = SVGKFastImageView(SVGKImage: svgkImage)
svgkFastImageCanvasView.addSubview(svgkFastImageView)
resizeSubviewToFitSuperview(superview: svgkFastImageCanvasView, subview: svgkFastImageView)

let svgkLayeredImageView = SVGKLayeredImageView(SVGKImage: svgkImage)
svgkLayeredImageCanvasView.addSubview(svgkLayeredImageView)
resizeSubviewToFitSuperview(superview: svgkLayeredImageCanvasView, subview: svgkLayeredImageView)
```

The example project can be downloaded here: https://github.com/sebasbad/SVGKit-Swift-Demo/tree/feature/getting-started-with-SVGKit

The error is this

```
*** Assertion failure in +[SVGKPointsAndPathsParser readCoordinate:intoFloat:], /Users/XXX/ios/SVGKitSwiftTest/Pods/SVGKit/Source/Parsers/SVGKPointsAndPathsParser.m:322
```

The result is this: the SVGKFastImageView only shows part of the svg while the SVGKLayeredImageView doesn't show anything

![captura de pantalla 2016-05-13 a las 13 59 41](https://cloud.githubusercontent.com/assets/2473684/15247341/e23e1de4-1913-11e6-84dc-4d99ad4f46ef.png)

The svg can be downloaded here: http://blackicemedia.com/presentations/2013-02-hires/img/awesome_tiger.svg

**Comment by adamgit** [comment]
What's the error, what were the data values, what should they have been, etc?

**Comment by sebasbad** [comment]
Hi @adamgit , i've updated the issue comment. Do you need more info? Thnx

**Comment by adamgit** [comment]
When Xcode has an assertion failure, it will show you data on the screen saying what it expected, and what actually happened. You have to read this - Xcode is very badly written and when you copy/paste the output, taht information is missing :(.

(old versions of Xcode didnt have this bug, but Apple broke it about 3-4 years ago and hasn't fixed it)

**Comment by aronkool** [comment]
Today I also had this issue. It get caused because the parser does not parse the seperating comma's between values and than tries to parse something like `,1.43` and it's true that's not a valid float.

So I've made a fork and a pull-request to fix this issue: https://github.com/SVGKit/SVGKit/pull/519
