### ISSUE TITLE
Image Not loading properly.

### ISSUE THREAD

**Issue by shaniraaj** [SVGKit/SVGKit#457]
I have an svg image generated through the inkscape but when i am loading the image the image contents are missing from the image.
Please help me regarding this.
Thank You.

**Comment by adamgit** [comment]
No-one can help unless you do some investigation, and narrow down what's
not appearing, and what the SVG source code is for those parts, sorry.

**Comment by shaniraaj** [comment]
i am using an svg image which must be loaded on view i am using SVGKFastImageView for loading it but the svg image is not get loaded properly.

here the code i am using for loading an svg image.

```
SVGKFastImageView * svgImgView=[[SVGKFastImageView alloc]initWithFrame:CGRectMake(30, 60, 300, 300)];

NSString * filepath=[[NSBundle mainBundle] pathForResource:@"ink-invoice1" ofType:@"svg"];
NSString * fileContents=[NSString stringWithContentsOfFile:filepath encoding:NSUTF8StringEncoding error:nil];
NSData * data=[fileContents dataUsingEncoding:NSUTF8StringEncoding];

svgImgView.image=[SVGKImage imageWithData:data];
```

the file which i am loading is an invoice template file with svg format

**Comment by adamgit** [comment]
Yes, you need to do some debugging.

Your code is wrong - you're deleting the error message - you should at
least read the errors if there are any!

**Comment by shaniraaj** [comment]
Sorry sir,
But there are no errors in the project and also no warnings regarding it.

**Comment by shaniraaj** [comment]
but when i am using the SVGKImageView instead of SVGKFastImageView i am getting a exception 
Exception:
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You cannot init this class directly. Instead, use a subclass e.g. SVGKFastImageView'

**Comment by adamgit** [comment]
I'm afraid you're making some basic errors that suggest you need to learn
more Objective-C coding first.
1. You need to find out what NSError is, and you must not pass "nil" for it.
2. You need to learn how to use breakpoints and Xcode's built-in debugger
   to see what's happening to your code.
