### ISSUE TITLE
Transformations

### ISSUE THREAD

**Issue by smashew** [SVGKit/SVGKit#46]
Transformations aren't commutative and I think you may be handling them in the wrong order. I am trying to get some D3 SVGs to render. I am modifying until it works, once it works may I send you proposed changes?

(I don't ever really send 'issues' on this thing, lol)

**Comment by adamgit** [comment]
That's very possible - we don't have any sample SVG's that use multi-transforms-in-one-attribute (I think).

I've just pushed a fix to 2013base for transforms that are space-separated (we were previously ONLY accepting comma-separated, oops) which might help too...

**Comment by smashew** [comment]
I went ahead and fixed it. I modified mg?????s branch (don't know his name)
something's build as I was looking to render D3 word clouds from SVG. So,
since it was words at various sizes and the slightest over rotation would
cause fonts to collide into one another. (A particularly annoying use case)
I went ahead and patched. I can shoot them to you of you'd like.

On matrix math A \* B != B \* A you had a convention it just happened to be
backwards. Lol. :-)

Great work on it tho, you saved a huge part of my project I'm working on,
I'm going to find some more ways to use it to enhance my data
visualizations and make them more interactive with my designers. :-)

Matt

Sent from my iPhone

On Feb 11, 2013, at 5:28 PM, adamgit notifications@github.com wrote:

That's very possible - we don't have any sample SVG's that use
multi-transforms-in-one-attribute (I think).

I've just pushed a fix to 2013base for transforms that are space-separated
(we were previously ONLY accepting comma-separated, oops) which might help
too...

—
Reply to this email directly or view it on
GitHubhttps://github.com/SVGKit/SVGKit/issues/46#issuecomment-13409872.

**Comment by adamgit** [comment]
Yep please send patches and if they test OK i'll add to master, thansk

**Comment by adamgit** [comment]
There's a major problem with mtrubnikov's code - it alters the Apple CALayer.transform / affineTransform properties - and Apple's code for transforms is BROKEN throughout Apple's libraries.

BUT ... talking to mtrubnikov about this ... I believe he's correct that we _need_ something equivalent to this to achieve SVG Spec compliance :(.

I don't know what we're going to do about this, but it will probably require major changes :(

**Comment by adamgit** [comment]
Looking further ... this is an old problem with Apple's library. Their "concat" method does the opposite of what it appears to do.

**Comment by smashew** [comment]
Want a working example of a D3 SVG word loud?

Sent from my iPhone

On Feb 16, 2013, at 9:56 AM, adamgit notifications@github.com wrote:

Looking further ... this is an old problem with Apple's library. Their
"concat" method does the opposite of what it appears to do.

—
Reply to this email directly or view it on
GitHubhttps://github.com/SVGKit/SVGKit/issues/46#issuecomment-13654367.

**Comment by adamgit** [comment]
If you've got one you can make public domain (and we can include in our
Test Suite), that would be great.

Also: ensures future versions of SVGKit are unlikely to break it :)

On 16 February 2013 20:44, Matthew.Hager@gmail.com <notifications@github.com

> wrote:
> 
> Want a working example of a D3 SVG word loud?
> 
> Sent from my iPhone
>
