### ISSUE TITLE
Preloading a large amount of SVGs

### ISSUE THREAD

**Issue by ellensundh** [SVGKit/SVGKit#47]
Hi!

I am using SVGKit and love it. As I build my app I added more and more SVGs and loading a UIView with them takes a while now. Is there a way to make them render as they show on the screen or some how cache them once I used the files in one view?

Thanks for a great lib.

**Comment by adamgit** [comment]
Using 2013base, yes?

Look at the SVGKImage class - if you use the "imageNamed" method to load images, it automatically maintains a global cache of SVGs, and will re-use an SVG if it already has been loaded.

This line of code lets you disable the feature at compile time:

#define ENABLE_GLOBAL_IMAGE_CACHE_FOR_SVGKIMAGE_IMAGE_NAMED 1 // if ENABLED, then ALL instances created with imageNamed: are shared, and are NEVER RELEASED

...but also: if you want to copy that cache into your own custom classes (and don't want to use imageNamed:), you can search for code blocks that are #ifdef'd on that flag, and easily find all the code that implements the cache.

**Comment by adamgit** [comment]
Alternatively, load the SVGKImage's all at once (parsing is quick), and display them one at a time by calling Apple's "addSubview" or "addSublayer" after a delay of 0.0 seconds (google for more info - you're workign around design flaws in Apple's drawing API, whereby it waits until its finished EVERYTHING before drawing ANYTHING. Telling it to do each one after 0.0 seconds, and then do the next after another 0.0 seconds etc ... is a well-known trick to achieve this)
