### ISSUE TITLE
dyld: Library not loaded: @rpath/SVGKit.framework/SVGKit :   Reason: image not found

### ISSUE THREAD

**Issue by duraiganesh0** [SVGKit/SVGKit#472]

**Comment by SumeetMourya** [comment]
@duraiganesh0 : Try to load the SVGKit framework in Embedded Banaries.

**Comment by noveleven** [comment]
same problem :(

**Comment by SumeetMourya** [comment]
@noveleven : Can you use SVGkit with cocoa pod ?
I have resolve these type of issue for my swift language based project with cocoa pod. With few changes.

**Comment by noveleven** [comment]
@9SumeetMourya I tried, it got a arch error, but lipo command output info that Lumberjack and SVGKit arch were both right.

**Comment by SumeetMourya** [comment]
@noveleven : you are using with swift project or objectiveC project?

**Comment by noveleven** [comment]
@9SumeetMourya ObjC project. Could you make a blank project test it using cocoapods please.

**Comment by srinivasgadda** [comment]
I have created a single view project (iOS) and tried to integrate SVGKit with the recommended approach suggested
_Drag/drop the .framework file into your project <-- PREFERRED / RECOMMENDED_
Still I had the same issue, can you please give solution apart from cocoapods?

**Comment by srinivasgadda** [comment]
@duraiganesh0 Any updates on the issue? Not sure, why it was closed without answering our query

**Comment by adamgit** [comment]
It was closed by the person who reported it - presumably because the issue is now solved!

If you have another issue, open a new one?

**Comment by ar-juan** [comment]
Add the framework (+ CocoaLumberjack, see folder 3rd-party-frameworks) to Embedded Binaries under the General tab.

<img width="659" alt="Schermafbeelding 2019-06-22 om 09 33 47" src="https://user-images.githubusercontent.com/5184525/59960971-f2da1e00-94d0-11e9-8a3a-d70837da8c97.png">
