### ISSUE TITLE
SVGKLayeredImageView on retina display

### ISSUE THREAD

**Issue by birnimal** [SVGKit/SVGKit#48]
Hi,
I tried to use SVGKLayeredImageView, but rendered image is not smooth on retina display.
Does SVGKLayeredImageView support retina display?

And I added following code to newLayer method in SVGGElement.m, SVGSVGElement.m, SVGGroupElement.m and SVGShapeElement.m,
the image looks smooth.

_layer.contentsScale = [[UIScreen mainScreen] scale];
_layer.rasterizationScale = _layer.contentsScale;

Thanks,

**Comment by adamgit** [comment]
We tried that before, and it didn't work. Maybe something else has changed, and this works now?

(I believe that what you've done is the Apple recommended approach - but it wasn't working when we tried it!)

**Comment by birnimal** [comment]
The code which I added do not work now as you say.
But I added follows, and it seems to work.

SVGHelperUtilities.m

+(CALayer _) newCALayerForPathBasedSVGElement:(SVGElement<SVGTransformable>_) svgElement withPath:(CGPathRef) pathRelative
{
    CAShapeLayer\* _shapeLayer = [[CAShapeLayerWithHitTest layer] retain];
        _shapeLayer.contentsScale = [[UIScreen mainScreen] scale]; // add
        _shapeLayer.rasterizationScale = _shapeLayer.contentsScale; // add
    ....
}

I added these setting after creating layer instance.

**Comment by adamgit** [comment]
I can't reproduce this.

WITH NO CHANGES TO THE CODE, everything renders at Retina resolution correctly.

Please provide more info + an example SVG file / project that demonstrates the problem.

**Comment by birnimal** [comment]
Please check your project "Demo-iOS" and select Monkey.svg.
It looks blurry.

**Comment by adamgit** [comment]
I tried it today, took screenshots, magnified to 10x ... there is no
blurriness.

So ... you need to be more specific, because currently I cannot reproduce
what you are seeing :(

**Comment by birnimal** [comment]
Umm... It's strange...
I retried it with master branch after Merge branch '2013base', and the problem was reproduced.

The details are as follows.
Xcode: Version 4.6 (4H127)
iOS: 6.1
Device: iPhone 5 and simulator(Retina)

I do not change your code at all.

This is a screenshot with "Demo-iOS" project and Monkey on iPhone 5.

![ss_layeredimageview](https://f.cloud.github.com/assets/3584991/164450/4b7f8ca6-78a5-11e2-9f5b-d9fb26173dd0.png)

And it is displayed clearly if I changed from SVGKLayeredImageView to SVGKFastImageView in your DetailViewController.m.

![ss_fastimageview](https://f.cloud.github.com/assets/3584991/164451/7cf2fab6-78a5-11e2-94f5-f64cb4607031.png)

**Comment by adamgit** [comment]
Ah, I thought you meant something different by "blurry", sorry!

I tried your fix and it made no difference for me, with ios 6.1 and iphone
4 retina :(.

I'l try again

**Comment by adamgit** [comment]
Excellent - found the problem, and fixed it.

There's TWO possible fixes - your code, OR: turn off rasterization.

I have MOVED ALL RASTERIZING CALLS into a single method, so it can be turned on / turned off in one place, with a single #define - c.f. SVGHelperUtilities.h

**Comment by adamgit** [comment]
PS: I've changed the code so that whenever rasterizing is enabled, your code is ALSO called, to make sure the rasterizing is "sharp"

**Comment by birnimal** [comment]
Great! Thank you!
