### ISSUE TITLE
Filling Colors using SVGKLayeredImageView

### ISSUE THREAD

**Issue by kiranvarma** [SVGKit/SVGKit#485]
I am trying to use SVG files to display as images, In my SVG file i have multiple tags like, "line" tag, "text" tag, "path" tag etc.. 

I want to fill colours for these shapes, For that i am using  "SVGKLayeredImageView" i am trying to get the layers and trying to fill the colors. 

Below is the code i am getting, I am able to high light only some areas behind the text. But not able to highlight other shapes, I am getting "CALayerWithChildHitTest", Do the other Shapes getting the CAShapelayers, 

Can any one suggest

```
CALayer* layer = self.imageView.layer;
for (CALayer *subLayer in layer.sublayers) {
    DLog(@"%@", [subLayer class]);

    for (CALayer *subSubLayer in subLayer.sublayers) {
        DLog(@"%@", [subSubLayer class]);

        for (CALayer *subSubSubLayer in subSubLayer.sublayers) {
            DLog(@"%@", [subSubSubLayer class]);

            if( [subSubSubLayer isKindOfClass:[CAShapeLayer class]]){
                CAShapeLayer* shapeLayer = (CAShapeLayer*)subSubSubLayer;
                shapeLayer.fillColor = [UIColor redColor].CGColor;

            }

        }
    }
}
```

**Comment by adamgit** [comment]
Instead of choosing random sublayers, why don't you use the DOM methods on
the SVG to read back the exact tags for each element?

You can then get the layer for the element, and edit the layer.

**Comment by kiranvarma** [comment]
Thanks Adam for your Suggestion, Is there any tutorial for using the DOM methods on SVG, Or any document where we can we see how to use.

**Comment by adamgit** [comment]
There are several examples linked to from the front page of the github site
here.

**Comment by kiranvarma** [comment]
You mean in the this page https://github.com/SVGKit/SVGKit, Or did you gave any hyperlink to "Here" in your previous comment, I didnt got any Hyperlink

**Comment by adamgit** [comment]
Yes that page!

**Comment by kiranvarma** [comment]
Adam, I have one more doubt can you please guide, 

In my requirement i have some shapes in my SVG file, Suppose if i click on a particular Path, can i get Root Element of the Shape. Based on that i can parse and fill the colors for the corresponding path. 

Is there any method or process which can give me the Root Node of selected path (Based on the touch co-ordinates can we get). Can you pls help

**Comment by adamgit** [comment]
I assume you mean the corresponding SVG element , not the root element (the
root element means the "<svg>" tag that creates the whole document).

If so, that's exactly what's shown in the demo project (try clicking on any
SVG), so you have the source right there, and is also explained in some of
the recipes linked from the svgkit website.

**Comment by kiranvarma** [comment]
Thanks, Adam. 
I will try that, I Have got other issue with "Symbol" tag, Earlier i have got a crash for it, I Created new Class "SVGSymbolElement" which is extended "SVGElement" (Just like  SVGDefsElement), Then i used the SVGSymbolElement in "SVGKParserDefsAndUse" class. 

I added "Symbol" tag in the array as below

-(NSArray*) supportedTags
{
    return [NSMutableArray arrayWithObjects: @"defs",@"symbol", @"use", nil];
}

Then In the below method i just used a "defs" tag because i feel the code may take care of the functinality.  I have added else if for symbol and write same code as defs. 

After this the crash is fixed but I see the issue, What ever there in "Symbol" tag is not Drawing. 

Can you please help 
- (Node_) handleStartElement:(NSString *)name document:(SVGKSource_) SVGKSource namePrefix:(NSString_)prefix namespaceURI:(NSString_) XMLNSURI attributes:(NSMutableDictionary _)attributes parseResult:(SVGKParseResult *)parseResult parentNode:(Node_) parentNode
  {
  if( [[self supportedNamespaces] containsObject:XMLNSURI] )
  {  
      NSString\* qualifiedName = (prefix == nil) ? name : [NSString stringWithFormat:@"%@:%@", prefix, name];
  
  ```
  if( [name isEqualToString:@"defs"])
  {   
      /** NB: must supply a NON-qualified name if we have no specific prefix here ! */
      SVGDefsElement *element = [[SVGDefsElement alloc] initWithQualifiedName:qualifiedName inNameSpaceURI:XMLNSURI attributes:attributes];
  
      return element;
  }
  **else if( [name isEqualToString:@"symbol"])
  {
      /** NB: must supply a NON-qualified name if we have no specific prefix here ! */
      SVGSymbolElement *element = [[SVGSymbolElement alloc] initWithQualifiedName:qualifiedName inNameSpaceURI:XMLNSURI attributes:attributes];
  
      return element;
  }**
  
  else if( [name isEqualToString:@"use"])
  {   
      /** NB: must supply a NON-qualified name if we have no specific prefix here ! */
      SVGUseElement *useElement = [[SVGUseElement alloc] initWithQualifiedName:qualifiedName inNameSpaceURI:XMLNSURI attributes:attributes];
  
      [useElement postProcessAttributesAddingErrorsTo:parseResult]; // handles "transform" and "style"
  
      if( [attributes valueForKey:@"x"] != nil )
          useElement.x = [SVGLength svgLengthFromNSString:[((Attr*)[attributes valueForKey:@"x"]) value]];
      if( [attributes valueForKey:@"y"] != nil )
          useElement.y = [SVGLength svgLengthFromNSString:[((Attr*)[attributes valueForKey:@"y"]) value]];
      if( [attributes valueForKey:@"width"] != nil )
          useElement.width = [SVGLength svgLengthFromNSString:[((Attr*)[attributes valueForKey:@"width"]) value]];
      if( [attributes valueForKey:@"height"] != nil )
          useElement.height = [SVGLength svgLengthFromNSString:[((Attr*)[attributes valueForKey:@"height"]) value]];
  
      NSString* hrefAttribute = [useElement getAttributeNS:@"http://www.w3.org/1999/xlink" localName:@"href"];
  
      NSAssert( [hrefAttribute length] > 0, @"Found an SVG <use> tag that has no 'xlink:href' attribute. File is invalid / don't know how to parse this" );
      if( [hrefAttribute length] > 0 )
      {
          NSString* linkHref = [((Attr*)[attributes valueForKey:@"xlink:href"]) value];
  
          NSAssert( [linkHref hasPrefix:@"#"], @"Not supported: <use> tags that declare an href to something that DOESN'T begin with #. Href supplied = %@", linkHref );
  
          linkHref = [linkHref substringFromIndex:1];
  
          /** have to find the node in the DOM tree with id = xlink:href's value */
          SVGElement* linkedElement = (SVGElement*) [parseResult.parsedDocument getElementById:linkHref];
  
          NSAssert( linkedElement != nil, @"Found an SVG <use> tag that points to a non-existent element. Missing element: id = %@", linkHref );
  
  
          useElement.instanceRoot = [self convertSVGElementToElementInstanceTree:linkedElement outermostUseElement:useElement];
      }
  
      return useElement;
  }
  ```
  
  }
  
  return nil;
  }

**Comment by kiranvarma** [comment]
In Demo project We have a SVG with file name "struct-use-09-b.svg"  it is having "Symbol" tag. But is not used any where (I dont know the reason), I added to the "Licenses.plist" to access it but not able to open it, Attaching the screen shot 

I got the below in the console 

2016-10-13 13:54:02:904 Demo-iOS[11195:601351] [SVGKSourceLocalFile] MISSING FILE (not found in App-bundle, not found in Documents folder), COULD NOT CREATE DOCUMENT: filename = struct-use-09-b, extension = svg
2016-10-13 13:54:02:926 Demo-iOS[11195:601351] [SVGKFastImageView] WARNING: you have initialized an SVGKImageView with a blank image (nil). Possibly because you're using Storyboards or NIBs which Apple won't allow us to decorate. Make sure you assign an SVGKImage to the .image property!

![file](https://cloud.githubusercontent.com/assets/1327027/19341877/109de3e8-914d-11e6-95ff-1d2d6b126e3f.png)

![simulator screen shot 13-oct-2016 1 55 23 pm](https://cloud.githubusercontent.com/assets/1327027/19341812/b62f1436-914c-11e6-9be8-bcaed1ce6399.png)

**Comment by adamgit** [comment]
Make a new Issue for new issues, please

**Comment by rahul-mane** [comment]
@adamgit  "You can then get the layer for the element, and edit the layer."
-> How can I get CALayer from Element?

I have,

`    
Element* domElement = [newImage.DOMDocument getElementById:@"svg_2"];
// I need CALayer of domElement
`

**Comment by adamgit** [comment]
Element is a superclass. Look at the actual class!

If its rendrring, it will be an SVGElement subclass.

**Comment by ghost** [comment]
if you have any id for the SVG image, you can fill the colours with respect to the ID.

```
    let image = SVGKImage(named: "iconName")
    let svgIMGV = SVGKFastImageView(frame: self.imgView.frame)
         svgIMGV.image = image
          svgIMGV.fillTintColor(colorImage: UIColor.red, iconID: "Bank")
```



```
 func fillTintColor(colorImage: UIColor, iconID: String) {
        if self.image != nil && self.image.caLayerTree != nil {
            print(self.image.caLayerTree.sublayers)
            guard let sublayers = self.image.caLayerTree.sublayers else { return }
            fillRecursively(sublayers: sublayers, color: colorImage, iconID: iconID)
        }
    }
    
     private func fillRecursively(sublayers: [CALayer], color: UIColor, iconID: String, hasFoundLayer: Bool) {
        var isLayerFound = false
        for layer in sublayers {
            if let l = layer as? CAShapeLayer {
                
                print(l.name)                
                //IF you want to color the specific shapelayer by id else remove the l.name  == "myID"  validation
                if let name =  l.name,  hasFoundLayer == true && name == "myID" {
                    self.colorThatImageWIthColor(color: color, layer: l)
                    print("Colouring FInished")
                }
            } else {
                if layer.name == iconID {
                    if let innerSublayer = layer.sublayers as? [CAShapeLayer] {
                        fillRecursively(sublayers: innerSublayer, color: color, iconID: iconID, hasFoundLayer: true )
                        print("FOund")
                    }
                } else {
                    if let l = layer as? CALayer, let sub = l.sublayers {
                        fillRecursively(sublayers: sub, color: color, iconID: iconID, hasFoundLayer: false)
                    }
                }
            }
           
        }
    }
    
    func colorThatImageWIthColor(color: UIColor, layer: CAShapeLayer) {
        if layer.strokeColor != nil {
            layer.strokeColor = color.cgColor
        }
        if layer.fillColor != nil {
            layer.fillColor = color.cgColor
        }
    }
    

```
