### ISSUE TITLE
Disable rasterizing when using transforms

### ISSUE THREAD

**Issue by tsaizhenling** [SVGKit/SVGKit#49]
In my application i have to use transforms instead of setting the size of the frames/bounds

I was able to do this fine in the previous version.

is there a way to switch off the rasterizing/or rasterise after transform for 2013base?

**Comment by adamgit** [comment]
What does: " i have to use transforms instead of setting the size of the frames/bounds" mean?

We have some major problems internally which I _think_ will force us to use .transform propertis for _every single layer_ in the output. Will this break your app?

**Comment by tsaizhenling** [comment]
If i set frame
svgkFastImageView.frame = CGRectMake(0,0,w,h);
i will get crisp images irregardless of the values of w and h (yay~)

but if i set svgkFastImageView.layer.transform = CGAffineTransformMakeScale(2.0,2.0); (I was doing this when using the older version of SVGKit and it worked out fine)
the image appears pixelated as if the image was rasterized before i set the transform

and yes unfortunately it would break my app :(

**Comment by tsaizhenling** [comment]
i should be clearer. I would set the frame size, THEN apply a transform. also, if it makes a difference, i disabled global caching.

**Comment by adamgit** [comment]
"but if i set svgkFastImageView.layer.transform = "

Users changing the .transform has NEVER been supported, because of Apple's many bugs there. It may have _accidentally_ worked ;), for some SVG's - but in general: it didn't

**Comment by adamgit** [comment]
So, I need to understand this better:

"In my application i have to use transforms instead of setting the size of the frames/bounds"

Why do you have to use transforms?

**Comment by tsaizhenling** [comment]
im using transform matrix information for animation. so i thought setting the transform property would be more straight forward. Since you've clarified its never been intended to be used that way, i'd have to figure something else out :/ thanks for building svgkit anyway. its great :)

**Comment by adamgit** [comment]
Actually, we hit some other problems with using transform, and I've
converted the code back to old style (ie svgkit NEVER sets the transform,
except for text).

We have to use transform for TEXT because apple api's dont provide any
other way to move/rotate/resize text.

(Except CoreText, which I have no experience with. Someone who knows
coretext could probaby fix this later)
