### ISSUE TITLE
Memory leak when getting UIImage from SVGKImage

### ISSUE THREAD

**Issue by ivan-ushakov** [SVGKit/SVGKit#491]
I faced with problem. When I request UIImage from SVGKImage multiple times and each time I change size of SVGKImage I see memory leak. Any idea why this could happen?

**Comment by adamgit** [comment]
Have you tried running Xcode's Leaks tool to find out if it can autodetect
a leak?

If not, are you sure there is a leak?

**Comment by ivan-ushakov** [comment]
Yes, and I see growing VM: CoreAnimation category. Since I don't use any animations I guess that leak happens in SVGKit rendering process. As I understand you use a CA layers a lot.
BTW I use SVGKit in Swift 3 project. Here is a simple code:

```
func render(width: Int, height: Int) -> CGImage? {
    let colorSpace = CGColorSpaceCreateDeviceRGB()
    let bitmapInfo = CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue)
    guard let context = CGContext(data: nil, width: width, height: height, bitsPerComponent: 8, bytesPerRow: 0, space: colorSpace, bitmapInfo: UInt32(bitmapInfo.rawValue)) else {
        return nil
    }

    self.vectorImage?.render(to: context, antiAliased: true, curveFlatnessFactor: 1, interpolationQuality: .default, flipYaxis: false)

    return context.makeImage()
}
```

When I run it in a loop with a lot of iterations per second, I see growing memory in VM: CoreAnimation. If I comment out self.vectorImage?.render() call then memory not growing.

**Comment by adamgit** [comment]
Merely seeing memory usage increasing is not a leak. A leak is when data is retained after it shouldn't be, and if the system runs out of memory it crashes. I would guess you're seeing caching.

If you have an actual leak, it'll be detected by Xcode, and it will give a precise line number, with a precise reason for the leak.

**Comment by ivan-ushakov** [comment]
I see that memory increasing up to 300 megabytes without any reason. I'm not sure this is correct.
And Xcode not always detect memory leaks. I can try to create simple project reproducing problem.

**Comment by khushDesai** [comment]
@adamgit i have also faced issue of memory leaking , i have used this library and there are up to 50 images could you please help me to stop leaking of my app . 

Thank You :)

**Comment by adamgit** [comment]
There are no known memory leaks. Unless you can provide evidence of one, I do not believe there are leaks.
