### ISSUE TITLE
How do I serialize a SVGKImage? 

### ISSUE THREAD

**Issue by sarperdag** [SVGKit/SVGKit#494]
Trying to load a SVGKImage into NSData, write it to disk and then re-store it into an SVGKImage but all my attempts have failed. What's the best practice for this?

Basically, I just want to do some modifications on a .svg file loaded into the UI, save the latest state and then re-open for later use. 

Any help is greatly appreciated. Thanks!

**Comment by adamgit** [comment]
You should be writing directly out as string, no?

I wrote an example of loading, changing, saving a couple of years ago, 
maybe linked from front page as a recipe. It was very quick, we already had 
almost all the code in the svgkit project

**Comment by sarperdag** [comment]
Thanks Adam,

Have been checking the docs but can't find a working proper code or example.

What I'm trying to achieve is very simple actually. I just want these 3 lines to work but when I try to read the NSData back in the third line, it just comes nil.

```
SVGKImage *image = [SVGKImage imageNamed:@"SomeImage.svg"];
NSData *data = [SVGKExporterNSData exportAsNSData:svgImage];
SVGKImage *reReadImage = [SVGKImage imageWithData:data];
```

Where exactly can I find a working sample code for such a need?

**Comment by adamgit** [comment]
That looks correct to me. You have no output on the console, no errors or
warnings? What happens when you run in the debugger?

**Comment by sarperdag** [comment]
No errors or warnings. The problem is that [SVGKImage imageWithData:data] returns nil although the data object is not nil. 

I tried using imageWithDataAsynchronously as below and in this case I got this error message from parseResult and the returned loadedImage is again nil.

[Parse result: 0 warnings, 0 errors(recoverable), 1 errors (fatal). First fatal error: Error Domain=1 Code=4 "Document is empty
" UserInfo={lineNumber=1, NSLocalizedDescription=Document is empty
, columnNumber=1}

```
        [SVGKImage imageWithDataAsynchronously:data onCompletion:^(SVGKImage *loadedImage, SVGKParseResult *parseResult) {
            SVGKImage *reReadImage = loadedImage;
            UIImage *testImage = reReadImage.UIImage;
        }];;
```

**Comment by adamgit** [comment]
NSData is approximately 90% implemented (which was fine in 1995, but not so
fine that we're 20 years later and Apple still hasn't finished writing it).

Possibly you need to explicitly write out to an NSString, and then convert
the NSString to an NSData before reading back in. A lot of Apple's API
calls around NSData crash / error if there's no actual "thing" backing the
original NSData.

But ... use the debugger, and see what nsdata you're writing out. Is it
suspiciously small? Have you got an NSData with the correct Unicode type
(you cannot simply create an "NSData", that doesn't exist - the nsdata
created should appear in the debugger as a human-readable string
automatically), and there may be something wrong with the SVGKit helper
class that it's failing to initialize the NSData objecT?)

**Comment by sarperdag** [comment]
Well, the data is not small at all. Tried converting to NSString as well, same problem...

Actually it's [this svg file](https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/beacon.svg) I'm using as an example. Here's the exact code I'm using: 

```
    SVGKImage *image = [SVGKImage imageNamed:@"beacon.svg"];
    NSData *data = [SVGKExporterNSData exportAsNSData:image];
    
    [SVGKImage imageWithDataAsynchronously:data onCompletion:^(SVGKImage *loadedImage, SVGKParseResult *parseResult) {
        
        DLog(@"%@", parseResult);
        
        if (loadedImage) {
            SVGKImage *reReadImage = loadedImage;
            UIImage *testImage = reReadImage.UIImage;
        }
    }];;
```

**Comment by sarperdag** [comment]
Same thing happens if I use SVGKSource as well. 

```
    SVGKImage *image = [SVGKImage imageNamed:@"beacon.svg"];
    SVGKSource *source = image.source;
    SVGKImage *reReadImage = [SVGKImage imageWithSource:source];
```

reReadImage is nil.

I'd like to try this by converting SVGKSource to NSString first. How do I do that?

**Comment by sarperdag** [comment]
Just tried with this code without fiddling with NSString or NSData. Still the same result :(

```
SVGKImage *image = [SVGKImage imageNamed:@"beacon.svg"];
NSInputStream *inputStream = image.source.stream;
SVGKSource *source = [[SVGKSource alloc] initWithInputSteam:inputStream];
SVGKImage *reReadImage = [SVGKImage imageWithSource:source];
```

**Comment by adamgit** [comment]
Um. Look at the debugger!!!

(what is the type of the data SVGKExporterNSData writes? Hint: does it
look like text?)

You really must use the debugger when diagnosing issues in Xcode.

I think what you really want is this page:
http://t-machine.org/index.php/2013/11/17/svgkit-programmatic-editing-of-svg-files-on-ios/

**Comment by sarperdag** [comment]
All right. I was able to get this working using the code below. (Although this is something different from exporting to NSData initially. I've been checking the debugger for the validity of the NSData exported... That exportAsNSData seems to be unstable) 

Anyways, the code below works.

```
SVGKImage *svgImage = [SVGKImage imageNamed:@"beacon.svg"];
NSMutableString *svgImageString = [NSMutableString string];
[svgImageString appendString:@"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"];
NSMutableDictionary* allNamespaces = [svgImage.DOMDocument allPrefixesByNamespaceNormalized];
[svgImage.DOMDocument.rootElement appendXMLToString: svgImageString availableNamespaces:allNamespaces activeNamespaces: [NSMutableDictionary dictionary]];
```

And then I do some modifications on the CALayer level and expect this to be reflected back to the DOMDocument because I will now save the modified NSString to the disk / memory. And when I do:

```
// fill some CALayers through SVGKLayeredImageView with a fillColors and stuff and modify the look in the UI
... 
SVGKImage *modifiedImage = [SVGKImage imageWithSource:[SVGKSourceString sourceFromContentsOfString: svgImageString]];
```

This still gives me back the original, non-modified SVGKImage, am I missing something? Can't see anything about this on the recipe page I've been reading...

**Comment by adamgit** [comment]
CAlayers are *exported* from the DOM.

If you want the DOM to change you need to change the DOM.

I think it would be incredibly complicated to write a library that 
converted the whole of CoreAnimation to an SVG DOM.

You're not the first to hope/assume that happens, so maybe we need a clear 
statement of this on the front page?

**Comment by sarperdag** [comment]
Adam, thanks for all your help and directions so far. And yes, the documentation needs some clarifications especially for first-comers. 

Anyways, I don't actually need to reflect the changes to the DOMDocument.

**Comment by adamgit** [comment]
I'd keep your own list of changes - dictionary of which layers have been 
changed, and their new colours - which you update in parallel with updating 
the calayer.

Then you can iterate over that and use it to change the DOM when they're 
saving, and then export the Dom as you already have working.

You can make it easier by making sure every clickable.part.of your svg has 
an id attribute, svgkit will automatically attach those tags to the 
calayers it creates

**Comment by sarperdag** [comment]
Yeah thanks Adam, this is also what I've been thinking of doing for the past hour. In fact, I've actually already implemented it :) Closing this issue for now.

**Comment by balasRepo** [comment]
@sarperdag can you please post your code here for reference. I want to save the modified SVGKImage to disk. Thanks in advance.
