### ISSUE TITLE
Problem with framework and static library installation

### ISSUE THREAD

**Issue by agerstown** [SVGKit/SVGKit#495]
1) There is a problem with a framework, described here: https://github.com/SVGKit/SVGKit/issues/455
You can either build the project (SVGKit-iOS) for a generic device - then you will be able to build and run your project only on a device
or build for a simulator - then only on a simulator

I see this error when the framework was built for a simulator and I try to build and run my project on a device: "warning: ignoring file .../SVGKit, file was built for x86_64 which is not the architecture being linked (arm64)"

![image](https://cloud.githubusercontent.com/assets/13255497/20554740/ef55b1c4-b16e-11e6-9c9d-1797e7649d40.png)

2) By the link above it's said you can solve the problem by using the static library (second way to use SVGKit), but I can't do it as after I build the project SVGKit-iOS, files in the Products folder are missing (red) except for the .framework

![image](https://cloud.githubusercontent.com/assets/13255497/20554743/f5291cda-b16e-11e6-8765-b2a34defe2bd.png)

**Comment by vitalii-tym** [comment]
Natalia, make sure you choose "SVGKit-iOS" before building.
![screenshot 2016-11-23 11 57 19](https://cloud.githubusercontent.com/assets/5410835/20557466/4fe407ac-b174-11e6-812f-cfe88bb0213d.png)

**Comment by agerstown** [comment]
@vitalii-tym thank you! Now the .a file is black and I can see it. Although second way of installation (static library) still doesn't work for me

What I do:
1) Open "SVGKit-iOS.xcodeproj", and Build it (cmd-B)
2) in left navbar, scroll to bottom, and open the "Products" section
3) right click the library ("libSVGKitBLAHBLAH.a") and select "show in finder"
4) GO UP ONE FOLDER
5) select the "Debug-universal" (or Release-universal if you were building in Release mode) folder
6) Drag/drop the .a file and the "usr" folder into your project (select the "Copy files" checkbox)
7) In Build Settings, select "Other Linker Flags" and add "-ObjC"

8) Edit your build settings and set "C/C++ Compiler Version" = "LLVM Compiler 2.0" - I don't have this, instead: "Compiler for C/C++/Objective-C" = "Default compiler (Apple LLVM 8.0)"

9) Add ALL the frameworks and 3rd party libraries listed below (go to "Build Phases", and "Link Binary with Libraries"):
CoreText
CoreImage

libxml2.dylib - don't have this, instead: libxml2.tbd

QuartzCore
CoreGraphics
UIKit

My project is in Swift so I also have a bridging header with the following:
#import <SVGKit/SVGKit.h>

The errors I get:
![image](https://cloud.githubusercontent.com/assets/13255497/20558679/513049c8-b182-11e6-9522-fe1f10a3e891.png)

![image](https://cloud.githubusercontent.com/assets/13255497/20558685/55993718-b182-11e6-9e8a-8dcaa876010e.png)

![image](https://cloud.githubusercontent.com/assets/13255497/20558690/59fcff9c-b182-11e6-88cc-ac600b9ee9ee.png)

**Comment by agerstown** [comment]
![image](https://cloud.githubusercontent.com/assets/13255497/20558852/3d0e137a-b183-11e6-8141-289510b343ad.png)

**Comment by agerstown** [comment]
all works! needed to write #import "SVGKit.h" in my bridging header
