### ISSUE TITLE
How to save SVGKImage to a svg file?

### ISSUE THREAD

**Issue by randylu** [SVGKit/SVGKit#497]
Hi, SVGKit is a great project, it helps me a lot!
I can display/zoom the image from SVG file, but when I modify the fillColor of one SVGLayer, and is there anyway to save the changes to local SVG file?

**Comment by adamgit** [comment]
If you modify a CALayer, you are not editing the SVG, you are editig
Apple's proprietary CoreAnimation, and you will have to write your own
converter to make it into SVG again.

If you are modifying the SVG DOM, you can save it directly using the
examples linked fomr the front page, or in #494

**Comment by randylu** [comment]
Thanks for your quick answer!
I just read the source codes, and found there is no relation between CALayer and DOM element, Just like what you point out.

**Comment by randylu** [comment]
I try the method in page:
@http://t-machine.org/index.php/2013/11/17/svgkit-programmatic-editing-of-svg-files-on-ios/
But another error comes up:
_Found a namespace (http://www.w3.org/XML/1998/namespace) in node (svg) which wasn't listed in the KNOWN namespaces you provided_

I try many SVG files, either from the SVG-Demo or myself.
Any help is a great appreciate!

**Comment by randylu** [comment]
I fix it by change svg tag to:
<svg version="1.1" id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 1000 1000" style="enable-background:new 0 0 1000 1000;">

the original tag is:
<svg version="1.1" id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 1000 1000" style="enable-background:new 0 0 1000 1000;" xml:space="preserve">

**Comment by randylu** [comment]
The original tag is:
\<svg version="1.1" id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 1000 1000" style="enable-background:new 0 0 1000 1000;" xml:space="preserve"\>

Then I fix it by remove the last attribute:
xml:space="preserve"
