### ISSUE TITLE
Does SVGKLayeredImageView supports radial gradient?

### ISSUE THREAD

**Issue by randylu** [SVGKit/SVGKit#498]
It seems that radial gradient is only supported by SVGKFastImageView after I run SVG-Demo, am i right?
I searched all the closed issues about 'radial', and some of them have said it.
Any help is a great appreciate!

**Comment by adamgit** [comment]
If the issues are "closed" that means it's fixed.

**Comment by randylu** [comment]
Thanks for you response.
The closed issue said Radial gradient is supported in SVGKFastImageView, nothing about SVGKLayeredImageView.
But I try to add an circle element(with radial gradient) in SVGKLayeredImageView, the loading image is just blank. I don't know why? Then I run the demo, the same result!

**Comment by randylu** [comment]
I also try to load an SVG file with linear gradient, it's ok for SVGKLayeredImageView.

**Comment by adamgit** [comment]
It should be the other way around - *everything* works in the Layered
version (by definition - this is Apple's code), and a few things don't work
in the Fast version.

You may have a new bug. I suggest you first load the RainbowWing image
(that's included in the sample images) in both types of view. I believe it
works in both - if it doesn't work for you, you can start debugging why not.

If it works, then you can start debugging why your images are behaving
differently from that.
