### ISSUE TITLE
SVG world map not parsing

### ISSUE THREAD

**Issue by uson1x** [SVGKit/SVGKit#5]
When I tried to parse an SVG world map from http://en.wikipedia.org/wiki/File:BlankMap-World6-Equirectangular.svg , I've got a lot of errors like:

<pre>Error: CGPathAddCurveToPoint: no current point.</pre>

I tried to make a quick fix, but I couldn't understand what was wrong.

**Comment by mattrajca** [comment]
SVGKit currently doesn't support inline stylesheets. This is probably tripping up the parser so I have updated the issue accordingly.

**Comment by adamgit** [comment]
This was fixed in all branches about 12 months ago,.
