### ISSUE TITLE
Use of undeclared identifier '_stringValue'

### ISSUE THREAD

**Issue by Rost-pro** [SVGKit/SVGKit#50]
Hi, I appologise in advance if this is a wrong place to ask this kind of dumm questions. I'm trying to build the demo example of svgkit but there is an error in SVGElement.m on line 158(and on 400 but i guess they are related) that says that _stringValue is undeclared, I'm three days into ios development and have no idea how to fix it. Thank you for your time.

**Comment by adamgit** [comment]
Which iOS SDK?

Which branch - master, or 2013base?

**Comment by Rost-pro** [comment]
Wow i figured questions have longer livespan, any way i'm using 2013base branch, and Xcode 4.3.3

**Comment by adamgit** [comment]
OK, I see the problem - your version of Xcode is quite old (Apple doesn't support Xcode 4.3.x any more - the current Xcode is 4.5.x), and it doesn't allow auto-synthesized @properties.

HOWEVER ... we're trying to keep the project backwards-compatible to Xcode 4.0.x and 3.x, so ... I've added a manual property which SHOULD fix this for you.

c.f. SVGElement line 45:

```
 @synthesize stringValue = _stringValue;
```

Try latest copy from master, and see if it builds. If you get any more build errors that are the same as the one you just got, you need to add an explicity @synthesize line like the one above, into the .m file for the affected class.

It would be great if you could add any needed and commit, and send a Pull Request, so we can merge them back into master.
