### ISSUE TITLE
SVG display is not complete

### ISSUE THREAD

**Issue by xiaoyafei** [SVGKit/SVGKit#501]
Hello！I have a svg-
<img width="376" alt="svg" src="https://cloud.githubusercontent.com/assets/8553906/21079235/c360dbdc-bfc6-11e6-8993-b6ed42a75077.png">display on iPhone 
<img width="375" alt="show" src="https://cloud.githubusercontent.com/assets/8553906/21079242/0e461982-bfc7-11e6-8fcb-bbacae093293.png">
The svg's text is missing.
Is there anyone to help me？
Thank you!

**Comment by adamgit** [comment]
You must:

1. Work out what's broken
2. Use the debugger to find out why it's broken
3. Explain what's broken, and why

Until you do that, no-one can help.

**Comment by xiaoyafei** [comment]
My program was not broken
the text on the picture does not show.like "k1" "k3" "k2".
@adamgit

**Comment by adamgit** [comment]
I wasn't talking about your program, I was talking about SVGKit.

You have the full source code and you have a powerful debugger - it will tell you exactly what's happening.

Once you know that, you can fix it, or someone else might fix it.

If you don't know what's broken, I will close this issue - you are currently saying "something is wrong, I don't know what". It's impossible to fix something if you can't say what's wrong.

**Comment by flemingm** [comment]
Providing a sample SVG File is also required for someone else to fix SVGKit display of the SVG file.

**Comment by xiaoyafei** [comment]
[svg2.svg.zip](https://github.com/SVGKit/SVGKit/files/645203/svg2.svg.zip) @flemingm

**Comment by xiaoyafei** [comment]
> <ellipse id="v3" fill="#ccf0fc" cx="238" cy="207" rx="8" ry="14"></ellipse>
    <ellipse id="v5" fill="#ccf0fc" cx="274" cy="207" rx="8" ry="14"></ellipse>
    <path d="M257,241 C261.418278,241 265,234.731986 265,227 C265,219.268014 261.418278,213 257,213 C252.581722,213 249,219.268014 249,227 C249,234.731986 252.581722,241 257,241 Z" id="v2" fill="#ccf0fc" transform="translate(257.000000, 227.000000) rotate(-270.000000) translate(-257.000000, -227.000000) "></path>
    <ellipse id="v6" fill="#ccf0fc" cx="274" cy="177" rx="8" ry="14"></ellipse>
    <text id="K1" font-family="PingFangSC-Medium, PingFang SC" font-size="10" font-weight="400" line-spacing="10" fill="#FFFFFF">
     <tspan x="14.5" y="93">
      K1
     </tspan>
    </text>
    <text id="K3" font-family="PingFangSC-Medium, PingFang SC" font-size="10" font-weight="400" line-spacing="10" fill="#FFFFFF">
     <tspan x="48.5" y="69">
      K3
     </tspan>
    </text>
    <text id="K2" font-family="PingFangSC-Medium, PingFang SC" font-size="10" font-weight="400" line-spacing="10" fill="#FFFFFF">
     <tspan x="48.5" y="122">
      K2
     </tspan>
    </text>

The <text></text>tag doesn't show!

**Comment by xiaoyafei** [comment]
`<ellipse id="v3" fill="#ccf0fc" cx="238" cy="207" rx="8" ry="14"></ellipse>
    <ellipse id="v5" fill="#ccf0fc" cx="274" cy="207" rx="8" ry="14"></ellipse>
    <path d="M257,241 C261.418278,241 265,234.731986 265,227 C265,219.268014 261.418278,213 257,213 C252.581722,213 249,219.268014 249,227 C249,234.731986 252.581722,241 257,241 Z" id="v2" fill="#ccf0fc" transform="translate(257.000000, 227.000000) rotate(-270.000000) translate(-257.000000, -227.000000) "></path>
    <ellipse id="v6" fill="#ccf0fc" cx="274" cy="177" rx="8" ry="14"></ellipse>
    <text id="K1" font-family="PingFangSC-Medium, PingFang SC" font-size="10" font-weight="400" line-spacing="10" fill="#FFFFFF">
     <tspan x="14.5" y="93">
      K1
     </tspan>
    </text>
    <text id="K3" font-family="PingFangSC-Medium, PingFang SC" font-size="10" font-weight="400" line-spacing="10" fill="#FFFFFF">
     <tspan x="48.5" y="69">
      K3
     </tspan>
    </text>
    <text id="K2" font-family="PingFangSC-Medium, PingFang SC" font-size="10" font-weight="400" line-spacing="10" fill="#FFFFFF">
     <tspan x="48.5" y="122">
      K2
     </tspan>
    </text>`

The <text></text>doesn't show!

**Comment by xiaoyafei** [comment]
My problem is solved.SVGKit is good！ @adamgit
