### ISSUE TITLE
Loading svg from url

### ISSUE THREAD

**Issue by brzi-subasa** [SVGKit/SVGKit#503]
This is code I'm using for loading svg into UIImageView. After running an app myImageView is empty, doesn't show an svg. 

`SVGKImage *svgImg = [SVGKImage imageWithContentsOfURL:[NSURL URLWithString:@"https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg"]];
  myImageView.image = svgImg.UIImage;`

What should I do different in order to have this svg showing correctly?

**Comment by adamgit** [comment]
What errors are you getting?

**Comment by brzi-subasa** [comment]
@adamgit I'm not receiving errors, I just can't see svg loaded within UIImageView. If I try with local svg everything is ok.

**Comment by adamgit** [comment]
If there's nothing loaded, there will be errors or warnings.

Otherwise you have an SVG that exclusively uses features that are not
supported, which is possibly but unlikely.

**Comment by brzi-subasa** [comment]
I was using old version 1.2 (only one available with CocoaPods). After adding new version everything works just fine.
Thanks @adamgit
