### ISSUE TITLE
Plans for thread safety?

### ISSUE THREAD

**Issue by lemonkey** [SVGKit/SVGKit#504]
Are there any plans to update the framework so that it is thread safe? The parsing of the SVG XML is definitely not thread safe in its current implementation and I tend to see issues with this more on iOS 10 vs. iOS 8 or 9.

Specifically, within SVGKParser.m -getCurrentlyParsingParser() 

```
/** This is a workaround to the major, catastophic bugs in libxml that you cannot
 attach a "context" object to libxml parser - and without that, you can't actually
 parse, because you have no reference to the context of your original "parse" call. ARGH!
 */
SVGKParser* getCurrentlyParsingParser()
{
	/** Currently implemented NON THREAD SAFE using a static varailbe that only
	 allows one parse in memory at a time:
	 */
	return [[NSThread currentThread].threadDictionary objectForKey:kThreadLocalCurrentlyActiveParser];
}
```

**Comment by adamgit** [comment]
Amusingly, that appears to be thread-safe within any single thread -
contrary to what all the comments say.

Possibly the person who added the thread-local wasn't sure it would work?
Or hadn't checked it for actual thread-safety?

Or possibly libxml does something nasty internally and is genuinely broken
(there are some bugs in the versions of libxml that Apple packages in iOS)
when run in a multi-threaded environment.

Off the top of my head, the only dependencies on single-threading we have
are:

1. does libxml crash/corrupt data internally? (I've no idea! But the
version Apple ships is very very old)
2. how do we get a reference to the current SVGKParser object that the
(asynchronous) parsing code is filling-in?

The context-pointer in libxml, that was invented to solve these issues,
used to be broken, causing the comments above. Maybe it still is. Maybe
it's not. Maybe there's a fixed version.

...even if it's fixed, c.f. point 1 above: I'm suspicious of libxml's
quality for anything MT. Maybe we can upgrade to a newer version of libxml
(surely Apple offers a new version now, the one we've been using is iOS was
out of date even on the iPhone4!)

**Comment by lemonkey** [comment]
@adamgit Thanks for your prompt feedback.

I have a situation with SVGs that can be loaded either locally from resources in the project or from the server for assets that can change dynamically. 

With iOS 10 I've started to notice issues related to multithreading where if a local SVG asset is being parsed on the main thread while a server hosted SVG is being parsed on a background thread that doesn't show up on iOS 8 or 9.

It would be worthwhile to investigate how things might improve if the version of libxml were to be updated within the SVGKit library.

**Comment by lemonkey** [comment]
It's not clear what version of libxml iOS 10  is shipping with in the iOS SDK:

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/usr/lib/libxml2.tbd

platform: ios
install-name: /usr/lib/libxml2.2.dylib
current-version: 10.9
compatibility-version: 10.0

$ otool -L /usr/lib/libxml2.2.dylib 
/usr/lib/libxml2.2.dylib:
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 57.1.0)
	/usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

But there's definitely a newer version if I check what version of libxml is being used by other tools such as xmllint I see 2.9.4:

`
xmllint: using libxml version 20904
`

Per [this StackOverflow post](http://stackoverflow.com/questions/3818723/can-i-call-libxml-parser-from-multiple-asynchronous-network-calls):

> Starting with [2.4.7](http://xmlsoft.org/threads.html), libxml2 makes provisions to ensure that concurrent threads can safely work in parallel parsing different documents. There is however a couple of things to do to ensure it:
> * configure the library accordingly using the --with-threads options
> * call xmlInitParser() in the "main" thread before using any of the libxml2 API (except possibly selecting a different memory allocator)

**Comment by lemonkey** [comment]
On second look, while an iOS app's execution was paused, I checked the headers for libxml and am seeing at least 2.9.0 being referred to within tree.h for LIBXML2_NEW_BUFFER:

>  * Macro used to express that the API use the new buffers for
>  * xmlParserInputBuffer and xmlOutputBuffer. The change was
>  * introduced in 2.9.0.

**Comment by adamgit** [comment]
Well ... Apple might deceive in the filename simply to ensure that people
who linked against 2.2 by accident (instead of against 2.anything) are
forced into using whichever version Apple has decided to actually ship.
This is the opposite of what they're supposed to do :) but I wouldn't be
surprised if they did it.

I suggest do a little debugging with your MT situation and breakpoints
around the code that fetches/updates/sets the SVGKParser object in the
libxml callbacks. It might be as simple as there's a few places (or even
just once place!) where we're accidentally sharing a pointer across threads
and shouldn't be.

Alternatively, it may be that the ThreadLocal storage doesn't work as
expected, and we need to write some code to manually manage a list of
"currently in-progress parses", which manages the list of SVGKParser
objects, and intelligently returns the right ones. Off the top of my head:
wrapping all libxml calls in separate GCD queues would be a clean and
fairly simple way to achieve this "Correctly".

**Comment by lemonkey** [comment]
SVGKParser.m -parseSynchronously seems to not be as thread-safe as it thinks it is. Per the method comments:

>  This MIGHT now be safe to call multiple times on different threads
>  (NB: the only reason it wasn't safe before was major bugs in libxml
>  that break libxml in horrible ways, see the source code to this class
>  for more info)

Where it fails for me is on the following line:

`ctx = xmlCreatePushParserCtxt(&SAXHandler, NULL, NULL, 0, NULL); // NEVER pass anything except NULL in second arg - libxml has a massive bug internally
`

where SAXHandler is currently being defined as a static xmlSAXHandler variable for the class. 

In general, others have seen MT issues with libxml2 and the [following](http://stackoverflow.com/questions/3818723/can-i-call-libxml-parser-from-multiple-asynchronous-network-calls) is basically the same error I'm seeing, with [this comment](http://stackoverflow.com/questions/3818723/can-i-call-libxml-parser-from-multiple-asynchronous-network-calls#comment4092756_3818723) being somewhat telling in relation to how SAXHandler is a static variable in SVGKParser.

**Comment by lemonkey** [comment]
I agree with your idea for "wrapping all libxml calls in separate GCD queues", possibly within a new -parseAsynchronously method within SVGKParser.

**Comment by lemonkey** [comment]
FYI, in my case it turns out that the issue was related to not using SVGKImage +imageWithData but instead using [[SVGKImage alloc] initWithData:. The former has an implementation that uses @synchronized(self) and this resolved the issue in my case.

However, SVGKParser.m does have logic that uses thread containment to at least try to prevent multithreading issues (see getCurrentlyParsingParser() and -parseSynchronously), albeit in a less than ideal way. 

Error logging (see -parseSynchronously) shows that until someone wraps libxml to be multi-threaded, SVGKit will remain single-threaded for now.

**Comment by adamgit** [comment]
Any obvious way to upgrade initWithData to use synchronization as well?

**Comment by adamgit** [comment]
Or ... to detect a possible non-threadsafe use of it, and output an error
log suggesting ppl use the other method?
