### ISSUE TITLE
why this svg draw incorrect? Thanks!

### ISSUE THREAD

**Issue by vasilykharitonov** [SVGKit/SVGKit#51]
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   version="1.1"
   width="744.09448"
   height="1052.3622"
   id="svg3040">
  <defs
     id="defs3042" />
  <metadata
     id="metadata3045">
    rdf:RDF
      <cc:Work
         rdf:about="">
        dc:formatimage/svg+xml/dc:format
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        dc:title/dc:title
      /cc:Work
    /rdf:RDF
  </metadata>
  <g
     id="layer1">
    <rect
       width="271.42856"
       height="245.71428"
       x="51.42857"
       y="100.93361"
       id="rect3048"
       style="opacity:0.35447765;fill:#ff8c00;fill-opacity:1;fill-rule:nonzero;stroke:none" />
    <rect
       width="331.42856"
       height="297.14285"
       x="151.42857"
       y="206.6479"
       id="rect3050"
       style="opacity:0.35447765;fill:#ff8c00;fill-opacity:1;fill-rule:nonzero;stroke:none" />
    <rect
       width="405.71429"
       height="234.28572"
       x="188.57143"
       y="415.21933"
       id="rect3052"
       style="opacity:0.35447765;fill:#ff8c00;fill-opacity:1;fill-rule:nonzero;stroke:none" />
  </g>
</svg>

**Comment by adamgit** [comment]
What's wrong with it?

**Comment by vasilykharitonov** [comment]
These boxes have transparency, but the image is opaque.
I use 2013base
and code:
[self.view addSubview: [[SVGKFastImageView alloc] initWithSVGKImage: [SVGKImage imageNamed:@"1.svg"]]];

**Comment by adamgit** [comment]
OK, thanks, I think I found the problem.

Please try SVGKit master now - see if it has fixed it? - https://github.com/SVGKit/SVGKit/

**Comment by vasilykharitonov** [comment]
Now, compile fails on: 

...BaseClassForAllSVGBasicShapes.h:20:9: 'SVGTransformable.h' file not found

**Comment by adamgit** [comment]
Sorry, that's an Xcode bug - I did a "clean" and "build" but sometimes Apple's Xcode screws up :(.

(Xcode was excluding that file from the build, an Apple bug they haven't fixed for a long time)

I've manually re-added the hedaer file - try now

**Comment by vasilykharitonov** [comment]
Thanks! Works good!
