### ISSUE TITLE
Images not loads in tableview?

### ISSUE THREAD

**Issue by GopiK14** [SVGKit/SVGKit#510]
Hi All,

I have loaded svg image icons inside tableview cell through background thread, But Its not correctly load. Sometimes it fails to load, Any suggestion to use svgkit in tableview cell.
Thanks!

**Comment by vitalii-tym** [comment]
I haven't had much problems using svg icons in tableView or collectionView. Try to add some caching, make sure you correctly work with the tableCell lifecycle (I mean its reusability), debug the networking part of your code.
Try to test with non-SVG images if you seriously believe it might be related to SVGKit and give more background or debugging info to help the community help you.

**Comment by adamgit** [comment]
You don't get any errors?

**Comment by GopiK14** [comment]
@vitalii-tym  Thanks For your response!
Please check below code I have used in my app and let me know if any changes to be done to make svg work in tableview,

 dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^(void) {
        SVGKImage *svgImage = [SVGKImage imageWithContentsOfURL:[NSURL URLWithString:cImage]];
        SVGKImage *svgLevelImage = [SVGKImage imageWithContentsOfURL:[NSURL URLWithString:levelImage]];
        dispatch_sync(dispatch_get_main_queue(), ^(void) {
            [cell.categoryIcon setImage:svgImage.UIImage];
            [cell.levelIcon setImage:svgLevelImage.UIImage];
        });
    });


As you said, "Try to add some caching," -> I believe there is no cache option in this library. Can you please give some suggestion how to handle cache? 

Thanks!

**Comment by GopiK14** [comment]
@adamgit Yes, I didn't get any errors but sometimes it crash if network is too slow. Please check my code added in above comment. Please suggest if anything i need to change.

Thanks!

**Comment by adamgit** [comment]
The way you're invoking SVGKit looks correct.

We can't debug the rest of your program for you. You need to debug your own
code. If it crashes because  "network too slow" then that's a problem you
need to look into.

**Comment by vitalii-tym** [comment]
-> imageWithContentsOfURL
I remember I had problems with this method and ended up making URL requests on my own using SVGKit only to init SVGKImage with the NSData.
But I can't recall what exactly was the issue and don't have spare time for experiments right now.

@GopiK14 It would be good if you could dig deeper and give some more background about the crash you experience.

By saying "caching" I meant it in general, not related to SVGKit. The default cachePolicy relies on info from server. Check the server response. If it has "Cache-Control" = "no-cache..." - it means no caching used at all. You need to either force the cachePolicy or use URLCache or something like this.
Also mind the tableCell reusability: by the time SVGImage is fetched from network the cell might be allocated for completely another item. This will result in blinking, blank images, or sometimes crashes too.

**Comment by GopiK14** [comment]
@adamgit Thanks!

**Comment by GopiK14** [comment]
@vitalii-tym Thanks! Will try to do cache. Also light color images not shown with white color background. Do u have any idea about it?
