### ISSUE TITLE
SVGKit-iOS-Prefix.pch:7:1: Use of '@import' when modules are disabled

### ISSUE THREAD

**Issue by hyfFocus1** [SVGKit/SVGKit#512]
I have cloned the repertory，and build the SVGKit-iOS.xcodeproj.then the issue acurred.
![111111111](https://cloud.githubusercontent.com/assets/12823581/23011429/e9080846-f45b-11e6-8197-7292956fae9c.png)

**Comment by hyfFocus1** [comment]
my xcode versio is 8.2.1

**Comment by sushihangover** [comment]
@hyfFocus1  Enable Modules in the build setting:

![screen shot 2017-02-16 at 12 04 51 am](https://cloud.githubusercontent.com/assets/1294194/23012560/aaf9f2ba-f3db-11e6-8d9c-b324ff89a6f8.png)

**Comment by adamgit** [comment]
If that's the fix, then previous Pull Request was incorrect - can you
please add a pull request for this and I'll approve? (I only have mobile /
web access today, no Xcode)

**Comment by sushihangover** [comment]
@adamgit  I maintain a `Xamarin.iOS` binding to allow the use of `SVGKit` via `C#` and that is the fix that I had to do to build/test `SVGKit` with the CocoaLumberjack changes introduced in PR# https://github.com/SVGKit/SVGKit/pull/511 before I could roll into an update of the bindings...

I created a PR: https://github.com/SVGKit/SVGKit/pull/513

**Comment by adamgit** [comment]
Thanks @sushihangover - merged.

@hyfFocus1 - checkout latest version - please confirm if this fixed the issue for you.

**Comment by hyfFocus1** [comment]
@adamgit @sushihangover OK, it works!

**Comment by coolwxb** [comment]
@sushihangover 
I have the same error, I setup my podfile to get svgkit from  2.x branch and I also checked Enable Modules in the build setting,but still have the same issue.
<img width="901" alt="wx20170217-180143 2x" src="https://cloud.githubusercontent.com/assets/5254163/23061034/2e9563f6-f53b-11e6-9556-237aeb99f650.png">
<img width="929" alt="wx20170217-180254 2x" src="https://cloud.githubusercontent.com/assets/5254163/23061060/547cb146-f53b-11e6-92e0-a787c4f85acd.png">
<img width="1103" alt="wx20170217-180321 2x" src="https://cloud.githubusercontent.com/assets/5254163/23061070/61832ffa-f53b-11e6-9532-92d14a7ccc8c.png">

**Comment by adamgit** [comment]
Cocoapods is not supported. I suggest using something less buggy, e.g. Carthage.
