### ISSUE TITLE
Get Element from Layer

### ISSUE THREAD

**Issue by charvoa** [SVGKit/SVGKit#517]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [X] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [X] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [X] I am not using CocoaPods, or: I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps

Hi,

I wonder how should one be able to get a particular Element* from a layer. 

I know how to handle tap on Layer. But the problem is that I would like to know which Element has been tapped in order to display information. 

For example : I have a US map, and if I touch the layer of  California I would like to display a Toast message "It's California". 

This is what I have tried so far : 

```
-(void) handleTapGesture:(UITapGestureRecognizer*) recognizer {
    CGPoint p = [recognizer locationInView:self.view];
    
    CALayer* layerForHitTesting;
    layerForHitTesting = imageView.layer;
    
    
    CALayer* hitLayer = [layerForHitTesting hitTest:p];
    
    
    
    if( hitLayer == lastTappedLayer ) {
        [self deselectTappedLayer];
    }
    else {
        [self deselectTappedLayer];
        lastTappedLayer = hitLayer;
    }
    
    if( lastTappedLayer != nil )
    {
        lastTappedLayerOriginalBorderColor = lastTappedLayer.borderColor;
        lastTappedLayerOriginalBorderWidth = lastTappedLayer.borderWidth;
        
        lastTappedLayer.borderColor = [UIColor greenColor].CGColor;
        lastTappedLayer.borderWidth = 3.0;
    }
    /// THE ABOVE WORKS PERFECTLY

    /// THIS IS WHAT I HAVE TRIED 
    SVGDocument *document = newImage.DOMDocument;
    
    for (Element *element in document.documentElement) {
        SVGElement* SVG_element = (SVGElement*) element;
        CALayer* layer = [newImage layerWithIdentifier:SVG_element.identifier];
        if (layer == hitLayer) {
            NSLog(@"ALLO");
        }
        
    }
}
```

Thanks for yor help !

**Comment by adamgit** [comment]
Have you seen the recipes linked from the main SVGKit webpage here, in the
instructions at bottom?

Off the top of my head, they contain an example of how to fetch this using
convenience methods I added a few years ago.

Your approach looks generally correct to me - but IIRC we attached a
special local variable, via a custom magic key, to keep the direct
connection between Layer and Element. Have a look at the source for
SVGElement and the extension headers for it.

**Comment by charvoa** [comment]
In the recipe the only thing I can find is how to get Layer from Element, but I want the opposite. Like a function call to getElementFromLayer.

**Comment by charvoa** [comment]
@adamgit  If I could get a simple working example that would be great because I did not get what you said before. Thanks for your help again !

**Comment by adamgit** [comment]
I don;t have access to a mac with xcode at the moment, so I'm not the best
person to help right now, sorry :(

**Comment by charvoa** [comment]
I will open a new issue as I think I discovered one. Thanks for your help.
