### ISSUE TITLE
Cannot get kSVGElementIdentifier from CALayer 

### ISSUE THREAD

**Issue by charvoa** [SVGKit/SVGKit#518]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [X] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [X] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [X] I am not using CocoaPods, or: I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps

I had open a previous issue stating that I wasn't able to find a particular Element knowing its CALayer. I found a way to get the information about the Element using the name property of the CALayer (layer.name). But I also found this : [ConverterSVGToCALayer.h](https://github.com/SVGKit/SVGKit/blob/2.x/Source/DOM%20classes/Unported%20or%20Partial%20DOM/ConverterSVGToCALayer.h) which states : 

> the returned layer has - as its "name" property - the "identifier" property of the SVGElement that created it;
 but that can be overwritten by applications (for valid reasons), so we ADDITIONALLY store the identifier into a
 custom key - kSVGElementIdentifier - on the CALayer. Because it's a custom key, it's (almost) guaranteed not to be
 overwritten / altered by other application code

Unfortunately I was not able to use :

`        NSLog(@"%@", [lastTappedLayer valueForKey:@"kSVGElementIdentifier"]);
`

As it returns null .. But the name property is working fine : 

`        NSLog(@"%@", lastTappedLayer.name);
` 
I am using a US map to test the framework so when I click on a state it prints the ID which is the abbreviation of the state : 

> 2017-03-16 18:59:39.871 SVGProject[52760:3066594] (null)
> 2017-03-16 18:59:39.872 SVGProject[52760:3066594] NM

(First line using  kSVGElementIdentifier.
Seconde line using name property.)

Maybe a fix in order to safely get the ElementIdentifier of the CALayer ? 

Thanks !

**Comment by adamgit** [comment]
Good find. Can you breakpoint the setting of that property (should be only
set in one or two places, I think?) and see why it's being set to null?

Maybe breakpoint wherever the layer.name is set too, see what the
difference is.

NB: I expect this is a new bug, a small typo in an unrelated change that
has caused this to stop working.

**Comment by charvoa** [comment]
This is my fault. Regarding the "SVGGroupElement.m" file the key is not a NSString, I am not used to using key and I thought it would be a NSString. Sorry for that. But thanks for pointing me in the right direction.
