### ISSUE TITLE
SVG Render Quality

### ISSUE THREAD

**Issue by victorstewart** [SVGKit/SVGKit#525]
Is there an ability to scale up the quality of the render? 

I converted a PNG to SVG with imagemagick. Both formats look crisp and clear in safari, but when I try to render both on iOS... the PNG is still crisp, but the SVG renders blurry.

Using the standard implementation:

```
SVGKFastImageView *svgView = [[SVGKFastImageView alloc] initWithSVGKImage:[SVGKImage imageNamed:@"nicola"]];

svgView.frame = CGRectMake(screenWidth * 0.20, screenWidth * 0.07, screenWidth * 0.15, screenWidth * 0.15);

[self.view addSubview:svgView];
```

the rendering difference:
![img_0267 png](https://cloud.githubusercontent.com/assets/17534897/25728371/9be629e8-30fc-11e7-8789-bd864adb7192.png)

the png:
![nicola](https://cloud.githubusercontent.com/assets/17534897/25728379/ac15fd98-30fc-11e7-81cd-f3ca6e171a0f.png)

the SVG:
https://www.dropbox.com/s/15g1vcknde3ge6m/nicola.svg?dl=0

**Comment by adamgit** [comment]
Can you share the SVG file? Dropbox hides it in a web page, there's no SVG
there.

**Comment by victorstewart** [comment]
there's actually a download link in the top right of the page, i just checked

but here it is on another site: http://s000.tinyupload.com/index.php?file_id=62576568386554993924

**Comment by adamgit** [comment]
Thanks, I see the button now - it's badly designed, almost as if they don't
want you to discover it ;). Most people link the file, not a webpage that
requires extra steps to find the file.

Anyway, looking at the source, it's merely an embedded base64 bitmap. The
only SVG part is a single embed-bitmap command.

That's nearly all handled by Apple's code, so I'm surprised it's
downscaling - it ought to Just Work.

 What happens in the debugger? Does it resize the bitmap?

**Comment by victorstewart** [comment]
I had the same thought when you didn't see it. And  they used to just link the file. Oh well.

Haha that explains my confusion about the formatting of the svg when I looked inside. You don't happen to have any other recommendations for PNG to SVG conversion then do you?

Ridiculous enough, breakpoints are broken in my XCode... so I can't use the debugger lol. I tried to fix it for a few hours (bc of another SVGKit issue I filed) then just moved on. Haven't had the time to go back and mess with it since.

**Comment by adamgit** [comment]
I haven't used the bitmap-in-SVG embedding myself, but I remember when
someone added it - they included some test images with the PR, and
everything appeared to be working fine. So I'm surprised it's not working
correctly in this case.

You're never going to have much success converting a photo to a vector
file, unless you use an expensive commercial tool to do it. Without that,
the best I'd aim for is a posterized version: reduce the pallette of the
photo so its only - say - 16 colours, then run an open-source tracer on it,
and that will give you one path per colour, which will export into an SVG
very nicely. But obviously not looking at all like a photo!

**Comment by victorstewart** [comment]
Not really much of an issue then bc I'll just use PNGs. I wanted to use SVGs to harness perfect scaling... haha but I was tricked.

On the photo -> vector, sounds like an awesomely useful open source project I'd love to take part in tackling lol

**Comment by adamgit** [comment]
You'd be trying to create data that doesn't exist - you can't magically 
make a higher res photo than the photo you started with.

There are many PhD s in that topic, and there are commercial.products that 
try various approximations. There might be some open source implementations 
by now, if you look into Image Synthesis or similar.
