### ISSUE TITLE
NSCharacterSet SVGWhitespaceCharacterSet unrecognized selector sent to class (for project!)

### ISSUE THREAD

**Issue by coamw2** [SVGKit/SVGKit#526]
I have a project which uses many SVGs and uses SVGKit.The app is on the store.
I have SVGKit framework, and CocoaLumberjack, as an embedded binary.
I have all the other frameworks linked that are suggested to be linked (e.g CoreGraphics). 
I have -Objc for Other Linker Flags in the build settings.

The app crashes on iPhone SE or iPhone 7. I saw the issue was SVGKit so updated/built/copied to my project. Everything else is the same but now the app crashes on the first SVG image it tries to load with the error: +[NSCharacterSet SVGWhitespaceCharacterSet]: unrecognized selector sent to class.

Any help appreciated.

**Comment by adamgit** [comment]
That sounds like you have a very old version of SVGkit.

What version are you running?

**Comment by coamw2** [comment]
Apologies, I have just solved the issue. I had to delete the SVGKit.framework from my project and then re-add it. Simply dragging and dropping the new version was not enough.

**Comment by adamgit** [comment]
How long ago was your last update?

Perhaps the build settings had changed since then, and delete/readding 
causes xcode to pick them.up, where overwriting means it doesn't  notice?

**Comment by coamw2** [comment]
At latest June 2016, that's when I released the app, but was likely months earlier (I'm not sure how I can see what version I had from the old .framework)

Not picking up build settings sounds plausible, or not picking up the new files in the project perhaps. I have built a framework that uses SVGKit, and then my projects use _that_ framework, which makes things a little more complicated.
