### ISSUE TITLE
Is the drawing result GPU hardware accelerated?

### ISSUE THREAD

**Issue by trusktr** [SVGKit/SVGKit#535]
?

**Comment by adamgit** [comment]
If you render CALayers - yes, Apple accelerates their CoreAnimation library.

If you render a bitmap up to 2kx2k - yes, you can't display a bitmap on iOS
without this happening.

... over 2k x 2k - I don't know. For this case, Apple used not to
accelerate anything, but I think they do now?

**Comment by trusktr** [comment]
Hello @adamgit, I'm talking about the actual creation of the pixels defined by the SVG. For example, I want to animate SVG paths and shapes, not just the resulting texture. Is that part accelerated?

**Comment by adamgit** [comment]
SVG's don't have pixels. I don't know what you're thinking of. Have you
tried using the library yet?

**Comment by trusktr** [comment]
Everything eventually ends up as pixels. Somehow, the SVG data (f.e. an `<svg>` element in a browser DOM) needs to be rendered into pixels for a given resolution, in order to be able to be presented on the screen. When a circle's radius is modified (for example) then a new set of pixels needs to be calculated.

Do these calculations happen on the GPU?

I know that static textures can be animated on the GPU. But that's not what I'm wondering about.

To animate an entire SVG image in the GPU, a texture created *from* the SVG spec can be passed to the GPU, and placed on a mesh (a Quad for example). I'm not talking about that sort of acceleration.

I am wondering if SVGKit hardware accelerates the process of taking an SVG spec and creating pixels from it. I'm not wondering about how to accelerate the transformation of those pixels after that point.

Do you know what I mean?

**Comment by adamgit** [comment]
It sounds like you're asking about CALayers, which was the first bit I
mentioned. SVGkit out-of-the-box lets you choose between using CALayers or
using bitmaps.

**Comment by trusktr** [comment]
I am asking if the generation of the pixels that are rendered from the SVG is accelerated. Is it accelerated?

**Comment by adamgit** [comment]
Do you know what a CALayer is?

**Comment by adamgit** [comment]
"I am asking if the generation of the pixels that are rendered from the SVG is accelerated."

This makes no sense. Why would you accelerate a pixel? That's guaranteed to be slower than NOT accelerating it: you cannot move data to the GPU as fast as you can render it on the CPU.

And on Apple hardware (which SVGKit runs on exclusively) the GPU and CPU are the same chip, so ... what would "accelerated" mean?

**Comment by trusktr** [comment]
A [CALayer](https://developer.apple.com/documentation/quartzcore/calayer) seems to be a class for controlling and animating a texture (or hierarchy of textures) on the GPU. Is that right?

Are you implying that you render each SVG primitive onto it's own CALayer? How do you do that?

For example, to accelerated the creation of a `<circle></circle>` SVG element in plain GL (OpenGL ES for example), one would create a circle using triangles specified with a vertex shader, then fill in the triangles using a fragment shader executed for each triangle of the circle.

To draw SVG manually and accelerated, we must first determine the dimensions of the pixel array (f.e. 640 by 480) that we wish to render a given SVG spec into. Then we must parse the `<svg>` document in order to determine what primitives to draw. So we see `<circle>`s, `<rect>`s, etc, and we must draw those. For a rect, we create two triangles and put them together to make a rectangle on the GPU with vert shaders, then we fill it in with frag shaders.

This is what I mean by hardware accelerated.

We have two options:

1. convert an SVG spec into pixels on the GPU,
2. or on the CPU

Either way we can pass those generated pixels into a `CALayer`, which is not what I am concerned about.

Does SVGKit use the GPU to draw SVG? I'm not talking talking about animating textures after drawing SVG.

I haven't coded for iOS before. Do CALayers give you drawing APIs to draw circles, lines, etc? And are the calculations that determine those pixels on the CPU or the GPU?

If not, and based on what I read, then CALayers are simply a toolkit for animating hierarchies of textures inside a GPU, which I know how to do manually.

I am asking about how those textures are created before they are used as textures.

**Comment by trusktr** [comment]
Maybe if you just describe how SVGKit renders SVGs then that will answer the question?

**Comment by trusktr** [comment]
I just did some research. I think you're using Core Graphics to draw the SVG primitives, and those are [not hardware accelerated](https://robots.thoughtbot.com/designing-for-ios-graphics-performance) based on the article, Core Graphics and other things are rasterized on the CPU, not on the GPU.

> In the case of CALayers, they wrap around rasterized bitmaps of the Core Graphics drawing

This they wrap around the rasterized result of an SVG, they don't accelerate the rasterization of the SVG.
So the answer is no, SVG rasterization does not happen on the GPU, and animating values of SVG primitives (circle radius, path curves, etc) can get really slow compared to if they were rendered on the GPU.

**Comment by trusktr** [comment]
For an example of a libraries that rasterize SVGs in the GPU, check out:

- [Pixi.js](https://github.com/pixijs/pixi.js/) paired with [pixi-svg](https://github.com/bigtimebuddy/pixi-svg/) (most incomplete SVG feature support)
- [Two.js](https://github.com/jonobr1/two.js)
- [MonkVG](https://github.com/micahpearlman/MonkSVG) paired with [MonkSVG](https://github.com/micahpearlman/MonkSVG) (most complete SVG feature support)

These three libraries triangulate and rasterize graphics on the GPU, while Core Graphics does not (as of 2012 as mentioned in that article, and I haven't found anything more recent yet).

**Comment by trusktr** [comment]
Here is further evidence: https://stackoverflow.com/a/7559897/454780

That answer states that CALayer host textures, and it makes sense that those textures can be animated in an accelerated fashion on the GPU, but the creation of those textures (with Core Graphics) is not accelerated.

**Comment by trusktr** [comment]
One [answer](https://stackoverflow.com/a/32567326/454780) states that Core Graphics on iOS 9 are built on top of Metal, which might possibly mean that recent upgrades have moved rasterization into the GPU.

It is worth knowing this stuff, because you don't want to just animate SVGs thinking it will be fast.

**Comment by adamgit** [comment]
What you're describing is not called "rasterization", nor "rendering", nor any of those things. The term you're looking for is "tesselation" -- i.e. the conversion of graphics into triangles (on CPU), and then allowing the GPU to decide how/what to render.

"we must first determine the dimensions of the pixel array "

- no, to do what you describe, you would never do that. GPU's *do not use pixels*. You need to stop thinking in terms of pixels

"Do CALayers give you drawing APIs to draw circles, lines, etc?"

- yes, and they've been hardware accelerated for many, many, MANY years.

"I think you're using Core Graphics"

- No. Core Graphics classes begin with the letters "CG"
- CALayer does not begin with "CG", it begins with "CA"
- ...which shows we're using CoreAnimation

We also use CoreGraphics, but CoreGraphics is a lot more than the article claims - it also contains data structures e.g. CGFloat - which have nothing to do with CPU or GPU.

**Comment by adamgit** [comment]
So ... to ask and answer the question I think you wanted...

Q: Does SVGKit have an option to do Tesselation?
A: No. But if you want to tesselate, it's very easy to add. We provide two different rendering layers, which are swappable (and we use them for testing each other - if something renders in one but not the other, it's a bug and we can rapidly track it down). You can add your own rendering layer very easily and use it with a single line of code. You get to re-use SVGKit's parsers, file handlers, logic (click / touch detction), semantics, etc.

**Comment by adamgit** [comment]
The magic method to look into is SVGKImage.CALayerTree - that triggers generation of a CALayers render output, and shows you how you could do it yourself; you can write your own alternative method that performs the same looping, but reacts differently each time it finds an SVGKElement class in the tree.

**Comment by trusktr** [comment]
I see how newCALayerTree calls newLayerWithElement. From there, what does newLayerWithElement call that makes the drawing of (for example) a circle path? I haven't coded Objective C before, so maybe I'm not visually seeing it.

**Comment by adamgit** [comment]
At the moment, each subclass of SVGElement has a callback where it renders 
itself using Apple's CALayer API.

Ideally, we should move those callbacks to a separate set of classes, so 
rendering is 100% separate from parsing and data storage - but it doesn't 
do any harm where it is.

You can easily create you own call system that iterates over the SVGElement 
tree the same way that CALayerTree does, but calls your own render methods 
- or uses one big method - however you like.
