### ISSUE TITLE
'Your subclass implementation is broken, it should be calling [super init]

### ISSUE THREAD

**Issue by sujayun** [SVGKit/SVGKit#538]
Using swift 2.3 and Xcode 8

I am creating ImageView from SVG but getting an error :
      
     let SvgImgVar = SVGKImage(named: setSvgVar)
        
     let SvgImjVyuVar = SVGKImageView(SVGKImage: SvgImgVar)

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Your subclass implementation is broken, it should be calling [super init] not [super initWithSVGKImage:]. Instead, use a subclass e.g. SVGKFastImageView'
*** First throw call stack:

**Comment by adamgit** [comment]
What's the problem? This report appears to be empty.

**Comment by sujayun** [comment]
Sorry

I was new to Github
So dint knew how to edit first.

I have updated the issue

**Comment by sujayun** [comment]
Sorry

I was new to Github
So dint knew how to edit first.
I have updated the issue Thanks and Regards  Sujay U N+91-9964120147Web: sujayun.cf

**Comment by adamgit** [comment]
This is a typo in your code. You've tried to use a class that doesn't exist.

The error message even gives you a suggestion about a real one you can use!

**Comment by sujayun** [comment]
SVGKImageView image view was there in all previous versions.

But is the different between SVGKImageView and SVGKFastImageView

**Comment by adamgit** [comment]
There has never been a straight class called SVGKImageView.

There has always been an abstract class - i.e. something like an interface
- with multiple implementations. You need to use one of the subclasses.
This hasn't changed.
