### ISSUE TITLE
dyld: Library not loaded: @rpath/SVGKit.framework/SVGKit

### ISSUE THREAD

**Issue by quinn** [SVGKit/SVGKit#545]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [x] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [x] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [x] I am not using CocoaPods, or: I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps

```
dyld: Library not loaded: @rpath/CocoaLumberjack.framework/CocoaLumberjack
  Referenced from: /Users/quinn/Library/Developer/CoreSimulator/Devices/D701106F-E571-4F10-AFB1-EACB2DDBB9D2/data/Containers/Bundle/Application/5F4BD5F0-DB78-4DAC-9987-4CB236EDF388/SolSearch.app/Frameworks/SVGKit.framework/SVGKit
  Reason: image not found
```

target settings:

![image](https://user-images.githubusercontent.com/3764/30131128-9d6bd630-9319-11e7-961f-ac154308d37b.png)

I dragged / dropped framework after building it from `SVGKit-iOS.xcodeproj`.

**Comment by adamgit** [comment]
It would appear you are building Lumberjack as a framework too, in which
case you'd need to drag/drop that as well?

**Comment by quinn** [comment]
Whoops, I skimmed that, thought it said the same thing as the other one. thanks!
