### ISSUE TITLE
i met a problem that svg file show incorrect 

### ISSUE THREAD

**Issue by zhanglei1239** [SVGKit/SVGKit#566]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [x] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [x] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [x] I am not using CocoaPods, or: I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by zhanglei1239** [comment]
hello  i use svgkit with a problem. i want to know if the SVGKit compatible for tag <filter>. There is a <filter> tag show a shadow and GaussianBlur effect in my svg file,and when i show the picture with svgkit .  the shadow and GaussianBlur was missing.

**Comment by adamgit** [comment]
What do you mean by "tag"?

Tag usually means the elements inside an SVG file. Perhaps you mean "does it support shadows and blur?".

If either is missing, they should be very easy to add - Apple provides direct support for both technologies, and it would work similarly to the existing code for Gradients (But is probably much simpler).

**Comment by dreampiggy** [comment]
Fix via #584
