### ISSUE TITLE
can't rander in SVGKit

### ISSUE THREAD

**Issue by miku1958** [SVGKit/SVGKit#575]
* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [x] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [x] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [x] I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps

I have a svg whitch is optimized ,the content is 

```
<svg id="Icons" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><defs><style>.cls-1{fill:#ffe500;}.cls-2{fill:#ebcb00;}.cls-3,.cls-6{fill:#45413c;}.cls-3{opacity:0.15;}.cls-4,.cls-5{fill:none;}.cls-4,.cls-5,.cls-6{stroke:#45413c;stroke-linecap:round;}.cls-4,.cls-6{stroke-linejoin:round;}.cls-5{stroke-miterlimit:10;}.cls-7{fill:#ffaa54;}.cls-8{fill:#fff48c;}</style></defs><title>18-slightly-smiling-face</title><g id="_Group_" data-name="&lt;Group&gt;"><circle id="_Ellipse_" data-name="&lt;Ellipse&gt;" class="cls-1" cx="24" cy="21.5" r="20"/><path id="_Compound_Path_" data-name="&lt;Compound Path&gt;" class="cls-2" d="M24,1.5a20,20,0,1,0,20,20A20,20,0,0,0,24,1.5Zm0,37A18.25,18.25,0,1,1,42.25,20.25,18.25,18.25,0,0,1,24,38.5Z"/><ellipse id="_Ellipse_2" data-name="&lt;Ellipse&gt;" class="cls-3" cx="24" cy="45.5" rx="16" ry="1.5"/><circle id="_Ellipse_3" data-name="&lt;Ellipse&gt;" class="cls-4" cx="24" cy="21.5" r="20"/><path id="_Path_" data-name="&lt;Path&gt;" class="cls-5" d="M29,29.48a9,9,0,0,1-10,0"/><path id="_Path_2" data-name="&lt;Path&gt;" class="cls-6" d="M14.5,20.5a1,1,0,1,1-1-1A1,1,0,0,1,14.5,20.5Z"/><path id="_Path_3" data-name="&lt;Path&gt;" class="cls-6" d="M33.5,20.5a1,1,0,1,0,1-1A1,1,0,0,0,33.5,20.5Z"/><path id="_Path_4" data-name="&lt;Path&gt;" class="cls-7" d="M38.5,26.5c0,.83-1.12,1.5-2.5,1.5s-2.5-.67-2.5-1.5S34.62,25,36,25,38.5,25.67,38.5,26.5Z"/><path id="_Path_5" data-name="&lt;Path&gt;" class="cls-7" d="M9.5,26.5c0,.83,1.12,1.5,2.5,1.5s2.5-.67,2.5-1.5S13.38,25,12,25,9.5,25.67,9.5,26.5Z"/><ellipse id="_Ellipse_4" data-name="&lt;Ellipse&gt;" class="cls-8" cx="24" cy="5.5" rx="6" ry="1.5"/></g></svg>
```

it come from http://emoji.streamlineicons.com 's slightly-smiling-face , and it is optimized by emoji.streamlineicons.com when you download fullpack

I test in web , finder or any other place is work normally ,  but  it can't be rander in SVGKit ,it become all black in SVGKit like:

![qq20180818-111202](https://user-images.githubusercontent.com/24806909/44295226-910cbe80-a2d7-11e8-9c38-14e95b04515b.png)

and there is the orignal file ,it work fine in SVGKit
http://d1cxtglzz1rb2m.cloudfront.net/emoji/SVG/18-slightly-smiling-face.svg

![qq20180818-111418](https://user-images.githubusercontent.com/24806909/44295247-ddf09500-a2d7-11e8-9b06-ce5e2a3e0ede.png)

**Comment by adamgit** [comment]
Hmm, this is a strange SVG file - that website is generating ugly output. It should still work, but it's a very unusual example! You need to open this in the debugger and see which instructions are failing. It could be the way it tries to embed Html inside SVG (ugh!) or the heavy use of CSS styles where it should be using SVG commands.
