### ISSUE TITLE
SVG FILL COLOR

### ISSUE THREAD

**Issue by ighotouch** [SVGKit/SVGKit#576]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [x] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [x] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [x] I am not using CocoaPods

### Issue Description and Steps

How do you passing in fill color to override SVG image

**Comment by adamgit** [comment]
Export the SVG to CALayers .... e.g. by reading the field "(SVGKImage).CALayertree" (or similar; I am on mobile, might have mispelled that) ... and you can then change the fill in any layer.

And/or find the specific layer you want/need by using the method: "[(SVGKImage) layerWithIdentifier:]" and passing it the id tag in the original SVG document.

...there are many more ways of doing this. If you try reading the links on the front page of the project you'll find different approaches with source code. e.g. http://t-machine.org/index.php/2013/01/02/svgkit-2013-recipes/
