### ISSUE TITLE
Can't compile when adding to a project includes Firebase

### ISSUE THREAD

**Issue by willtr101** [SVGKit/SVGKit#589]
### New Issue Checklist

* [x ] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [ ] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [ ] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [x]I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps
Using the following cocoapods:
`pod 'Firebase/Core'
  pod 'GoogleUtilities'
  pod 'FirebaseFirestore'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'
`
the project won't be able to compile, error `'Firestore/core/src/firebase/firestore/model/field_path.h' file not found`

Similar to this issue https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/768

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by adamgit** [comment]
That file is not part of svgkit, you ned to report this bug to the Firebase 
project, I think?

**Comment by hanumanAbacus** [comment]
@businessengine were you able to solve the issue?

**Comment by package71** [comment]
??
