### ISSUE TITLE
iOS projects not compiling after last commit

### ISSUE THREAD

**Issue by dvanwinkle** [SVGKit/SVGKit#592]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [x] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [x] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [x] I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps

iOS projects are no longer building after the recent commit to 2.x. It's trying to build SVGKExporterNSImage and cannot find the correct headers, as expected.

**Comment by onnoweb** [comment]
PR: https://github.com/SVGKit/SVGKit/pull/593
