### ISSUE TITLE
Tests failing (wrong colors, incomplete rendering)

### ISSUE THREAD

**Issue by lattejed** [SVGKit/SVGKit#6]
Tests failing (wrong colors, incomplete rendering).

**Comment by mattrajca** [comment]
Can you provide the files you are running the tests against?

**Comment by bhoomik** [comment]
yes.True incomplete rendering of files.Even errors like <Error>: CGPathAddLineToPoint: no current point.
while testing some files

**Comment by bhoomik** [comment]
1)http://www-archive.mozilla.org/projects/svg/lion.svg
2)http://coveredincake.com/svgfiles/cupcakewrapper.svg
the above file does not work
second gives error and first does not render images properly

**Comment by Paul69** [comment]
I have the same issue : 
For example the "note.svg" only displays a red circle on a green rectangle. 
And I have <Error>: CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 32 bits/pixel; 3-component color space; kCGImageAlphaNoneSkipLast; 67 bytes/row. when trying "lion.svg".

I'm using Mac OS X 10.6 and have been unable to compile the framework using "Release" option (354 errors found).

**Comment by Paul69** [comment]
Oh sorry : the error I have when loading lion.svg is : 
Inconsistent set of values to create NSBitmapImageRep

**Comment by adamgit** [comment]
Second example works for me now with latest commits I just made (fixes a lot of inkscape files too).

At least, it looks identical in OS X Preview, Inkscape, and SVGKit (except for the missing background image, which is ignored by everything except Inkscape, which shows the "error" in background)

**Comment by adamgit** [comment]
First example also (allegedly) now renders correctly with the CSS fixes from one of the branches - although I haven't tested that myself.

**Comment by adamgit** [comment]
Fixed in both master (about 6 months ago) and in 2013base branch (a month ago)
