### ISSUE TITLE
App crashing after (Feb12) commit

### ISSUE THREAD

**Issue by tomasgatial** [SVGKit/SVGKit#60]
I am getting this error when doing scale convert with this image:
https://dl.dropbox.com/u/25433702/svgImageWithProblems.svg

app crashes with this error

2013-02-28 14:12:59.780 MyApp[5512:907] cols, rows: 1, 1 ... scaleConvert: {0.475728, 0.5} ... tilesize: {784, 40}
2013-02-28 14:12:59.784 MyApp[5478:907] [SVGKImage] WARNING: no CALayer tree found, creating a new one (will cache it once generated)
2013-02-28 14:12:59.874 MyApp[5478:907] **\* Assertion failure in -[CSSPrimitiveValue getFloatValue:], /Users/user/Documents/XCode/MyApp/SVGKit/Source/DOM classes/Core DOM/CSSPrimitiveValue.m:178
2013-02-28 14:12:59.875 MyApp[5478:907] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Asked to convert a (19) value to a (5) (couldn't find a valid conversion route). Float (4 d.p.) = 0.0000, String = NaN'
**\* First throw call stack:
(0x316443e7 0x394d4963 0x3164429d 0x31f1afa3 0x429273 0x404e7b 0x411b8d 0x41fb47 0x41fd1f 0x41feaf 0x41ff6d 0x4225d7 0x3345cd61 0x3320d315 0x3320c8c3 0x3320c037 0x332030b7 0x33202fe1 0x332029c3 0x332027d5 0x33202639 0x31619941 0x31617c39 0x31617f93 0x3158b23d 0x3158b0c9 0x3514533b 0x334a72b9 0xfa975 0x39901b20)
libc++abi.dylib: terminate called throwing an exception

this happens in all commits after: 
(Feb 12)
69aa14569972331106f08a9fcbb3e77a90fd7c0e

**Comment by adamgit** [comment]
Please can you breakpoint there (add the "all breakpoints" breakpoint in xcode and it will auto-stop at the right moment), and copy/paste which bit of code is calling [CSSPrimitiveValue getFloatValue:]

(I need to know the source file + line so I can check it out - that error message is saying it wanted a "length" and it found a "string"... )

**Comment by tomasgatial** [comment]
This is the code: 

  UIView *myView = [[UIView alloc] initWithFrame:CGRect(0,0,100,100)];

//initialization of SVGKImage
  SVGKImage *document = [SVGKImage imageWithContentsOfFile:path ];

//here the problem happens 
  SVGKFastImageView *sgvkView = [[SVGKFastImageView alloc] initWithSVGKImage:document]; 
  [sgvkView setFrame:CGRectMake(0, 0,myView.bounds.size.width, myView.bounds.size.height)];

  [myView addSubview:sgvkView];

I want to point out, that this happens only with that one image, I wrote dropbox link to at the first comment.

**Comment by adamgit** [comment]
Thanks.

Sorry, I need the innermost piece of code that is crashing it - somewhere
deep inside the parser, whichever class is invoking "[CSSPrimitiveValue
getFloatValue:],"

I've looked at your SVG, but can't see any problems, it looks fine to me.

(I can't test it, I don't have a dev machine right now)

**Comment by tomasgatial** [comment]
Okey
Is this screenshot enough for you? 

![Screen Shot 2013-02-28 at 18 34 07](https://f.cloud.github.com/assets/3351584/206144/c6fd6196-81c4-11e2-9a72-737a438d0f9b.png)

**Comment by adamgit** [comment]
Aha - your SVG Is illegal. It has:

```
"x="NaN""
```

as the X-position for one of your TEXT nodes. Fix the SVG source and it
should render fine.

**Comment by tomasgatial** [comment]
SVG displayed fine at older versions of SVGKit (which i currently use) even though is illegal. My SVGs are generated on backend where i dont have an access.

But i would like to use some new features u implemented recently.

Do you think its possible to fix this?

**Comment by adamgit** [comment]
Older versions didn't support SVG's "text" node.

Now that we've added support for text, your broken SVG won't render. You
_really_ need to fix your SVG source files. If you can't edit directly,
download them with code, run a search-replace on the file locally, and then
hand it to SVG.

The illegal text in your SVG is not a small thing: it's a major thing, a
major problem. The only way to give you back the old behaviour is to break
the library _for everyone else_. We're not going to do that!

**Comment by tomasgatial** [comment]
I understand

I have no idea why the svg file contains corrupted element. (some backend bug or so)

Do you think it is possible at least to catch theese exceptions inside the framework?

As long as the other elements are valid, why should my application crash why receiving invalid SVG? I mean some try-catch block with logging the exception to console should solve my issue. I think it is not going to ruin the all library. 

I can work with this file without any problems in Adobe Ilustrator, also Safari displays it properly. So if the other applications can handle corrupted files, why SVGKit shouldnt?

**Comment by adamgit** [comment]
"As long as the other elements are valid, why should my application crash why receiving invalid SVG?"

If you turn off Assertions, it'll keep running. I don't know what will happen after that - you have corrupt data coming from the file, it might "crash" later on, for a different reason :(.

"I mean some try-catch block with logging the exception to console should solve my issue. I think it is not going to ruin the all library."

It's an open-source project, so ... if you want a custom version, you can easily fork the project on github, and comment-out the code that's crashing.

Future updates should easily "auto-merge" into your fork, so you wouldn't get stuck on an old version

**Comment by tomasgatial** [comment]
Thank you. I will look into this. I am new to GitHub.

**Comment by adamgit** [comment]
"I can work with this file without any problems in Adobe Ilustrator, also Safari displays it properly. So if the other applications can handle corrupted files, why SVGKit shouldnt?"

I understand your point, but the difference is those are "applications" and this is a "library". Libraries have to be more accurate and correct - if Safari displays a broken file, that's fine. If SVGKit allows a broken file, and is embedded inside other apps, developers will find its not doing what it should be doing.

If Illustrator loads a file that follows the SVG spec, then we work hard to make sure SVGKit loads it. But if it's against the spec ... we don't want to touch it.

**Comment by adamgit** [comment]
"Thank you. I will look into this. I am new to GitHub."

It makes life very easy :).
