### ISSUE TITLE
Image is rendered all black

### ISSUE THREAD

**Issue by ezisxl** [SVGKit/SVGKit#604]
using empty objective-c project with cocoapods
trying with this SVG: https://goo.gl/CsQK8h
getting all black
![simulator screen shot - iphone x - 2018-11-22 at 13 39 55](https://user-images.githubusercontent.com/4365368/48901031-d0a9f000-ee5c-11e8-8060-5c1160f46fca.png)

**Comment by adamgit** [comment]
How did you create this issue? Github should have given you a form to fill out. All the info from that form is missing. I will close this, we cannot do anything with it, sorry.

**Comment by ezisxl** [comment]
yup, solved!

used `pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'`

(mb add that to the readme as an alternative)
