### ISSUE TITLE
Load SVG content from memory

### ISSUE THREAD

**Issue by rakeshta** [SVGKit/SVGKit#61]
i have an app that generates SVG content in memory. I would like to render this content directly from memory.

Right now my only option is to write the content to a temporary file and then load it again.
This is costly for performance.

**Comment by rakeshta** [comment]
I tried implementing my own `SVGKSource` but that results in an `EXEC_BAD_ACCESS` crash when the `SVGKImageView` is released.

The crash happens on the first line in `[SVGKImage dealloc]` that tries to access `self.DOMTree`

**Comment by rakeshta** [comment]
Here is my implementation of `SVGKSource`

```
@interface VPSVKSourceNSStringReader : NSObject <SVGKSourceReader> {
    NSData *_data;
    NSUInteger _carat;
}

@end

@implementation VPSVKSourceNSStringReader

- (id)initWithString:(NSString *)string {
    if (self = [super init]) {
        _data  = [[string dataUsingEncoding:NSUTF8StringEncoding] retain];
        _carat = 0;
    }
    return self;
}

- (int)readNextChunk:(char *)chunk maxBytes:(int)maxBytes {
    NSRange range = NSMakeRange(_carat, MIN([_data length] - _carat, maxBytes));
    [_data getBytes:chunk range:range];
    _carat += range.length;
    return range.length;
}

- (void)dealloc {
    [_data release];
    [super dealloc];
}

@end


#pragma mark -

@interface VPSVKSourceNSString : SVGKSource {
    NSString *_svgString;
}

@end

@implementation VPSVKSourceNSString

+ (VPSVKSourceNSString *)sourceWithString:(NSString *)svgString {
    return [[[self alloc] initWithString:svgString] autorelease];
}

- (id)initWithString:(NSString *)svgString {
    if (self = [super init]) {
        _svgString = [svgString retain];
    }
    return self;
}

- (void)dealloc {
    [_svgString release];
    [super dealloc];
}


#pragma mark -

- (NSObject<SVGKSourceReader> *)newReader:(NSError**)error {
    return [[[VPSVKSourceNSStringReader alloc] initWithString:_svgString] autorelease];
}

- (void)closeReader:(NSObject<SVGKSourceReader> *)reader {
}

- (int)reader:(NSObject<SVGKSourceReader> *)reader readNextChunk:(char *)chunk maxBytes:(int)maxBytes {
    VPSVKSourceNSStringReader *stringReader = (VPSVKSourceNSStringReader *)reader;
    return [stringReader readNextChunk:chunk maxBytes:maxBytes];
}

@end
```

**Comment by rakeshta** [comment]
Btw, great library. I find it invaluable. Please keep up the good work!

**Comment by adamgit** [comment]
From a _brief_ read, your SVGKSource looks correct.

"The crash happens on the first line in [SVGKImage dealloc] that tries to access self.DOMTree"

That method doesn't _read_ self.DOMTree, it merely releases it. It sounds to me like there's "one too many [release] calls" somewhere. I suggest you run Product -> Analyze and see what blue memory errors it flags. I tried it on master just now and there's zero mem errors.

Final thought: does this crash happen with other sources? Might be something in your app (or in SVGKit) that's over-releasing anyway, and your source is a coincidence?

**Comment by adamgit** [comment]
PS: if/when this is working, it would be great to add it to master (although you'd need to rename it to "SVGKSourceNSString" to fit with the naming conventions).

...the current SVGKsource, which does everything in one file, is NOT how it should be - it needs refactoring to split it into two separate, clean, classes. (one for files, one for URLs). Maybe ... doing that refactor would expose this bug too?

**Comment by adamgit** [comment]
aleph7's pull request has fixed this - I've used his fix in my own apps, and I've added an example to the core SVG library (try instantiating an SVGKLayeredImageView without an image, and display it on screen! You'll get a default image that was loaded directly from an in-memory string...)
