### ISSUE TITLE
how to convert UIIMage to SVG?

### ISSUE THREAD

**Issue by bizibizi** [SVGKit/SVGKit#610]
and are there some other formats to convert?

**Comment by adamgit** [comment]
UIImage is a bitmap. SVG is a vector.

Vectors can be drawn as bitmaps (but lose the advantages of a vector), but bitmaps are too low-resolution to become vectors.

There are some open-source libraries that make "approximate" vectors from a bitmap - e.g. I've used potrace a lot - but it is never perfect, and it's not a conversion it's an approximation.

**Comment by bizibizi** [comment]
so, the library does not do that? i need ios solution

**Comment by adamgit** [comment]
Noone does that. It is literally not possible.

If you want to do a lossy approximation, id look at using potrace and 
similar libs - its open source, but I don't know whether there's a 
swift/obj port.
