### ISSUE TITLE
Memory leaks when SVGKImage convert to UIImage ,please fix it

### ISSUE THREAD

**Issue by zw318** [SVGKit/SVGKit#622]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [ ] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [ ] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [ ] I am not using CocoaPods, or: I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by zw318** [comment]
UIImage *image = [SVGKImage imageWithContentsOfFileAsynchronously:svgURL.path onCompletion:nil].UIImage;

**Comment by adamgit** [comment]
What is the leak?

**Comment by zw318** [comment]
> What is the leak?

![image](https://user-images.githubusercontent.com/48673240/55725399-3085e980-5a40-11e9-9ba4-c92aeb04d81b.png)
this picture from Instruments!

code: UIImage *image = [SVGKImage imageWithContentsOfFileAsynchronously:svgURL.path onCompletion:nil].UIImage;

UIImage *image = [SVGKImage imageWithContentsOfFileAsynchronously:svgURL.path onCompletion:nil].UIImage
--

**Comment by adamgit** [comment]
That code does not exist inside this project (I confirmed this just now with a search using GitHub).

Maybe this is a bug in Github (seems unlikely), but I do not remember there ever being a method "loadWireframeImageWith:completion:" - where did you get that code from?

You may need to investigate your source code a little more to find where that code has come from.

**Comment by zw318** [comment]
> That code does not exist inside this project (I confirmed this just now with a search using GitHub).
> 
> Maybe this is a bug in Github (seems unlikely), but I do not remember there ever being a method "loadWireframeImageWith:completion:" - where did you get that code from?
> 
> You may need to investigate your source code a little more to find where that code has come from.

![image](https://user-images.githubusercontent.com/48673240/55727943-b193af80-5a45-11e9-8669-c9e0024ebaf5.png)
This is my test code, i find leaks from the method "imageWithContentsOfFileAsynchronously:onCompletion"

**Comment by zw318** [comment]
> That code does not exist inside this project (I confirmed this just now with a search using GitHub).
> 
> Maybe this is a bug in Github (seems unlikely), but I do not remember there ever being a method "loadWireframeImageWith:completion:" - where did you get that code from?
> 
> You may need to investigate your source code a little more to find where that code has come from.
![image](https://user-images.githubusercontent.com/48673240/55728605-f1a76200-5a46-11e9-9ef3-267efd6baa0b.png)
This is my test code, i find leaks from the method "UIImage *image = [SVGKImage imageWithContentsOfFileAsynchronously:svgPath onCompletion:nil].UIImage" ,

**Comment by adamgit** [comment]
Yes. The leak is in your code. That is what Instruments is telling you.

Also, you are using that constructor incorrectly. If you use an ASYNCHRONOUS constructor, you cannot immediately reference the result - it will never work.

Either use the default version (that does NOT contain the word "Asynchronously" in the constructor name), or implement the callback (that you currently provide "nil"!)

**Comment by zw318** [comment]
> Yes. The leak is in your code. That is what Instruments is telling you.
> 
> Also, you are using that constructor incorrectly. If you use an ASYNCHRONOUS constructor, you cannot immediately reference the result - it will never work.
> 
> Either use the default version (that does NOT contain the word "Asynchronously" in the constructor name), or implement the callback (that you currently provide "nil"!)

![image](https://user-images.githubusercontent.com/48673240/55770547-4a164800-5ab7-11e9-86a9-8685fd5dff95.png)
![image](https://user-images.githubusercontent.com/48673240/55770585-6dd98e00-5ab7-11e9-971f-e028d556f06d.png)

This is my test code and memory
