### ISSUE TITLE
How to set SVG's default namespace in codes?

### ISSUE THREAD

**Issue by Taxiway** [SVGKit/SVGKit#636]
I got to parse an SVG file without specifying the namespace (xmlns) in the SVG xml.

<svg width='100px' height='25px'><g class='bars'><rect fill='blue' width='100%' height='25'></rect><rect fill='green' width='45%' height='25'></rect></g></svg>

I got warning like "WARNING: Your input SVG contains tags that have no namespace, and your document doesn't define a default namespace."

I understand a namespace should be set but how could I set namespace before parsing the SVG without modifying the original SVG xml string?

My codes are like:
`            NSString *svgString = @"<svg width='100px' height='25px'><g class='bars'><rect fill='blue' width='100%' height='25'></rect><rect fill='green' width='45%' height='25'></rect></g></svg>";`
`            SVGKSource *cssSource = [SVGKSourceString sourceFromContentsOfString:svgString];`
`            SVGKImage *image = [SVGKImage imageWithSource:cssSource];`
`            SVGKImageView *imageView = [[SVGKFastImageView alloc] initWithSVGKImage:image];`

**Comment by adamgit** [comment]
Can you inject an XMLNS tag into  the start of your strings?

Alternatively, off the top of my head you can manually add NS's to the 
parser before it parses. You need to use the richer constructor for  
SVGKImage (one of the ones that guves you the parser  object and waits for 
you to start the parse - i think there's one?)

Off the top of my head, theres a method call to add a namespace and you 
just basically give it a namespace name and a namespace url. I'd look in 
the parser xode for namespaces to see what it does with namespaces it finds 
in the document.
