### ISSUE TITLE
Build iOS failed: 'SVGKitLogVerbose' is invalid in C99

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [SVGKit/SVGKit#644]
I'm trying to build my project which is including SVGKit installed from pods (branch v3)

Target `iOS 9.0`
XCode `10.2.1`

Tried with branch v2 and v3, both using CocoaPods and integrating the framework.
I always get the error `Implicit declaration of function 'SVGKitLogVerbose' is invalid in C99`

I'm trying with the old and the new build system.

_P.S. If that's relevant, I'm trying to integrate the library in a `react-native` project._

**Comment by adamgit** [comment]
Does it work if you don't use cocoapods?

**Comment by GabrielePrestifilippo** [comment]
I tried once more with the static library and that error was solved. Thanks!
