### ISSUE TITLE
Support Symbol Image

### ISSUE THREAD

**Issue by IvanChan** [SVGKit/SVGKit#649]
For more information

SF Symbols
https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/

Creating Custom Symbol Images for Your App
https://developer.apple.com/documentation/uikit/uiimage/creating_custom_symbol_images_for_your_app

**Comment by adamgit** [comment]
If it's a normal SVG, it should just work.

What doesn't work?

**Comment by IvanChan** [comment]
@adamgit it’s an image set,I try to load one of them according to actual needs

**Comment by adamgit** [comment]
What's the issue?

**Comment by IvanChan** [comment]
@adamgit 
Here is a symbol svg file,  is an image set actually
[moon.circle.svg.zip](https://github.com/SVGKit/SVGKit/files/3717237/moon.circle.svg.zip)

If you load it directly,  it will show the total map like this:
![1570793076287](https://user-images.githubusercontent.com/3829585/66647961-e4b93480-ec5c-11e9-82bf-e8b6b9863d1b.jpg)


Actually I just want to load one of them depends on specific scene

**Comment by adamgit** [comment]
That's not really related to SVGkit. You have an image and you want help 
with doing some image manipulation / writing your app.

My guess is that each symbol is tagged in the raw SVG file, eg using the 
id="something" Syntax, which is standard in SVGs. There are methods in 
SVGkit to ask SVGkit to give you *only* the sub parts of the image starting 
at a given node/element, which make this easy to then pull out.

(I used this a few times in different apps, works well,)

I'm on mobile at the moment, can't remember the method names you need to 
use, but there are some old examples on the wiki and on the front page that 
are probably outdated but approximately correct names.

**Comment by IvanChan** [comment]
At first I try to target the element I want and work with it,  and it's not easy to fix all transform stuff.

I found solution avoid dealing with svg element
just call `- (CALayer *)layerWithIdentifier:(NSString *)identifier;` and render again
