### ISSUE TITLE
Performance issue when transiting from an SVGKImage to UIImage

### ISSUE THREAD

**Issue by emilien-io** [SVGKit/SVGKit#676]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [x] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [x] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [x] I am not using CocoaPods, or: I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps

Hello guys, the converstion of an **SVKImage** to an **UIImage** (`svgk.uiImage`) takes a long time (approximatively up to 4 to 5 sec for 3 SVGs). Is there any way to improve this process ?

Here is my code :

```
if let svgk = SVGKImage(data: data) {
      self.svgView?.image = svgk.uiImage
}
```

I read somewhere here on a issue that SVGKit was doing a lot of thing that might be unnecessary for some of us. Since I just need to display the SVG, I'm not sure if I use he most efficient way there.

Thanks in advance guys and thanks for your work.

**Comment by adamgit** [comment]
If you want to display the SVG image, then don't convert it to a
UIImage. Conversion is always going to take a lot longer than just
displaying it.

Use the provided classes for displaing it - the ones named
"SVGKImageView" or similar, as shown in the demo app provided in the
project.

**Comment by emilien-io** [comment]
I tried it but unfortunately it didn't display anything.
I'll try again and let you know.

> If you want to display the SVG image, then don't convert it to a
> UIImage. Conversion is always going to take a lot longer than just
> displaying it.
>
> Use the provided classes for displaing it - the ones named
> "SVGKImageView" or similar, as shown in the demo app provided in the
> project.
>

**Comment by emilien-io** [comment]
```
class PassthroughImageView: SVGKImageView {
    override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        let view = super.hitTest(point, with: event)
        return view == self ? nil : view
    }
    
    init(with source: SVGKSource, frame: CGRect) {
        super.init(frame: frame)
        self.image = SVGKImage(source: source)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```

I tried to load the SVG in a subclass of SVGKImageView through an SVGKImage initialized via both **SVGKSource** and **data** without success. The app is not showing the SVG and I don't seems to have any warning/error in my console. **That same data is working fine whenever I create an SVGKimage with it then convert it in UIImage**.

Any idea why ?

_**EDIT**: I printed the result of `svgk.parseErrorsAndWarnings`, here is the result :_
`Parse result: 0 warnings, 0 errors(recoverable), 0 errors (fatal). Last recoverable error: (n/a)`

**Comment by adamgit** [comment]
SVGKImageView is only a base class. If you try to use SVGKImageView it will
give you an error message to the console telling you exactly what you need
to do, and the names of the classes you can use. Use one of them.

Don't try subclassing it unless you're going to implement the required
methods yourself, manually. Right now you're trying to use a half-empty
class, so yeah it won't work on its own.
