### ISSUE TITLE
Recognising transformation matrix even if elements are not separated by whitespace 

### ISSUE THREAD

**Issue by timbms** [SVGKit/SVGKit#695]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [X] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [X] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [X] I am not using CocoaPods, or: I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps
SVGKit is strict wrt separator between elements in transformation matrix. SVGKit expects a whitespace. 

The matrix defined in the attribute gradientTransform requires 6 elements. If the elements are not separated by whitespace, SVGKit does not get 6 elements and then crashes in SVGElement.m block lines 303-308. 

Other SVG frameworks render image without error. 

SVGKit should split elements as for fix #691

Examples are in the attached zip: bedroom.svg (on which SVGKit chokes) and bedroom2.svg (which is rendered by SVGKit)
[Archive 2.zip](https://github.com/SVGKit/SVGKit/files/5197135/Archive.2.zip)

**Comment by weakfl** [comment]
@timbms Are you sure the problematic files are valid? The SVG specification seems quite clear regarding [transform attributes](https://www.w3.org/TR/SVG11/coords.html#TransformAttribute):  _"The individual transform definitions are separated by whitespace and/or a comma."_

And it looks like the problematic files in openHAB have been fixed with openhab/openhab-webui#291 (eg [bedroom.svg](https://github.com/openhab/openhab-webui/blob/master/bundles/org.openhab.ui.iconset.classic/src/main/resources/icons/bedroom.svg?short_path=ebf6689)).

**Comment by timbms** [comment]
@weakfl: 
In my opinion the BNF for [transform matrix](https://www.w3.org/TR/SVG11/coords.html#TransformMatrixDefined) is the same as for : 
`comma-wsp:
(wsp+ comma? wsp*) | (comma wsp*)`
is the same as for [path data](https://www.w3.org/TR/SVG/paths.html) section 9.3.9:
`comma_wsp::=(wsp+ ","? wsp*) | ("," wsp*)`
A case where wsp is contracted is strictly not permitted in both cases. However, there is an explanatory note for path data: 
> The processing of the EBNF must consume as much of a given EBNF production as possible, stopping at the point when a character is encountered which no longer satisfies the production. Thus, in the string "M 100-200", the first coordinate for the "moveto" consumes the characters "100" and stops upon encountering the minus sign because the minus sign cannot follow a digit in the production of a "coordinate". The result is that the first coordinate will be "100" and the second coordinate will be "-200".
> Similarly, for the string "M 0.6.5", the first coordinate of the "moveto" consumes the characters "0.6" and stops upon encountering the second decimal point because the production of a "coordinate" only allows one decimal point. The result is that the first coordinate will be "0.6" and the second coordinate will be ".5".

By analogy it would make sense to have transform matrix parsing as tolerant.

**Comment by weakfl** [comment]
> By analogy it would make sense to have transform matrix parsing as tolerant.

@timbms You're probably right and it does work:

<img width="46" alt="Screenshot 2020-10-04 at 09 42 01" src="https://user-images.githubusercontent.com/614985/95009967-22f5f380-0626-11eb-99ae-173b7f7cf17a.png">

I'll have to clean it up a bit when I have time and then I could sumbit a PR if @adamgit is ok with it...
