### ISSUE TITLE
SVGKit seems to allocate too much memory

### ISSUE THREAD

**Issue by pepejeria** [SVGKit/SVGKit#735]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [x] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [x] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [x] I am not using CocoaPods, or: I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps

We are using the library using SPM to display SVG images in a collection view. This is done by using Kingfisher's `ImageProcessor` protocol:

```
import Kingfisher
import SVGKit

struct SVGImageProcessor: ImageProcessor {

    public let identifier = "com.company.x"

    public func process(item: ImageProcessItem, options: KingfisherParsedOptionsInfo) -> KFCrossPlatformImage? {
        switch item {
            case .image(let image):
                return image
            case .data(let data):
                return SVGKImage(data: data)?.uiImage
        }
    }
}
```

The images are displayed correctly, but the app is killed by iOS on some phones (iPhone mini). Below a screenshot from Instrument Leaks where the memory allocation is over 2 gigs:

![iphone-mini-memory-allocation](https://user-images.githubusercontent.com/1394550/135234063-9ad3e15f-a7e2-4f88-9f0a-eef25f9db5d5.png)

The SVG images are small (around 50kb) and the biggest one is about 150 kbs.

**Comment by adamgit** [comment]
This is not a memory leak. 150KB is **very large** for a vector image. I am not surprised to see it reach gigabytes of RAM (the Wikipedia map of Earth in high res is only twice that size, and is so large it can't be rendered on many SVG implementations without crashing).

You haven't stated what resolution you're rendering at. Remember that vector images on disk have fixed size, but once you render them to pixels then the amount of memory needed is proportional to your screen size.

NB: in your code snippet you're rendering as pure pixels, which is the worst case for memory usage. It's great for small/medium images, but for large images I'd recommend using the SVG as a layered object, and let Apple's internal rendering keep it in vector format. This will still use some RAM, but it should be a lot less (it depends on Apple's own performance optimizations)

**Comment by adamgit** [comment]
Also: if you have caching enabled (default is on - look in the source code for a #define with "CACHE" in it to turn it off) then you're probably holding the vector version in memory **as well as** the final pixel version.

You can flush the vector-cache manually - I can't remember the API call off the top of my head, but quick-searching in Xcode for 'cache' should find it very quickly - and if you're only using the image as pixels then you lose nothing by loading and flushing.

NB: disabling caching won't change the maximum memory used: Apple needs to use all that memory while it's converting from vector to pixels. But after rendering is finished, you could safely drop the internal memory used for the vector version.

(it's impossibe to render an SVG in pixels without first rendering it in vector)

**Comment by pepejeria** [comment]
Thank you for the suggestions. 

 -  I'd recommend using the SVG as a layered object

How would you achieve this? I couldn't find this.

**Comment by adamgit** [comment]
If you look in the SVGKImage.m file, you'll see that the '.UIImage'
call you're currently using is a convenience method that takes the
underlying SVGKImage and runs an Exporter to convert it to a UIImage
(pixels/raster):

-(UIImage *)UIImage
{
#if SVGKIT_MAC
return [SVGKExporterNSImage exportAsNSImage:self antiAliased:TRUE
curveFlatnessFactor:1.0f
interpolationQuality:kCGInterpolationDefault]; // Apple defaults
#else
return [SVGKExporterUIImage exportAsUIImage:self antiAliased:TRUE
curveFlatnessFactor:1.0f
interpolationQuality:kCGInterpolationDefault]; // Apple defaults
#endif
}

...looking further down that file, you have other methods e.g.:

-(CALayer *)CALayerTree

...and a bunch of more powerful methods for returning specific layers
from the tree, etc. Once you have a CALayer (Apple's general class for
rendering) you can display it multiple different ways - Apple has many
methods for this. But the key point is: a CALayer preserves the
vector-data, i.e. shapes/outlines/drawinig commands.

The downside is that no current modern device renders vectors
natively, so everytime you have to render the image Apple will have to
use a small amount of CPU/GPU time to re-execute the vector
instructions before displaying it. In most cases that is vanishingly
small. With very large SVGs that could take significant CPU time.
