### ISSUE TITLE
radial gradients

### ISSUE THREAD

**Issue by tsaizhenling** [SVGKit/SVGKit#75]
any plans to implement radial gradients? I believe it has not been implemented yet.
![screen shot 2013-05-01 at 1 10 29 am](https://f.cloud.github.com/assets/1062331/445301/f77de038-b1b8-11e2-9fee-5107dc98144e.png)

the sample provided actually has a radial gradient in the eye.
![screen shot 2013-05-01 at 1 10 50 am](https://f.cloud.github.com/assets/1062331/445302/fc14198c-b1b8-11e2-9e9c-5ba019cb6a5f.png)

also, looks like the linear gradients are a little buggy.
![screen shot 2013-05-01 at 1 12 17 am](https://f.cloud.github.com/assets/1062331/445307/295b9ee2-b1b9-11e2-8111-84edc67bf6ba.png)
![screen shot 2013-05-01 at 1 12 26 am](https://f.cloud.github.com/assets/1062331/445308/2c26f158-b1b9-11e2-893e-e3323fa2e227.png)

**Comment by adamgit** [comment]
Good catch.

If you search the source for "gradient", I think you can add support for radial gradients very easily - maybe as little as 5-10 lines of code.

For the bug in linear gradients - are you sure that's a linear gradient? Maybe it's a radial gradient and a linear together? If it's definitely a bug, then ... again, the code for gradients is very simple (it uses Apple's CAGradientLayer to do 95% of the work) so I recommend experiementing with it see if you can find/fix it directly

**Comment by tsaizhenling** [comment]
its is a linear gradient and i found the bug. submitted a pull request for the fix.

radial gradients.. are not supported by CAGradientLayer unfortunately, but we can draw radial gradients with quartz commands so i think thats the only way to do it. will tinker with this when i have more time.

**Comment by adamgit** [comment]
Fix merged into branch 1.1.0 - https://github.com/SVGKit/SVGKit/tree/1.1.0
