### ISSUE TITLE
Crash on some svg file due to OOM issue

### ISSUE THREAD

**Issue by Simon-Zeng** [SVGKit/SVGKit#802]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [x] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [x] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [x] I am not using CocoaPods, or: I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps

App will consume lots of memory and then crash when viewing some svg files with large viewBox:
`
   version="1.1"
   viewBox="0 0 10000 8500"
   xml:space="preserve"
   id="svg5418"
   inkscape:version="0.48.4 r9939"
   width="100%"
   height="100%"
`
i.e. my svg file is 30KB, but when viewing in app, it cost 2.9 GB memory.
Is there any way to avoid this issue?

**Comment by adamgit** [comment]
If your image was a single white rectangle, at that resolution you have
forced your machine to dedicate at least 255 MB just to send it to the
screen for rendering. Operating Systems often cache rendering, so you might
expect that to be 500+MB instead.

If you're viewing the image as bitmap: Reduce the size of the viewBox. You
are currently *forcing* your machine to spend this much memory - that is
what the viewBox parameter does.

If you're viewing the image as vector: your image probably has too much
complexity (too many gradients, etc) for your machine to handle. You can
reduce the viewbox to make it easier for your OS -- the OS will only have
to generate a smaller number of pixels during rendering. A vector image can
be thousands of times smaller on disk than in-memory.
