### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by chrs1885** [SVGKit/SVGKit#804]
Hi there,

We recently became aware that, according to the new Apple privacy regulations, third-party SDKs will also be required to provide a [Privacy Manifest ](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) to ensure compliance with privacy policies in the future.

Do you have any plans to deliver a Privacy Manifest with the library?

**Comment by adamgit** [comment]
SVGKit doesn't (as far as I know) gather any data at all, and doesn't use
any unusual APIs (all the ones Apple lists as restricted: we're not using
any of them) - so the Privacy Manifest would be empty anyway.

I'm not sure how that works out - it seems as though the PM is only
required if it would be non-empty?

**Comment by chrs1885** [comment]
From my perspective the whole thing is about providing transparency. Even the fact that you don't collect any data might be important to developers. What do you think?

**Comment by adamgit** [comment]
Personally I wouldn't reject a PR that added an empty manifest - unless it
caused problems with other uses - but I don't see any value in it... Apple
nearly always makes these things compulsory wherever possible. A team
saying 'we don't collect data' is pretty meaningless today when so many
companies simply lie about it - but a technical block on apps running/being
published that operates at the API level is something you can trust. Or ..
use open-source projects (like this one) where you can simply see for
yourself - e.g. use GitHub to do a search on the codebase for uses of
NSURL, see for yourself that there's nothing making outbound connections
other than those you trigger yourself (by requesting a remote image).
(and if that search found something unexpected, it would be a sign that
someone had sneaked something in that shouldn't be there, and we'd want to
remove it ASAP!)

I expect Apply will gradually (or rapidly!) increase the number of APIs
that require the manifest, until apps/libs/etc are unable to hide what
they're doing.

**Comment by merrymay** [comment]
Do you have any plan to support SPM for this issue?
