### ISSUE TITLE
Display complex SVG

### ISSUE THREAD

**Issue by GeorgeRosescu1** [SVGKit/SVGKit#820]
![aw](https://github.com/SVGKit/SVGKit/assets/56083561/25f423ce-7519-4a50-b59e-b82904badcca)
Hello,
I have to display the attached svg image. I'm using Kingfisher to download the asset and have an svg processor based on SVGKit as follows:

```
struct SVGImgProcessor: ImageProcessor {
    var identifier: String = "ro.app.webpprocessor"
    
    func process(item: ImageProcessItem, options: KingfisherParsedOptionsInfo) -> KFCrossPlatformImage? {
        switch item {
        case .image(let image):
            return image
        case .data(let data):
            let svgImage = SVGKImage(data: data)
            return svgImage?.uiImage
        @unknown default:
            return nil
        }
    }
}
```

Then I retrieve the image from cache for display:
`flagImageView.asyncImage(url: URL(string: country.flagURL), kfOptions: [.svgProcessor])`

The result is not as I expected:
<img width="104" alt="Screenshot 2024-03-08 at 16 49 58" src="https://github.com/SVGKit/SVGKit/assets/56083561/873a9250-5389-4b54-9790-8c29c507cb8f">

Does anyone have any clue?

**Comment by adamgit** [comment]
Typically things like this are due to a misconfigured "viewBox" parameter
on the SVG file itself - a lot of tools are too forgiving of bad viewboes -
or, vice versa: a bug in SVGKit's calculation of the underlying viewbox
(there are some unusual formats of the viewbox parameter string that are
technically legal but no-one had seen/tested with and so the code didn't
support them - until someone finds a case where the parser is wrong, and
submits a PR to improve it).

Might not be the case here, but the fact its scaled down to a tiny size
suggests it to me.

**Comment by GeorgeRosescu1** [comment]
@adamgit thank you for the insight. Indeed the viewBox is missing on my resource. I've tested other svgs with viewBox and they display as expected.

Thanks!

**Comment by adamgit** [comment]
The rules for 'inferred viewbox' are quite vague in the standard - off
the top of my head a lot of software has its own heuristics to make an
intelligent guess at what the viewbox SHOULD have been, even when its
incorrect or missing.

Off the top of my head: our API already lets you specify an 'override
viewbox' when you parse the file, so if you have a way of knowing what
the viewbox 'should' be (e.g. you might have 800 flags all of which
are supposedly 1024x512 in size) then you can use that to 'force' it.

**Comment by GeorgeRosescu1** [comment]
how can it be set? Not .scale, nor .size or .scaleToFit works

**Comment by adamgit** [comment]
First thing I tried: open the SVGKImage.m, and there at line 13 there's a
comment literally about this, pointing you to:

https://github.com/SVGKit/SVGKit/blob/3.x/Source/DOM%20classes/SVG-DOM/SVGSVGElement_Mutable.h
