### ISSUE TITLE
retrieve CGPath(s) from SVG file

### ISSUE THREAD

**Issue by fabriz23** [SVGKit/SVGKit#84]
How can I retrieve CGPath from SVG file exactly? I don't understand and there aren't a clear documentation of tht.

thank you

**Comment by adamgit** [comment]
c.f. http://t-machine.org/index.php/2013/06/01/svgkit-2013-recipes-part-2/

But please note: CGPath is a difficult structure to use (it's not an ObjC class), you'll need to read a LOT of Apple documentation if you don't know how to use it already.
