### ISSUE TITLE
taking SVGs from URL

### ISSUE THREAD

**Issue by Alexanderrgonzales77** [SVGKit/SVGKit#91]
initWithContentsOfURL seems to be depreciated, I have attempted to upgrade this with the appropriate replacement command initWithContentsOfURL: encoding:  error: 

however when i try to test with the upgraded command, i get the error that the selector is not found. 

I will keep trying to fix this and if do manage to create a fix will post it.

**Comment by Alexanderrgonzales77** [comment]
Okay there is a problem with the demo program making use of URLs i have tried two wiki URLs 

http://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg

and http://upload.wikimedia.org/wikipedia/en/f/fb/Yes_check.svg

the problem however is not with the initWithContentsOfURL (this was my mistake) 

right now it looks like the problem is with the code for making streams. However i am not certain about that as well. 

I will keep trying to fix this issue

**Comment by Alexanderrgonzales77** [comment]
just to be clear i used the example given to me in the recipes

this would not display an SVG from URL and it appears to be a problem with the streaming.  
3
NSString\* longURL = [NSString stringWithFormat:@"%@%@%@",
4
@"http://upload.wikimedia.org/",
5
@"wikipedia/commons/f/fd/",
6
@"Ghostscript_Tiger.svg";
7
NSURL\* url = [NSURL urlWithString:longURL];
8
SVGKImage\* newImage = [SVGKImage imageWithContentsOfURL:url];

for some reason it is entering this if statement 

if (status != NSStreamStatusOpen)
    {
        if (status == NSStreamStatusError)
            [currentParseRun addSourceError:[stream streamError]];
        [stream close];
        return  currentParseRun;
    }

and it doesnt seem to actually be making a stream

**Comment by MaddTheSane** [comment]
Is the status variable reporting an error? If not, what is it reporting?

**Comment by Alexanderrgonzales77** [comment]
the first thing i get is a pop-up alert.  "SVG pare failed Total failure. see console log

in the log i have this

2013-07-10 17:44:25.490 XXX[12634:c07] [SVGKImage] ERROR: failed to init SVGKImage with source = (null), returning nil from init methods
2013-07-10 17:44:25.492 XXX[12634:c07] http response code: 307
2013-07-10 17:44:25.493 XXX[12634:c07] GET
2013-07-10 17:44:25.494 XXX[12634:c07] Unbalanced calls to begin/end appearance transitions for <ChooseRoomViewController: 0xa4666f0>.
2013-07-10 17:44:25.830 XXX[12634:c07] Finishing up a navigation transition in an unexpected state. Navigation Bar subview tree might get corrupted.

**Comment by Alexanderrgonzales77** [comment]
I did find what appears to be a tempt work around.

in SVGKSource.m 
- (SVGKSource_)sourceFromURL:(NSURL_)u {
  NSInputStream _stream = [NSInputStream inputStreamWithData:[NSData dataWithContentsOfURL:u]];
  //NSInputStream_ stream = [NSInputStream inputStreamWithURL:u];
  [stream open];
  
  SVGKSource\* s = [[[SVGKSource alloc] initWithInputSteam:stream] autorelease];
  s.URL = u;
  
  return s;
  }

I changed NSInputStream\* stream = [NSInputStream inputStreamWithURL:u]; to NSInputStream *stream = [NSInputStream inputStreamWithData:[NSData dataWithContentsOfURL:u]];

i call this a temp fix because only simple made SVGs are now displayed, but i am thinking this might be a fault of my app and not the kit.

**Comment by adamgit** [comment]
It used to work. I suspect the problem might be that current iOS breaks the (Apple) NSInputStream class (I have seen a couple of horrible, showstopper bugs in Apple's networking from iOS 6.0 onwards - they mucked around with a lot of stuff behind the scenes).

I've done a lot of work with NSInputStream recently on a different project -- I'll have a look at this in more detail when I have some free time.

One thing I'd suggest: there's been 3 different versions of the SVGKSource implementation, and IIRC one of the older ones didn't work well (it was more fragile based on network environement - probabyl didn't support HTTP-proxies, or similar).

So ... it might be worth using GitHub's "BLAME"/"HISTORY" buttons on the SVGKSource class and subclasses, have a browse of the previous versions, see if any of them work better / worse for you.

FINALLY: if your remote SVG's contain any embedded weblinks to embedded data / cross-referencing / instancing ... that part of SVGKit doesn't work at the moment. I wrote most of the code for it, but never got it to work properly. It's very tricky to get right :(. IT _esepcially_ won't work with remote files!

**Comment by adamgit** [comment]
I haven't touched SVGKit's version, but doing more work with NSInputStream on other projects: it's basically unsupported/ignored by Apple.

We need to rewrite this code to implement our own download/streaming, Apple's stream classes appear not to have been updated since the iPhone launched, and are missing core features of streams APIs on other OS's.

Best approach IMHO would be:
1. Use NSURLConnection's new "blocks" methods to get callbacks for data coming over the wire
2. Write a custom NSInputStream subclass, a thin wrapper that converts those callbacks into the NSInputStream API

**Comment by Alexanderrgonzales77** [comment]
Thanks, We ended up not using SVGs on the phone, but it would have been Awesome if we had :)

**Comment by adamgit** [comment]
Update: Apple has rewritten / replaced their bad URLConnection classes with a new set of session-based class that seem to work a bit better - I don't know if they support streams, but it's worth lookign into.

**Comment by adamgit** [comment]
It turns out that [stream open] has some subtle side-effects on current iOS to do with threading.

I've rewritten that code and it seems to work fine now (it calls open as late as possible now, instead of as early as possible)

**Comment by bilby91** [comment]
What's the status of this ?

**Comment by adamgit** [comment]
As per the github status, one line above your comment.

**Comment by bilby91** [comment]
@adamgit sorry if I was not clear enough. Just wanted to know if imageWithContentsOfURL was working. I guess it's a no. Thanks!

**Comment by adamgit** [comment]
Its been working for a month. As per.the last comment. As per.the status.
