### ISSUE TITLE
"Compile an embeddable library" in readme need some work

### ISSUE THREAD

**Issue by bdalziel** [SVGKit/SVGKit#92]
Trying to create a library for 1.1.0 (https://github.com/SVGKit/SVGKit/tree/1.1.0)

Item 2. "Select the target "SVGKit Library" from the dropdown build selector at top left"
Can you elaborate on this please? Perhaps it's an xcode version difference, but I don't see this/these options.

Item 4a. Markdown doesn't like your letter sub bullet, it is combined with Item 3.

Item 5. Can you reference the name of the library file.

Item 6. "Edit your build settings and set "C/C++ Compiler Version" = "LLVM Compiler 2.0""
I think the key has changed to: "compiler for C/C++/Objective-C", and "LLVM Compiler 2.0" is not an option - should it be added manually? Available options are "Apple LLVM compiler 4.2" and "GCC 4.2"

**Comment by MaddTheSane** [comment]
Item 6: Apple has updated the LLVM compiler (Clang) since the doc was written. _LLVM Compiler 4.2_ is what you want.

**Comment by bdalziel** [comment]
@MaddTheSane thanks for the clarification.

**Comment by adamgit** [comment]
Unfortunately, Apple has changed the names in every successive version of Xcode. I haven't tried Xcode 5 yet, but I bet it has the same problem.

That will mean 3 or more different versions of the instructions (Xcode 3, Xcode 4 (two versions, IIRC), Xcode 5) :(.

**Comment by adamgit** [comment]
As per comments on other issues: I'd like to merge @MaddTheSane 's branches into master, and then I'll re-write the instructions + build process for Xcode 5 (which is about to go live/gold!)

...but there's a lot of work needed to merge + test here, so I'll need help; @bdalziel do you have time to help a bit with that? And/or help by installing Xcode5 and trying out simpler ways of building the lib?

(Apple will kill support for Xcode4 as soon as Xcode5 goes live, so I don't mind us switching over compeletely, and backporting changes to build instructions for the handful of people who won't upgrade xcod4 yet)

**Comment by bdalziel** [comment]
can you link to @MaddTheSane 's branch? I can help a little - I've used SVGKit extensively on a game launching tomorrow and intended to write about some of the things I found and worked around.

My primary issues 2 months ago were knowing which branch or version to use - lots of cross linking, no single source of truth, and once I made a decision, getting a version installed into my app. Then basic usage examples seemed out dated etc. Clarifying those three components would be a great start.

**Comment by adamgit** [comment]
Ouch, sorry to hear that.

We got a bit mixed up with master, which i hoped to fix with a final
1.0 release (we were waiting for a few more people to clean up their
brancbes and re-merge) but 1.0.0 and 1.1.0 have been single source for most
people.

**Comment by MaddTheSane** [comment]
On my fork, my main coding is done on master. And yes, it is based on the 1.1.0 branch.
