### ISSUE TITLE
SVG file scrolls and zoomes very slowly.

### ISSUE THREAD

**Issue by parfenuk** [SVGKit/SVGKit#94]
Good afternoon! 

I have a large SVG file and I load it as SVGKLayeredImageView (because it has gradients) with your SVGKit 1.1.0 iOS-Demo project. If I run it on the Simulator 6.0 - everything is fine. But when I run this application on my iPhone 4 (it has iOS 6.0 too) - my SVG file loaded about 5 times slower. Also scrolling and zooming both work very slow - they have essential delay and the screen has low fps. 

So, could you give me any answer what's wrong with SVG-file or, maybe, code? 

Thanks in advance.

**Comment by adamgit** [comment]
Simulator is using the 3D graphics card in your desktop/laptop - which is a lot more powerful than an iPhone.

Slow scrolling/zooming suggests you have too many layers OR too many curves in some of your layers ... for Apple's built-in graphics chip / iOS graphics rendering.

Alternatively, some of the features of Apple's rendering will prevent the iPhone from using hardware-acceleration: e.g. blue, drop-shadow. It's possible you have some of them.

I've been experimenting with an OpenGL-based rendering, and it runs many times faster than Apple's slow iOS code, but that's not open-source. If you have time / expertise to replace Apple's drawing calls with OpenGL calls, I'd recommend trying it out!

**Comment by parfenuk** [comment]
Thank you! I tried OpenGL rendering - and it works really faster. Now I think I can fix my problem totally.
