### ISSUE TITLE
Crash When Loading Multiple SVGs

### ISSUE THREAD

**Issue by asutula** [SVGKit/SVGKit#97]
I wrote a simple wrapper class around SVGKit that outputs UIImage objects:

```
@implementation SSSVGImage
- (UIImage *)imageWithSvgNamed:(NSString *)name color:(UIColor *)color scale (CGFloat)scale
{
    SVGKSource *source = [SVGKSource sourceFromFilename:[[NSBundle mainBundle] pathForResource:name ofType:@"svg"]];

     SVGKParser *parser = [[SVGKParser alloc] initWithSource:source];
    [parser addDefaultSVGParserExtensions];

    SVGKParseResult* result = [parser parseSynchronously];

    SVGKImage *svg = [[SVGKImage alloc] initWithParsedSVG:result];

    svg.size = CGSizeMake(svg.size.width * scale, svg.size.height * scale);

    if (color) {
        NSString *id = @"SVG-TESTup";

        CALayer *layer = [svg layerWithIdentifier:id];

        for (CALayer *sublayer in layer.sublayers) {
            if ([sublayer isKindOfClass:[CAShapeLayer class]]) {
                ((CAShapeLayer *)sublayer).fillColor = color.CGColor;
            }
        }
    }

    return svg.UIImage;
}
@end
```

During the initialization of a view controller, I can use this class to set the image for a button, for example, and it works fine. 

In a situation where I have a second view controller that is loaded immediately after the first (within a split view controller, for example), I attempt to use this class to set the button image within the second view controller, and SVGKit crashes. The top of the stack trace is:

```
#1  0x01bb4363 in -[NSScanner scanCharactersFromSet:intoString:] ()
#2  0x0016636d in +[SVGKPointsAndPathsParser readWhitespace:] at /Users/asutula/Documents/SS/Projects/Code/myproject/Pods/SVGKit/Source/Parsers/SVGKPointsAndPathsParser.m:206
...
```

I don't usually see a meaningful message in the console, but one time it printed:

```
2013-07-31 11:35:48.380 Blog[57135:c07] -[__NSArrayM invertedSet]: unrecognized selector sent to instance 0x12aa2be0
2013-07-31 11:35:48.382 Blog[57135:c07] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM invertedSet]: unrecognized selector sent to instance 0x12aa2be0'
```

If I comment out the setting of the button image in the first view controller, the second works fine. One or the other work, but not both.

This seems like possibly a threading issue, but it's not clear to me that there are actually multiple threads involved.

**Comment by asutula** [comment]
I was experiencing this problem on the 1.0 tag using Cocoapods. When I reference :head for my version (thus pulling the master branch), the problem goes away. Looking at the commit logs, I'm guessing it's this commit that fixes it: https://github.com/SVGKit/SVGKit/commit/403b59ee4b682873834f565d68e33f88c3d9097c

**Comment by adamgit** [comment]
That looks correct, yes.

**Comment by asutula** [comment]
Any timeline for when another release will be made available via Cocoapods?

**Comment by adamgit** [comment]
Good question.

I got 90% through verifying all fixes for a new release, but then we had a
big influx of fixes from different people that conflicted (couldn't be
auto-merged).

I was hoping we'd pull those out separately, but it's been a couple of
months and no-one's had time, so...

...I think I'll aim to get a quick release pushed out, and we can revisit
the contributed fixes in the NEXT release.
