### ISSUE TITLE
Applying fill color to a SVGImage / SVGImageView

### ISSUE THREAD

**Issue by sarperdag** [SVGKit/SVGKit#98]
How is it possible to color fill an SVGImage or SVGImageView? I've been trying to loop through the sublayers of these objects and all I get are CALayers that do not have any fillColor property... I can't seem to find any CAShapeLayers anywhere... 

Any suggestions?

**Comment by adamgit** [comment]
CALayer is the superclass of CAShapeLayer ... you probably want to typecast them to CAShapeLayer (make sure you check first! some of the layers will be grouped inside raw CALayers).

e.g.
if( [sublayer isKindOfClass:[CAShapeLayer class]] )
{
   CAShapeLayer \* shapeLayer = (CAShapeLayer*) sublayer;
   ... do your stuff here ...
}

(I've used this a few times in different apps, works fine)

**Comment by sarperdag** [comment]
I've already tried this. 

Here is the code I use

```
SVGKImage *svgImage = [SVGKImage imageNamed:@"Anchor.svg"];
SVGKFastImageView *svgImageView = [[SVGKFastImageView alloc] initWithSVGKImage:svgImage];
[self.view addSubview:svgImageView];
```

And here is what "po svgImageView.layer" gives:

```
$2 = 0x14a213e0 <CALayer:0x14a213e0; position = CGPoint (396 306); bounds = CGRect (0 0; 792 612); delegate =     <SVGKFastImageView: 0x14a21480; frame = (0 0; 792 612); layer = <CALayer: 0x14a213e0>>; rasterizationScale = 2; contentsScale = 2>
```

So, no sublayers under svgImageView.layer and nothing of type CAShapeLayer anywhere either... 

Also, here is the svg i I use

https://dl.dropboxusercontent.com/u/1124427/Anchor.svg

**Comment by adamgit** [comment]
Svgkfastinageview does not expose the layers - thats what makes it "fast".

If you want the layers, you ask svgkimage to export them for you - this is
nothing to do with an imageview class!

Alternatively, you can use svgklayeredimageview, which exposes the layers -
thats why ts called "layered".

Normally, if youre changing layers, you do it directly on an image and the
 feed those layers into your own uikit views ... Or you use
 layersdimageview, where you update apples layers directly while theyre on
screen.

For obvious reasons, this is slower than using fastimageview. But it cant
be fast if youre changing the underlying data :) !

**Comment by sarperdag** [comment]
Well, even fi I use SVGKLayeredImageView, still can't find any CAShapeLayers...

```
SVGKImage *svgImage = [SVGKImage imageNamed:@"Anchor.svg"];

SVGKLayeredImageView *svgImageView = [[SVGKLayeredImageView alloc] initWithSVGKImage:svgImage];
[sefl.view addSubview:svgImageView];

CALayer* layer = svgImageView.layer;
for (CALayer *subLayer in layer.sublayers) {
    if( [layer isKindOfClass:[CAShapeLayer class]] )
    {
        CAShapeLayer* shapeLayer = (CAShapeLayer*)layer;
        shapeLayer.fillColor = [UIColor redColor].CGColor;
    }
}
```

this never falls in the if condition...

**Comment by sarperdag** [comment]
All I get are layers of type CALayerWithChildHitTest and these do not have a fill color property...

**Comment by adamgit** [comment]
It sounds like your SVG has no rendering elements. You should be getting
CAShapeLayerWithChildHitTest (which, unsurprisingly :), is a subclass of
CAShapeLayer).

Your file renders correctly, right?

Is it possible that the source file has no shapes (polygons, ellipse, line,
path, polyline, rect) - that it only uses text, or only uses bitmaps, or
something?

**Comment by sarperdag** [comment]
Yeah the file renders correctly. 

But it might be possible it has no shapes. These are just simple drawings designed on Adobe Ilustrator by our designer. Coloring a layer is not possible if the svg file only uses text / bimaps?

**Comment by adamgit** [comment]
You can always change the background colour of a layer - CALayer has a
bunch of built-in properties (e.g. "backgroundColor") that work on any
layer.

By definition ... if you've saved your data as non-SVG, non-vector ... it
would be physically impossible to colour it any other way - you would have
_already deleted_ all the shapes information needed.

But I'd be surprised - by default, AI shouldn't be removing the vector
data. Can you open the file in a text editor and check what svg tags are
inside it?

If it has any of the vector tags, we may have a new bug

**Comment by sarperdag** [comment]
Sure, actually here is my svg file if you wanna take a look at it...

https://dl.dropboxusercontent.com/u/1124427/Anchor.svg

**Comment by adamgit** [comment]
You've got a path - that should work fine.

Can you do a recursive NSLog of all your CALayers and their sublayers, with
the class of each?

Judging by your SVG file, should be something like:

calayerwithhittest
- calayerwithhittest
  - cashapelayerwithhittest
  - cashapelayerwithhittest
  - cashapelayerwithhittest
  - cashapelayerwithhittest

Also, if that doesn't work, I suggest you:
1. remove your svgkimageview (for testing)
2. use [svgkimage calayertree] directly
3. put a breakpoint on that line above
4. step into the call, and step through it to watch it creating the layers
5. ...it should create a CAShapeLayer each time it encounters one of your
   "path" tags

I'm afraid I don't have time to debug this for you at the moment, I'm too
busy with paid work for anything but very brief help for SVG users right
now :(

**Comment by sarperdag** [comment]
Thanks Adam, 

It worked when I built the loop like this. Now I also understand the SVG file format better... Thank you very much for your help.

```
SVGKImage *svgImage = [SVGKImage imageNamed:@"Anchor.svg"];
SVGKLayeredImageView *svgImageView = [[SVGKLayeredImageView alloc] initWithSVGKImage:svgImage];
[capturedImageView addSubview:svgImageView];

CALayer* layer = svgImageView.layer;
for (CALayer *subLayer in layer.sublayers) {
    DLog(@"%@", [subLayer class]);

    for (CALayer *subSubLayer in subLayer.sublayers) {
        DLog(@"%@", [subSubLayer class]);

        for (CALayer *subSubSubLayer in subSubLayer.sublayers) {
            DLog(@"%@", [subSubSubLayer class]);

            if( [subSubSubLayer isKindOfClass:[CAShapeLayer class]]){
                CAShapeLayer* shapeLayer = (CAShapeLayer*)subSubSubLayer;
                shapeLayer.fillColor = [UIColor redColor].CGColor;
            }
        }
    }
}
```

**Comment by adamgit** [comment]
OK, so, to recap:
- Problem was: the layers that SVG generates can be multiple levels of
  nesting deep

?

(I think this is effectively forced on us by the SVG spec: each "g" tag and
each shape tag, and the top-level tag, are required to have their own
"co-ordinate space" (each one can apply a transform / scale / rotate /
etc). The clean way to do this is we create a new CALayer at each level
down, and embed the sublayers recursively)

**Comment by sarperdag** [comment]
Yes, this is the exact problem. This should be done on the SVGKit side or on my app's implementation?

**Comment by adamgit** [comment]
I think the only thing to do is improve the documentation, maybe.

This is "As designed, as per Spec".

But I wanted to make sure!

**Comment by tptee** [comment]
I used this function on simple SVG icons to change their fillColor. Just pass it a CALayerTree from your SVGKImage. It should work on arbitrarily nested layers. Thought it might be helpful!

``` swift
func changeFillColorRecursively(sublayers: [AnyObject], color: UIColor) {
    for layer in sublayers {
        if let l = layer as? CAShapeLayer {
            l.fillColor = color.CGColor
        }
        if let l = layer as? CALayer, sub = l.sublayers {
            changeFillColorRecursively(sub, color: color)
        }
    }
}
```

**Comment by squall2022** [comment]
Thanks @tptee, I upgraded your function to support both fillColor and strokeColor in an extension :

``` swift
extension SVGKImageView {

    func setTintColor(color: UIColor) {
        if self.image != nil && self.image.caLayerTree != nil {
            changeFillColorRecursively(sublayers: self.image.caLayerTree.sublayers, color: color)
        }
    }

    private func changeFillColorRecursively(sublayers: [AnyObject]?, color: UIColor) {
        if let sublayers = sublayers {
            for layer in sublayers {
                if let l = layer as? CAShapeLayer {
                    if l.strokeColor != nil {
                        l.strokeColor = color.cgColor
                    }
                    if l.fillColor != nil {
                        l.fillColor = color.cgColor
                    }
                }
                if let l = layer as? CALayer, let sub = l.sublayers {
                    changeFillColorRecursively(sublayers: sub, color: color)
                }
            }
        }
    }
}
```

**Comment by adamgit** [comment]
Looks nice. Perhaps make a wiki page for useful functions like that, and link it from the README

**Comment by Juice007** [comment]
I know a method that can change the color of an UIImage.
So, we should get the UIImage from SVGKImage firstly.

    UIImage *img = [SVGKImage imageNamed:@"imageName"].UIImage;

And then, we can define a method like this:

    - (UIImage *)changeTintColorWithImage:(UIImage *)img color:(UIColor *)tintColor {
    UIImage *imageIn = img;
    CGRect rect = CGRectMake(0, 0, imageIn.size.width, imageIn.size.height);
    CGImageAlphaInfo alphaInfo = CGImageGetAlphaInfo(imageIn.CGImage);
    BOOL opaque = alphaInfo == kCGImageAlphaNoneSkipLast
    || alphaInfo == kCGImageAlphaNoneSkipFirst
    || alphaInfo == kCGImageAlphaNone;
    UIGraphicsBeginImageContextWithOptions(imageIn.size, opaque, imageIn.scale);
    CGContextRef context = UIGraphicsGetCurrentContext();
    CGContextTranslateCTM(context, 0, imageIn.size.height);
    CGContextScaleCTM(context, 1.0, -1.0);
    CGContextSetBlendMode(context, kCGBlendModeNormal);
    CGContextClipToMask(context, rect, imageIn.CGImage);
    CGContextSetFillColorWithColor(context, tintColor.CGColor);
    CGContextFillRect(context, rect);
    UIImage *imageOut = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return imageOut;
    }
OK. this method can help us change the color of an image.It mainly use some APIs in CoreGraphics.
And I suggest you can create a category with UIImage, it will be convenient to use.

**Comment by kaynewbie** [comment]
@sarperdag I have another question: If I use `SVGKLayeredImageView`, the sublayers didn't render in the bounds. Can you help?

**Comment by ghost** [comment]
Thanks, @squall2022  I've update your function to color the layers with respect to the ID.

if you have any id for the SVG image, you can fill the colours with respect to the ID.

```
    let image = SVGKImage(named: "iconName")
    let svgIMGV = SVGKFastImageView(frame: self.imgView.frame)
         svgIMGV.image = image
          svgIMGV.fillTintColor(colorImage: UIColor.red, iconID: "Bank")
```



```

// added  in extension SVGKImageView 
 func fillTintColor(colorImage: UIColor, iconID: String) {
        if self.image != nil && self.image.caLayerTree != nil {
            print(self.image.caLayerTree.sublayers)
            guard let sublayers = self.image.caLayerTree.sublayers else { return }
            fillRecursively(sublayers: sublayers, color: colorImage, iconID: iconID)
        }
    }
    
     private func fillRecursively(sublayers: [CALayer], color: UIColor, iconID: String, hasFoundLayer: Bool) {
        var isLayerFound = false
        for layer in sublayers {
            if let l = layer as? CAShapeLayer {
                
                print(l.name)                
                //IF you want to color the specific shapelayer by id else remove the l.name  == "myID"  validation
                if let name =  l.name,  hasFoundLayer == true && name == "myID" {
                    self.colorThatImageWIthColor(color: color, layer: l)
                    print("Colouring FInished")
                }
            } else {
                if layer.name == iconID {
                    if let innerSublayer = layer.sublayers as? [CAShapeLayer] {
                        fillRecursively(sublayers: innerSublayer, color: color, iconID: iconID, hasFoundLayer: true )
                        print("FOund")
                    }
                } else {
                    if let l = layer as? CALayer, let sub = l.sublayers {
                        fillRecursively(sublayers: sub, color: color, iconID: iconID, hasFoundLayer: false)
                    }
                }
            }
           
        }
    }
    
    func colorThatImageWIthColor(color: UIColor, layer: CAShapeLayer) {
        if layer.strokeColor != nil {
            layer.strokeColor = color.cgColor
        }
        if layer.fillColor != nil {
            layer.fillColor = color.cgColor
        }
    }
    

```
