### ISSUE TITLE
Doesn't compile in certain iOS versions

### ISSUE THREAD

**Issue by buscarini** [SVGKit/SVGKit#99]
SVGRectElement declares a function CGPathAddRoundedRect, which might have been added in “some” iOS beta versions

**Comment by zeeshanlakhani** [comment]
Yeah. `CGPathAddRoundedRect` is throwing errors on build of some of the beta versions.

**Comment by miwillhite** [comment]
+1

**Comment by IamAliSufyan** [comment]
Facing same build errors. Please fix it

**Comment by adamgit** [comment]
Personally, I don't run the iOS betas (too many bugs until you get to the very final one).

If you want to rename that method, go for it - do a global rename in the source, check the Demo still works (it has an image that uses roudnded rects and nothing else, should be a good test). 

Or even better: see if the method can be deleted, and we can use the new Apple one instead. Use a #if check to see which version of iOS it is, and use the Apple one for new iOS, our one for old iOS.

Github will turn it into a pull request for you, I'll give it a quick check, and merge immediately if it seems to work.
